// Auto-generated by Protovibe Sketchpad
import { Rectangle } from '@/components/ui/rectangle';

export default function Frame3() {
  return (
    <div data-layout-mode="absolute" style={{ width: '100%', height: '100%', position: 'relative' }}>
      {/* pv-editable-zone-start:lsfr9z */}
      
      {/* pv-block-start:2gpu7q */}
      <Rectangle data-pv-block="2gpu7q" data-pv-sketchpad-el="2gpu7q"  style={{ position: 'absolute', left: 50, top: 50 }}>
        {/* pv-editable-zone-start:pzy7kq */}
        {/* pv-editable-zone-end:pzy7kq */}
      </Rectangle>
      {/* pv-block-end:2gpu7q */}
      {/* pv-editable-zone-end:lsfr9z */}
    </div>
  );
}
