// Auto-generated by Protovibe Sketchpad
import { Button } from '@/components/ui/button';
import { Rectangle } from '@/components/ui/sketchpad-rectangle';
import { Card } from '@/components/ui/card';
import { Checkbox } from '@/components/ui/checkbox';
import { Avatar } from '@/components/ui/avatar';
import { TextBlock } from '@/components/ui/text-block'
import { RadioGroup } from '@/components/ui/radio-group'
import { RadioItem } from '@/components/ui/radio-item'
import { Badge } from '@/components/ui/badge'
import { Icon } from '@/components/ui/icon'
import { SuperLabel } from '@/components/ui/super-label'
import { SelectDropdown } from '@/components/ui/select-dropdown';
import { DropdownItem } from '@/components/ui/dropdown-item';

export default function Frame3() {
  return (
    <div data-layout-mode="absolute" style={{ width: '100%', height: '100%', position: 'relative' }}>
      {/* pv-editable-zone-start:b399cq */}
      {/* pv-block-start:xn7mdg */}
      <div data-pv-block="xn7mdg" className="flex flex-col gap-2" data-pv-sketchpad-el="xn7mdg" style={{ position: 'absolute', width: 131, left: 79, top: 429 }}>
        {/* pv-editable-zone-start:ni67pr */}
        {/* pv-block-start:m1moro */}
        <Avatar data-pv-block="m1moro" initials="AB" size="md" bgColor="default" imageSrc="https://i.pravatar.cc/60"  />
        {/* pv-block-end:m1moro */}

        {/* pv-block-start:zxz1lq */}
        <div data-pv-block="zxz1lq" className="flex flex-col gap-2" >
          {/* pv-editable-zone-start:2iatij */}
          {/* pv-block-start:c7keys */}
          <div data-pv-block="c7keys" className="flex flex-col gap-2" >
          {/* pv-editable-zone-start:qubfhb */}
          {/* pv-block-start:hx6ptm */}
          <div data-pv-block="hx6ptm" className="flex flex-col gap-10" >
          {/* pv-editable-zone-start:c2rycc */}
          {/* pv-block-start:720a3j */}
          <Button data-pv-block="720a3j" label="Button" variant="solid" color="primary" size="md"  />
          {/* pv-block-end:720a3j */}
          {/* pv-editable-zone-end:c2rycc */}
          </div>
          {/* pv-block-end:hx6ptm */}
          {/* pv-editable-zone-end:qubfhb */}
          </div>
          {/* pv-block-end:c7keys */}
          {/* pv-editable-zone-end:2iatij */}
        </div>
        {/* pv-block-end:zxz1lq */}
        {/* pv-editable-zone-end:ni67pr */}
      </div>
      {/* pv-block-end:xn7mdg */}

      {/* pv-block-start:actnnw */}
      <div data-pv-block="actnnw" className="flex flex-col gap-2" data-pv-sketchpad-el="actnnw" style={{ position: 'absolute', width: 131, left: 229, top: 494 }}>
        {/* pv-editable-zone-start:ni67pr */}
        {/* pv-block-start:i44eri */}
        <Avatar data-pv-block="i44eri" initials="AB" size="md" bgColor="default" imageSrc="https://i.pravatar.cc/60"  />
        {/* pv-block-end:i44eri */}

        {/* pv-block-start:p745g9 */}
        <div data-pv-block="p745g9" className="flex flex-col gap-2" >
          {/* pv-editable-zone-start:2iatij */}
          {/* pv-block-start:7e1r3h */}
          <div data-pv-block="7e1r3h" className="flex flex-col gap-2" >
          {/* pv-editable-zone-start:qubfhb */}
          {/* pv-block-start:fuleui */}
          <div data-pv-block="fuleui" className="flex flex-col gap-10" >
          {/* pv-editable-zone-start:c2rycc */}
          {/* pv-block-start:k938ao */}
          <Button data-pv-block="k938ao" label="Button" variant="solid" color="primary" size="md"  />
          {/* pv-block-end:k938ao */}
          {/* pv-editable-zone-end:c2rycc */}
          </div>
          {/* pv-block-end:fuleui */}
          {/* pv-editable-zone-end:qubfhb */}
          </div>
          {/* pv-block-end:7e1r3h */}
          {/* pv-editable-zone-end:2iatij */}
        </div>
        {/* pv-block-end:p745g9 */}
        {/* pv-editable-zone-end:ni67pr */}
      </div>
      {/* pv-block-end:actnnw */}

      {/* pv-block-start:hqmnfc */}
      <div data-pv-block="hqmnfc" className="flex flex-col gap-2" data-pv-sketchpad-el="hqmnfc" style={{ position: 'absolute', width: 131, left: 390, top: 497 }}>
        {/* pv-editable-zone-start:ni67pr */}
        {/* pv-block-start:r82nu7 */}
        <Avatar data-pv-block="r82nu7" initials="AB" size="md" bgColor="default" imageSrc="https://i.pravatar.cc/60"  />
        {/* pv-block-end:r82nu7 */}

        {/* pv-block-start:q3rzwk */}
        <div data-pv-block="q3rzwk" className="flex flex-col gap-2" >
          {/* pv-editable-zone-start:2iatij */}
          {/* pv-block-start:i2jxbr */}
          <div data-pv-block="i2jxbr" className="flex flex-col gap-2" >
          {/* pv-editable-zone-start:qubfhb */}
          {/* pv-block-start:hkk5oo */}
          <div data-pv-block="hkk5oo" className="flex flex-col gap-10" >
          {/* pv-editable-zone-start:c2rycc */}
          {/* pv-block-start:aaubt8 */}
          <Button data-pv-block="aaubt8" label="Button" variant="solid" color="primary" size="md"  />
          {/* pv-block-end:aaubt8 */}
          {/* pv-editable-zone-end:c2rycc */}
          </div>
          {/* pv-block-end:hkk5oo */}
          {/* pv-editable-zone-end:qubfhb */}
          </div>
          {/* pv-block-end:i2jxbr */}
          {/* pv-editable-zone-end:2iatij */}
        </div>
        {/* pv-block-end:q3rzwk */}
        {/* pv-editable-zone-end:ni67pr */}
      </div>
      {/* pv-block-end:hqmnfc */}

      {/* pv-block-start:c587un */}
        <Avatar data-pv-block="c587un" initials="AB" size="md" bgColor="default" imageSrc="https://i.pravatar.cc/60"   data-pv-sketchpad-el="c587un" style={{ position: 'absolute', left: 172, top: 362 }}/>
        {/* pv-block-end:c587un */}
      
      {/* pv-block-start:ri3omq */}
      <Rectangle data-pv-block="ri3omq" data-pv-sketchpad-el="ri3omq" className="w-[200px] h-[200px]" style={{ position: 'absolute', height: 287, left: 76, top: 40, width: 415 }}>
        {/* pv-editable-zone-start:duvsah */}
        {/* pv-block-start:wjkjlt */}
        <div data-pv-block="wjkjlt" className="flex flex-col gap-2" data-pv-sketchpad-el="wjkjlt" style={{ position: 'absolute', left: 17, top: 18 }}>
          {/* pv-editable-zone-start:kwz2ry */}
          {/* pv-editable-zone-end:kwz2ry */}
        </div>
        {/* pv-block-end:wjkjlt */}

        {/* pv-block-start:8eoc96 */}
        <div data-pv-block="8eoc96" className="flex flex-col gap-4" data-pv-sketchpad-el="8eoc96" style={{ position: 'absolute', left: 41, top: 24 }}>
          {/* pv-editable-zone-start:9rdg7j */}
          {/* pv-editable-zone-end:9rdg7j */}
        </div>
        {/* pv-block-end:8eoc96 */}

        {/* pv-block-start:d9hg1z */}
        <div data-pv-block="d9hg1z" className="flex flex-col gap-4" data-pv-sketchpad-el="d9hg1z" style={{ position: 'absolute', left: 50, top: 26 }}>
          {/* pv-editable-zone-start:8xrqx0 */}
          {/* pv-block-start:m2cqiv */}
          <Checkbox data-pv-block="m2cqiv" primaryText="Accept terms" />
          {/* pv-block-end:m2cqiv */}
          {/* pv-block-start:jnbdk7 */}
          <Checkbox data-pv-block="jnbdk7" primaryText="Accept terms" />
          {/* pv-block-end:jnbdk7 */}
          {/* pv-editable-zone-end:8xrqx0 */}
        </div>
        {/* pv-block-end:d9hg1z */}

        {/* pv-block-start:6lxa53 */}
      <Rectangle data-pv-block="6lxa53" data-pv-sketchpad-el="6lxa53"  style={{ position: 'absolute', left: 121, top: 116, height: 38, width: 235 }}>
        {/* pv-editable-zone-start:csc7wf */}
        {/* pv-editable-zone-end:csc7wf */}
      </Rectangle>
      {/* pv-block-end:6lxa53 */}

      {/* pv-block-start:6yknv7 */}
        <Avatar data-pv-block="6yknv7" initials="AB" size="md" bgColor="default" imageSrc="https://i.pravatar.cc/60"  data-pv-sketchpad-el="6yknv7" style={{ position: 'absolute', left: 115, top: 203 }}/>
        {/* pv-block-end:6yknv7 */}

      {/* pv-block-start:cc5rmm */}
        <Avatar data-pv-block="cc5rmm" initials="AB" size="md" bgColor="default" imageSrc="https://i.pravatar.cc/60"   data-pv-sketchpad-el="cc5rmm" style={{ position: 'absolute', left: 221, top: 183 }}/>
        {/* pv-block-end:cc5rmm */}

        {/* pv-block-start:vumf74 */}
      <Button data-pv-block="vumf74" label="Button" variant="solid" color="primary" size="md"   data-pv-sketchpad-el="vumf74" style={{ position: 'absolute', left: 285, top: 36 }}/>
      {/* pv-block-end:vumf74 */}

        {/* pv-block-start:5ih57a */}
      <Button data-pv-block="5ih57a" label="Button" variant="solid" color="primary" size="md"   data-pv-sketchpad-el="5ih57a" style={{ position: 'absolute', left: 184, top: 51 }}/>
      {/* pv-block-end:5ih57a */}

        {/* pv-block-start:njunpm */}
                  <Button data-pv-block="njunpm" label="Button" variant="solid" color="primary" size="md"  data-pv-sketchpad-el="njunpm" style={{ position: 'absolute', left: 313, top: 193 }}/>
                  {/* pv-block-end:njunpm */}
        {/* pv-editable-zone-end:duvsah */}
      </Rectangle>
      {/* pv-block-end:ri3omq */}
      {/* pv-block-start:l3h2tm */}
        <Avatar data-pv-block="l3h2tm" initials="AB" size="md" bgColor="default" imageSrc="https://i.pravatar.cc/60"  data-pv-sketchpad-el="l3h2tm" style={{ position: 'absolute', left: 42, top: 334 }}/>
        {/* pv-block-end:l3h2tm */}

      {/* pv-block-start:yeg1ow */}
            <Card data-pv-block="yeg1ow" variant="bordered" shadow="sm" className="bg-background-default" data-pv-sketchpad-el="yeg1ow" style={{ position: 'absolute', left: 513, top: 39, width: 256 }}>
              {/* pv-editable-zone-start:c8d9e1 */}
              {/* pv-block-start:1r4vha */}
                <div data-pv-block="1r4vha" className="flex items-center gap-3 mb-2 text-foreground-secondary" >
                  {/* pv-editable-zone-start:i5j6k7 */}
                    {/* pv-block-start:g7w603 */}
                    <Icon data-pv-block="g7w603" name="Users" size="sm" />
                    {/* pv-block-end:g7w603 */}
                    {/* pv-block-start:nk8d96 */}
                    <TextBlock data-pv-block="nk8d96" typography="small" className="font-semibold uppercase tracking-wider">Total Headcount</TextBlock>
                    {/* pv-block-end:nk8d96 */}
                  {/* pv-editable-zone-end:i5j6k7 */}
                </div>
                {/* pv-block-end:1r4vha */}

                {/* pv-block-start:jvp5ts */}
                <div className="flex flex-col min-h-4" data-pv-block="jvp5ts">
                  {/* pv-editable-zone-start:inside-jvp5ts */}
                  {/* pv-editable-zone-end:inside-jvp5ts */}
                </div>
                {/* pv-block-end:jvp5ts */}

              {/* pv-block-start:1yo64s */}
      <SuperLabel heading="Test" data-pv-block="1yo64s" primaryText="Label"  />
      {/* pv-block-end:1yo64s */}

              {/* pv-block-start:ttp0x0 */}
                <Badge data-pv-block="ttp0x0" label="+12% vs last year" color="success" prefixIcon="TrendingUp" />
                {/* pv-block-end:ttp0x0 */}
                {/* pv-block-start:17etj5 */}
      <Card className="" data-pv-block="17etj5" variant="bordered" shadow="none" border="default" >
        {/* pv-editable-zone-start:xi74a7 */}
        {/* pv-editable-zone-end:xi74a7 */}
      </Card>
      {/* pv-block-end:17etj5 */}

              {/* pv-block-start:aow6j7 */}
                  <div className="flex flex-col min-h-4" data-pv-block="aow6j7">
                  Test
                  {/* pv-editable-zone-start:inside-aow6j7 */}
                  {/* pv-editable-zone-end:inside-aow6j7 */}
                  </div>
                  {/* pv-block-end:aow6j7 */}

      {/* pv-block-start:fh4xr5 */}
        <Avatar data-pv-block="fh4xr5" initials="AB" size="md" bgColor="default" imageSrc="https://i.pravatar.cc/60"   data-pv-sketchpad-el="fh4xr5" style={{ position: 'absolute', left: 158, top: 247 }}/>
        {/* pv-block-end:fh4xr5 */}
      
      {/* pv-block-start:ryhp4i */}
                  <Button data-pv-block="ryhp4i" label="Button" variant="solid" color="primary" size="md" />
                  {/* pv-block-end:ryhp4i */}
                  {/* pv-block-start:o8itux */}
        <Avatar data-pv-block="o8itux" initials="AB" size="md" bgColor="default" imageSrc="https://i.pravatar.cc/60" />
        {/* pv-block-end:o8itux */}

              {/* pv-block-start:ix5c3r */}
      <Button data-pv-block="ix5c3r" label="Button" variant="solid" color="primary" size="md" />
      {/* pv-block-end:ix5c3r */}
              {/* pv-editable-zone-end:c8d9e1 */}
            </Card>
            {/* pv-block-end:yeg1ow */}
      
      {/* pv-block-start:m8d3jh */}
          <div data-pv-block="m8d3jh" className="flex flex-col gap-2" data-pv-sketchpad-el="m8d3jh" style={{ position: 'absolute', left: 257, top: 355 }}>
          {/* pv-editable-zone-start:bla8ry */}
          {/* pv-block-start:ki590k */}
          <Button data-pv-block="ki590k" label="Button" variant="solid" color="primary" size="md" />
          {/* pv-block-end:ki590k */}
          {/* pv-editable-zone-end:bla8ry */}
          </div>
          {/* pv-block-end:m8d3jh */}

      {/* pv-block-start:rbuu92 */}
        <Avatar data-pv-block="rbuu92" initials="AB" size="md" bgColor="default" imageSrc="https://i.pravatar.cc/60"   data-pv-sketchpad-el="rbuu92" style={{ position: 'absolute', left: 28, top: 67 }}/>
        {/* pv-block-end:rbuu92 */}
      
      {/* pv-block-start:0sc46q */}
        <Avatar data-pv-block="0sc46q" initials="AB" size="md" bgColor="default" imageSrc="https://i.pravatar.cc/60"   data-pv-sketchpad-el="0sc46q" style={{ position: 'absolute', left: 329, top: 435 }}/>
        {/* pv-block-end:0sc46q */}
      {/* pv-editable-zone-end:b399cq */}
    </div>
  );
}
