// Auto-generated by Protovibe Sketchpad
import { Container } from '@/components/ui/container';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { SuperLabel } from '@/components/ui/super-label';
import { Rectangle } from '@/components/ui/sketchpad-rectangle'
import { Checkbox } from '@/components/ui/checkbox'
import { Avatar } from '@/components/ui/avatar'
import { Card } from '@/components/ui/card'
import { Icon } from '@/components/ui/icon'
import { TextBlock } from '@/components/ui/text-block'
import { Badge } from '@/components/ui/badge'

export default function Frame4() {
  return (
    <div data-layout-mode="absolute" style={{ width: '100%', height: '100%', position: 'relative' }}>
      {/* pv-editable-zone-start:6g9nd2 */}
      {/* pv-block-start:qndewo */}
      <Container data-pv-block="qndewo" data-pv-sketchpad-el="qndewo"  style={{ position: 'absolute', left: 140, top: 126 }}>
        {/* pv-editable-zone-start:z2yarx */}
        {/* pv-editable-zone-end:z2yarx */}
      </Container>
      {/* pv-block-end:qndewo */}
      
      {/* pv-block-start:lv8rzw */}
      <div data-pv-block="lv8rzw" className="flex flex-col gap-2" data-pv-sketchpad-el="lv8rzw" style={{ position: 'absolute', width: 401, left: 61, top: 58 }}>
        {/* pv-editable-zone-start:i7bwgp */}
        {/* pv-block-start:yzabkm */}
      <SuperLabel secondaryText="Uważaj co wpisujesz!" heading="Wybierz co tam chcesz!" data-pv-block="yzabkm" primaryText=""  />
      {/* pv-block-end:yzabkm */}
        {/* pv-block-start:ie8zg7 */}
        <Input data-pv-block="ie8zg7" placeholder="Enter text..."  />
        {/* pv-block-end:ie8zg7 */}

        {/* pv-block-start:hnanzk */}
        <Button data-pv-block="hnanzk" label="Button" variant="solid" color="primary" size="md" />
        {/* pv-block-end:hnanzk */}

        {/* pv-block-start:f61y5m */}
      <div data-pv-block="f61y5m" className="flex gap-2 flex-row" >
        {/* pv-editable-zone-start:e0x6wo */}
        {/* pv-block-start:szmlt9 */}
        <Avatar data-pv-block="szmlt9" initials="AB" size="md" bgColor="default" imageSrc="https://i.pravatar.cc/60"  />
        {/* pv-block-end:szmlt9 */}
        {/* pv-block-start:z7lprl */}
        <Avatar data-pv-block="z7lprl" initials="AB" size="md" bgColor="default" imageSrc="https://i.pravatar.cc/60"  />
        {/* pv-block-end:z7lprl */}
        {/* pv-editable-zone-end:e0x6wo */}
      </div>
      {/* pv-block-end:f61y5m */}
        {/* pv-editable-zone-end:i7bwgp */}
      </div>
      {/* pv-block-end:lv8rzw */}

      {/* pv-block-start:scxs8b */}
      <div data-pv-block="scxs8b" className="flex flex-col gap-2" data-pv-sketchpad-el="scxs8b" style={{ position: 'absolute', left: 78, top: 377, width: 287 }}>
        {/* pv-editable-zone-start:i7bwgp */}
        {/* pv-block-start:f4pt37 */}
      <SuperLabel secondaryText="Uważaj co wpisujesz!" heading="Wybierz co tam chcesz!" data-pv-block="f4pt37" primaryText=""  />
      {/* pv-block-end:f4pt37 */}
        {/* pv-block-start:4mqcma */}
        <Input data-pv-block="4mqcma" placeholder="Enter text..."  />
        {/* pv-block-end:4mqcma */}
        {/* pv-editable-zone-end:i7bwgp */}
      </div>
      {/* pv-block-end:scxs8b */}
      
      {/* pv-block-start:txjw3m */}
        <Button data-pv-block="txjw3m" label="Button" variant="solid" color="primary" size="md"  data-pv-sketchpad-el="txjw3m" style={{ position: 'absolute', left: 59, top: 289 }}/>
        {/* pv-block-end:txjw3m */}
      
      {/* pv-block-start:m3347o */}
      <div data-pv-block="m3347o" className="flex gap-2 flex-row"  data-pv-sketchpad-el="m3347o" style={{ position: 'absolute', left: 569, top: 74 }}>
        {/* pv-editable-zone-start:e0x6wo */}
        {/* pv-block-start:g6s64f */}
        <Avatar data-pv-block="g6s64f" initials="AB" size="md" bgColor="default" imageSrc="https://i.pravatar.cc/60"  />
        {/* pv-block-end:g6s64f */}
        {/* pv-block-start:yrq73t */}
        <Avatar data-pv-block="yrq73t" initials="AB" size="md" bgColor="default" imageSrc="https://i.pravatar.cc/60"  />
        {/* pv-block-end:yrq73t */}
        {/* pv-editable-zone-end:e0x6wo */}
      </div>
      {/* pv-block-end:m3347o */}
      {/* pv-editable-zone-end:6g9nd2 */}
    </div>
  );
}
