// Auto-generated by Protovibe Sketchpad
import { RadioGroup } from '@/components/ui/radio-group';
import { RadioItem } from '@/components/ui/radio-item';
import { Card } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { DialogTrigger } from '@/components/ui/dialog-trigger'
import { DialogOverlay } from '@/components/ui/dialog-overlay'
import { DialogWindow } from '@/components/ui/dialog-window'
import { Tabs } from '@/components/ui/tabs'
import { TabItem } from '@/components/ui/tab-item'

export default function Frame1() {
  return (
    <div data-layout-mode="absolute" style={{ width: '100%', height: '100%', position: 'relative' }}>
      {/* pv-editable-zone-start:t362fh */}
      {/* pv-block-start:h9byvi */}
      <Card data-pv-block="h9byvi" data-pv-sketchpad-el="h9byvi" variant="bordered" shadow="none" style={{ position: 'absolute', width: 320, left: 385, top: 88 }}>
        {/* pv-editable-zone-start:e5p33e */}
        {/* pv-block-start:frvi1v */}
      <Card data-pv-block="frvi1v" variant="bordered" shadow="none" >
        {/* pv-editable-zone-start:ftmlni */}
        {/* pv-editable-zone-end:ftmlni */}
      </Card>
      {/* pv-block-end:frvi1v */}

        {/* pv-block-start:sqlxpm */}
          <RadioItem data-pv-block="sqlxpm" value="opt2" primaryText="Option Two" secondaryText="Description for option two" />
          {/* pv-block-end:sqlxpm */}

          {/* pv-block-start:1635fu */}
          <span data-pv-block="1635fu">
            Lorem ipsum
            {/* pv-editable-zone-start:inside-1635fu */}
            {/* pv-editable-zone-end:inside-1635fu */}
          </span>
          {/* pv-block-end:1635fu */}

        {/* pv-block-start:4shxnk */}
        <Button data-pv-block="4shxnk" label="Button" variant="solid" color="primary" size="md" />
        {/* pv-block-end:4shxnk */}

        {/* pv-block-start:is8e3x */}
        <Tabs data-pv-block="is8e3x"  value="tab1">
          {/* pv-editable-zone-start:76mqr2 */}
            {/* pv-block-start:yb94od */}
            <TabItem data-pv-block="yb94od" label="Tab 1" value="tab1" />
            {/* pv-block-end:yb94od */}
            {/* pv-block-start:xfhu3s */}
            <TabItem data-pv-block="xfhu3s" label="Tab 2" value="tab2" />
            {/* pv-block-end:xfhu3s */}
            {/* pv-block-start:73ah00 */}
            <TabItem data-pv-block="73ah00" label="Tab 3" value="tab3" />
            {/* pv-block-end:73ah00 */}
          {/* pv-editable-zone-end:76mqr2 */}
        </Tabs>
        {/* pv-block-end:is8e3x */}
        {/* pv-editable-zone-end:e5p33e */}
      </Card>
      {/* pv-block-end:h9byvi */}
      
      {/* pv-block-start:cos5bj */}
      <Card data-pv-block="cos5bj" data-pv-sketchpad-el="cos5bj" variant="bordered" shadow="none" style={{ position: 'absolute', left: 95, top: 324 }}>
        {/* pv-editable-zone-start:ev1pm3 */}
        {/* pv-editable-zone-end:ev1pm3 */}
      </Card>
      {/* pv-block-end:cos5bj */}
      
      {/* pv-block-start:gp85ke */}
      <Card data-pv-block="gp85ke" variant="bordered" shadow="none"  data-pv-sketchpad-el="gp85ke" style={{ position: 'absolute', width: 314, left: 27, top: 39 }}>
        {/* pv-editable-zone-start:t1i2jj */}
        {/* pv-block-start:eyxz9w */}
      <RadioGroup data-pv-block="eyxz9w" orientation="vertical" value="opt1" >
        {/* pv-editable-zone-start:mvy8s3 */}
          {/* pv-block-start:g7rhla */}
          <RadioItem data-pv-block="g7rhla" value="opt1" primaryText="Option One" secondaryText="Description for option one" />
          {/* pv-block-end:g7rhla */}
          {/* pv-block-start:zcxh5z */}
          <RadioItem data-pv-block="zcxh5z" value="opt3" primaryText="Option Three" secondaryText="Third option" />
          {/* pv-block-end:zcxh5z */}
        {/* pv-editable-zone-end:mvy8s3 */}
      </RadioGroup>
      {/* pv-block-end:eyxz9w */}
        {/* pv-editable-zone-end:t1i2jj */}
      </Card>
      {/* pv-block-end:gp85ke */}
      
      {/* pv-block-start:92l8ls */}
      <Button data-pv-block="92l8ls" label="Button" variant="solid" color="primary" size="md"   data-pv-sketchpad-el="92l8ls" style={{ position: 'absolute', left: 202, top: 379 }}/>
      {/* pv-block-end:92l8ls */}
      
      {/* pv-block-start:j3x4sx */}
      <Button data-pv-block="j3x4sx" data-pv-sketchpad-el="j3x4sx" label="Button" variant="solid" color="primary" size="md" style={{ position: 'absolute', left: 265, top: 280 }} />
      {/* pv-block-end:j3x4sx */}

        {/* pv-block-start:7pwpbi */}
        <span data-pv-block="7pwpbi">
          Lorem ipsum
          {/* pv-editable-zone-start:inside-7pwpbi */}
          {/* pv-editable-zone-end:inside-7pwpbi */}
        </span>
        {/* pv-block-end:7pwpbi */}
      
      {/* pv-block-start:mdhhao */}
      <Button data-pv-block="mdhhao" label="Button" variant="solid" color="primary" size="md"  data-pv-sketchpad-el="mdhhao" style={{ position: 'absolute', left: 519, top: 31 }}/>
      {/* pv-block-end:mdhhao */}

        {/* pv-block-start:0iavlg */}
        <DialogTrigger data-pv-block="0iavlg">
          {/* pv-editable-zone-start:uar3e6 */}
            {/* pv-block-start:83kqj7 */}
            <Button data-pv-block="83kqj7" label="Open Dialog" variant="solid" color="primary" size="md" />
            {/* pv-block-end:83kqj7 */}
            {/* pv-block-start:jso97n */}
            <DialogOverlay data-pv-block="jso97n">
              <DialogWindow size="md">
                {/* pv-editable-zone-start:2u5ol7 */}
                {/* pv-block-start:q3h5k8 */}
                <h2 data-pv-block="q3h5k8" className="text-xl font-semibold text-foreground-default mb-2">Dialog Title</h2>
                {/* pv-block-end:q3h5k8 */}
                {/* pv-block-start:cbvc6p */}
                <p data-pv-block="cbvc6p" className="text-foreground-secondary mb-6">This is the dialog content. Click the button below or press Escape to close.</p>
                {/* pv-block-end:cbvc6p */}
                {/* pv-editable-zone-end:2u5ol7 */}
              </DialogWindow>
            </DialogOverlay>
            {/* pv-block-end:jso97n */}
          {/* pv-editable-zone-end:uar3e6 */}
        </DialogTrigger>
        {/* pv-block-end:0iavlg */}

      {/* pv-block-start:ie4h1i */}
          <Button data-pv-block="ie4h1i" label="Button" variant="solid" color="primary" size="md"  data-pv-sketchpad-el="ie4h1i" style={{ position: 'absolute', left: 101, top: 245 }}/>
          {/* pv-block-end:ie4h1i */}

      {/* pv-block-start:zwbw45 */}
        <Button data-pv-block="zwbw45"  label="Button" variant="solid" color="primary" size="md"  data-pv-sketchpad-el="zwbw45" style={{ position: 'absolute', left: 260, top: 190 }}/>
        {/* pv-block-end:zwbw45 */}
      
      {/* pv-block-start:gadq61 */}
        <Tabs data-pv-block="gadq61"  value="tab1"  data-pv-sketchpad-el="gadq61" style={{ position: 'absolute', left: 386, top: 408 }}>
          {/* pv-editable-zone-start:w7kd7q */}
            {/* pv-block-start:7j2vkm */}
            <TabItem data-pv-block="7j2vkm" label="Tab 1" value="tab1" />
            {/* pv-block-end:7j2vkm */}
            {/* pv-block-start:cl9e5r */}
            <TabItem data-pv-block="cl9e5r" label="Tab 2" value="tab2" />
            {/* pv-block-end:cl9e5r */}
            {/* pv-block-start:bdxkft */}
            <TabItem data-pv-block="bdxkft" label="Tab 3" value="tab3" />
            {/* pv-block-end:bdxkft */}
          {/* pv-editable-zone-end:w7kd7q */}
        </Tabs>
        {/* pv-block-end:gadq61 */}
      
      {/* pv-block-start:adbdxr */}
      <Tabs data-pv-block="adbdxr" data-pv-sketchpad-el="adbdxr" value="tab1" style={{ position: 'absolute', left: 186, top: 503 }}>
        {/* pv-editable-zone-start:5afse6 */}
          {/* pv-block-start:uhqwcx */}
          <TabItem data-pv-block="uhqwcx" label="Tab 1" value="tab1" />
          {/* pv-block-end:uhqwcx */}
          {/* pv-block-start:yp8xxx */}
          <TabItem data-pv-block="yp8xxx" label="Tab 2" value="tab2" />
          {/* pv-block-end:yp8xxx */}
          {/* pv-block-start:spv4t0 */}
          <TabItem data-pv-block="spv4t0" label="Tab 3" value="tab3" />
          {/* pv-block-end:spv4t0 */}
        {/* pv-editable-zone-end:5afse6 */}
      </Tabs>
      {/* pv-block-end:adbdxr */}

      {/* pv-block-start:ozc6lt */}
          <div className="flex-col min-h-4 bg-background-secondary rounded-md flex w-1/2 py-5 pl-2 pr-5" data-pv-block="ozc6lt" data-pv-sketchpad-el="ozc6lt" style={{ position: 'absolute', left: 823, top: 90 }}>
            {/* pv-editable-zone-start:inside-ozc6lt */}
              {/* pv-block-start:m984bq */}
              <span data-pv-block="m984bq">
                Lorem ipsum
                {/* pv-editable-zone-start:inside-m984bq */}
                {/* pv-editable-zone-end:inside-m984bq */}
              </span>
              {/* pv-block-end:m984bq */}

            {/* pv-block-start:95zjmz */}
          <div className="flex flex-col min-h-4 p-5 bg-background-secondary rounded-md" data-pv-block="95zjmz">
            {/* pv-editable-zone-start:inside-95zjmz */}
              {/* pv-block-start:zf8gvj */}
              <span data-pv-block="zf8gvj">
                Lorem ipsum
                {/* pv-editable-zone-start:inside-zf8gvj */}
                {/* pv-editable-zone-end:inside-zf8gvj */}
              </span>
              {/* pv-block-end:zf8gvj */}
            {/* pv-editable-zone-end:inside-95zjmz */}
          </div>
          {/* pv-block-end:95zjmz */}

            {/* pv-block-start:631vwp */}
          <Button data-pv-block="631vwp" label="Open Dialog" variant="solid" color="primary" size="md" />
          {/* pv-block-end:631vwp */}

            {/* pv-block-start:58oqsv */}
              <Button data-pv-block="58oqsv" label="Button" variant="solid" color="primary" size="md" />
              {/* pv-block-end:58oqsv */}

            {/* pv-block-start:koia6v */}
          <Card className="flex justify-center flex-col items-start self-start shrink pr-10" data-pv-block="koia6v" variant="bordered" shadow="none">
            {/* pv-editable-zone-start:c1cn2h */}
            {/* pv-block-start:i7dvmz */}
          <Button data-pv-block="i7dvmz" label="Button" variant="solid" color="primary" size="md" />
          {/* pv-block-end:i7dvmz */}
            {/* pv-editable-zone-end:c1cn2h */}
          </Card>
          {/* pv-block-end:koia6v */}

              {/* pv-block-start:r7eil3 */}
              <DialogTrigger data-pv-block="r7eil3">
                {/* pv-editable-zone-start:n4ivbh */}
                  {/* pv-block-start:h19v31 */}
                  <Button data-pv-block="h19v31" label="Open Dialog" variant="solid" color="primary" size="md" />
                  {/* pv-block-end:h19v31 */}
                  {/* pv-block-start:r4fwl4 */}
                  <DialogOverlay data-pv-block="r4fwl4">
                    <DialogWindow size="md">
                      {/* pv-editable-zone-start:906s94 */}
                      {/* pv-block-start:9hii72 */}
                      <h2 data-pv-block="9hii72" className="text-xl font-semibold text-foreground-default mb-2">Dialog Title</h2>
                      {/* pv-block-end:9hii72 */}
                      {/* pv-block-start:52bi16 */}
                      <p data-pv-block="52bi16" className="text-foreground-secondary mb-6">This is the dialog content. Click the button below or press Escape to close.</p>
                      {/* pv-block-end:52bi16 */}
                      {/* pv-editable-zone-end:906s94 */}
                    </DialogWindow>
                  </DialogOverlay>
                  {/* pv-block-end:r4fwl4 */}
                {/* pv-editable-zone-end:n4ivbh */}
              </DialogTrigger>
              {/* pv-block-end:r7eil3 */}
            {/* pv-editable-zone-end:inside-ozc6lt */}
          </div>
          {/* pv-block-end:ozc6lt */}
      {/* pv-editable-zone-end:t362fh */}
    </div>
  );
}
