// Auto-generated by Protovibe Sketchpad
import { Card } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { DialogTrigger } from '@/components/ui/dialog-trigger';
import { DialogOverlay } from '@/components/ui/dialog-overlay';
import { DialogWindow } from '@/components/ui/dialog-window';
import { RadioGroup } from '@/components/ui/radio-group'
import { RadioItem } from '@/components/ui/radio-item'

export default function Frame2() {
  return (
    <div data-layout-mode="absolute" style={{ width: '100%', height: '100%', position: 'relative' }}>
      {/* pv-editable-zone-start:myx0mv */}
      {/* pv-block-start:0f2ftm */}
      <Button data-pv-block="0f2ftm" label="Button" variant="solid" color="primary" size="md"   data-pv-sketchpad-el="0f2ftm" style={{ position: 'absolute', left: 460, top: 447 }}/>
      {/* pv-block-end:0f2ftm */}
      
      {/* pv-block-start:0yzpp0 */}
      <Card data-pv-block="0yzpp0" data-pv-sketchpad-el="0yzpp0" variant="bordered" shadow="none" style={{ position: 'absolute', left: 92, top: 93 }}>
        {/* pv-editable-zone-start:6hs9d2 */}
        {/* pv-block-start:rsuoys */}
      <Button data-pv-block="rsuoys" label="Button" variant="solid" color="primary" size="md" />
      {/* pv-block-end:rsuoys */}

        {/* pv-block-start:f7zclr */}
      <Card data-pv-block="f7zclr" variant="bordered" shadow="none" >
        {/* pv-editable-zone-start:05x4yx */}
        {/* pv-block-start:2s7e96 */}
        <RadioGroup data-pv-block="2s7e96"  orientation="vertical" value="opt1" >
          {/* pv-editable-zone-start:5a5fn8 */}
            {/* pv-block-start:hqxgxy */}
            <RadioItem data-pv-block="hqxgxy" value="opt1" primaryText="Option One" secondaryText="Description for option one" />
            {/* pv-block-end:hqxgxy */}
            {/* pv-block-start:8xo1nl */}
            <RadioItem data-pv-block="8xo1nl" value="opt2" primaryText="Option Two" secondaryText="Description for option two" />
            {/* pv-block-end:8xo1nl */}
            {/* pv-block-start:fo0g2i */}
            <RadioItem data-pv-block="fo0g2i" value="opt3" primaryText="Option Three" secondaryText="Third option" />
            {/* pv-block-end:fo0g2i */}
          {/* pv-editable-zone-end:5a5fn8 */}
        </RadioGroup>
        {/* pv-block-end:2s7e96 */}
        {/* pv-editable-zone-end:05x4yx */}
      </Card>
      {/* pv-block-end:f7zclr */}

        {/* pv-block-start:m8wdv6 */}
      <DialogTrigger data-pv-block="m8wdv6" >
        {/* pv-editable-zone-start:npkiwa */}
          {/* pv-block-start:4qnqh2 */}
          <Button data-pv-block="4qnqh2" label="Open Dialog" variant="solid" color="primary" size="md" />
          {/* pv-block-end:4qnqh2 */}
          {/* pv-block-start:xfhlu6 */}
          <DialogOverlay data-pv-block="xfhlu6">
            <DialogWindow size="md">
              {/* pv-editable-zone-start:6n860e */}
              {/* pv-block-start:vlfvnx */}
              <h2 data-pv-block="vlfvnx" className="text-xl font-semibold text-foreground-default mb-2">Dialog Title</h2>
              {/* pv-block-end:vlfvnx */}
              {/* pv-block-start:tt3bxz */}
              <p data-pv-block="tt3bxz" className="text-foreground-secondary mb-6">This is the dialog content. Click the button below or press Escape to close.</p>
              {/* pv-block-end:tt3bxz */}
              {/* pv-editable-zone-end:6n860e */}
            </DialogWindow>
          </DialogOverlay>
          {/* pv-block-end:xfhlu6 */}
        {/* pv-editable-zone-end:npkiwa */}
      </DialogTrigger>
      {/* pv-block-end:m8wdv6 */}
        {/* pv-editable-zone-end:6hs9d2 */}
      </Card>
      {/* pv-block-end:0yzpp0 */}
      {/* pv-editable-zone-end:myx0mv */}
    </div>
  );
}
