// Auto-generated by Protovibe Sketchpad
import { Button } from '@/components/ui/button';
import { Rectangle } from '@/components/ui/sketchpad-rectangle';
import { Card } from '@/components/ui/card';
import { Checkbox } from '@/components/ui/checkbox';

export default function Frame3() {
  return (
    <div data-layout-mode="absolute" style={{ width: '100%', height: '100%', position: 'relative' }}>
      {/* pv-editable-zone-start:b399cq */}
      {/* pv-block-start:h8t4x5 */}
      <Rectangle data-pv-block="h8t4x5" data-pv-sketchpad-el="h8t4x5" className="w-[200px] h-[200px]" style={{ position: 'absolute', left: 89, top: 30 }}>
        {/* pv-editable-zone-start:duvsah */}
        {/* pv-block-start:p0gfxe */}
        <div data-pv-block="p0gfxe" className="flex flex-col gap-2" data-pv-sketchpad-el="p0gfxe" style={{ position: 'absolute', left: 17, top: 18 }}>
          {/* pv-editable-zone-start:kwz2ry */}
          {/* pv-editable-zone-end:kwz2ry */}
        </div>
        {/* pv-block-end:p0gfxe */}

        {/* pv-block-start:x709xk */}
      <div data-pv-block="x709xk" className="flex flex-col gap-2" data-pv-sketchpad-el="x709xk" style={{ position: 'absolute', left: 29, top: 29 }}>
        {/* pv-editable-zone-start:qubfhb */}
        {/* pv-block-start:1jt7gv */}
        <div data-pv-block="1jt7gv" className="flex flex-col gap-10" >
        {/* pv-editable-zone-start:c2rycc */}
        {/* pv-block-start:m4k58z */}
        <Button data-pv-block="m4k58z" label="Button" variant="solid" color="primary" size="md"  />
        {/* pv-block-end:m4k58z */}
        {/* pv-editable-zone-end:c2rycc */}
        </div>
        {/* pv-block-end:1jt7gv */}
        {/* pv-block-start:ccoejs */}
        <div data-pv-block="ccoejs" className="flex flex-col gap-10" >
        {/* pv-editable-zone-start:c2rycc */}
        {/* pv-block-start:xapeet */}
        <Button data-pv-block="xapeet" label="Button" variant="solid" color="primary" size="md"  />
        {/* pv-block-end:xapeet */}
        {/* pv-editable-zone-end:c2rycc */}
        </div>
        {/* pv-block-end:ccoejs */}
        {/* pv-editable-zone-end:qubfhb */}
      </div>
      {/* pv-block-end:x709xk */}
        {/* pv-editable-zone-end:duvsah */}
      </Rectangle>
      {/* pv-block-end:h8t4x5 */}

      {/* pv-block-start:o5jjlj */}
      <Card data-pv-block="o5jjlj" data-pv-sketchpad-el="o5jjlj" variant="bordered" shadow="none" border="default" style={{ position: 'absolute', width: 365, left: 221, top: 310 }}>
        {/* pv-editable-zone-start:taxyss */}
        {/* pv-block-start:85og1m */}
        <div data-pv-block="85og1m" className="flex flex-col gap-2">
          {/* pv-editable-zone-start:bla8ry */}
          {/* pv-block-start:7mnwm3 */}
          <Button data-pv-block="7mnwm3" label="Button" variant="solid" color="primary" size="md" />
          {/* pv-block-end:7mnwm3 */}
          {/* pv-block-start:scirda */}
          <Button data-pv-block="scirda" label="Button" variant="solid" color="primary" size="md" />
          {/* pv-block-end:scirda */}
          {/* pv-editable-zone-end:bla8ry */}
        </div>
        {/* pv-block-end:85og1m */}

        {/* pv-block-start:aeiiwc */}
        <div data-pv-block="aeiiwc" className="flex gap-2 flex-row" >
          {/* pv-editable-zone-start:x6aovb */}
          {/* pv-editable-zone-end:x6aovb */}
        </div>
        {/* pv-block-end:aeiiwc */}

          {/* pv-block-start:7yz2s2 */}
          <div className="flex flex-col min-h-4" data-pv-block="7yz2s2">
            {/* pv-editable-zone-start:inside-7yz2s2 */}
            {/* pv-editable-zone-end:inside-7yz2s2 */}
          </div>
          {/* pv-block-end:7yz2s2 */}

        {/* pv-block-start:n0rpju */}
        <div data-pv-block="n0rpju" className="flex flex-col gap-4">
          {/* pv-editable-zone-start:9rdg7j */}
          {/* pv-block-start:lt1ecf */}
          <Checkbox data-pv-block="lt1ecf" primaryText="Accept terms"  />
          {/* pv-block-end:lt1ecf */}
          {/* pv-block-start:lxy2ai */}
          <Checkbox data-pv-block="lxy2ai" primaryText="Accept terms"  />
          {/* pv-block-end:lxy2ai */}
          {/* pv-editable-zone-end:9rdg7j */}
        </div>
        {/* pv-block-end:n0rpju */}


        {/* pv-editable-zone-end:taxyss */}
      </Card>
      {/* pv-block-end:o5jjlj */}
      {/* pv-editable-zone-end:b399cq */}
    </div>
  );
}
