import { Button } from '@/components/ui/button'
import { Card } from '@/components/ui/card'
import { Icon } from '@/components/ui/icon'
import { TextBlock } from '@/components/ui/text-block'
import { Badge } from '@/components/ui/badge'
import { Table } from '@/components/ui/table';
import { TableRowHeading } from '@/components/ui/table-row-heading';
import { TableRowContent } from '@/components/ui/table-row-content';
import { TableCellHeading } from '@/components/ui/table-cell-heading';
import { TableCellContent } from '@/components/ui/table-cell-content';
import { Avatar } from '@/components/ui/avatar'
import { Container } from '@/components/ui/container'
import { SuperLabel } from '@/components/ui/super-label';
// Auto-generated by Protovibe Sketchpad

export default function Frame2() {
  return (
    <div data-layout-mode="absolute" style={{ width: '100%', height: '100%', position: 'relative' }}>
      {/* pv-editable-zone-start:hxwp0f */}
      {/* pv-block-start:qqn3dn */}
            <Card data-pv-block="qqn3dn" variant="bordered" shadow="sm" className="bg-background-default" data-pv-sketchpad-el="qqn3dn" style={{ position: 'absolute', width: 206, left: 231, top: 59 }}>
              {/* pv-editable-zone-start:c8d9e1 */}
                {/* pv-block-start:3lfgei */}
                <div data-pv-block="3lfgei" className="flex items-center gap-3 mb-2 text-foreground-secondary">
                  {/* pv-editable-zone-start:i5j6k7 */}
                    {/* pv-block-start:h63ogy */}
                    <Icon data-pv-block="h63ogy" name="Users" size="sm" />
                    {/* pv-block-end:h63ogy */}
                    {/* pv-block-start:smw7ma */}
                    <TextBlock data-pv-block="smw7ma" typography="small" className="font-semibold uppercase tracking-wider">Total Headcount</TextBlock>
                    {/* pv-block-end:smw7ma */}
                  {/* pv-editable-zone-end:i5j6k7 */}
                </div>
                {/* pv-block-end:3lfgei */}

              {/* pv-block-start:rz5kvr */}
                <TextBlock data-pv-block="rz5kvr" typography="heading-xxl" className="mb-2" >142</TextBlock>
                {/* pv-block-end:rz5kvr */}

              {/* pv-block-start:forrs6 */}
                <Badge data-pv-block="forrs6" label="+12% vs last year" color="success" prefixIcon="TrendingUp" />
                {/* pv-block-end:forrs6 */}

              {/* pv-block-start:maw5ms */}
      <Button data-pv-block="maw5ms" label="Button" variant="solid" color="primary" size="md"  />
      {/* pv-block-end:maw5ms */}
              {/* pv-editable-zone-end:c8d9e1 */}
            </Card>
            {/* pv-block-end:qqn3dn */}
      
      {/* pv-block-start:4ka2gh */}
      <Table data-pv-block="4ka2gh" data-pv-sketchpad-el="4ka2gh"  style={{ position: 'absolute', width: 669, left: 58, top: 329 }}>
        {/* pv-editable-zone-start:rqlqwm */}
          {/* pv-block-start:6chu7x */}
          <thead data-pv-block="6chu7x">
            <TableRowHeading>
              {/* pv-editable-zone-start:gaptp7 */}
                {/* pv-block-start:8srlnn */}
                <TableCellHeading data-pv-block="8srlnn" label="Name" />
                {/* pv-block-end:8srlnn */}
                {/* pv-block-start:btljrn */}
                <TableCellHeading data-pv-block="btljrn" label="Status" />
                {/* pv-block-end:btljrn */}
                {/* pv-block-start:dvq1v7 */}
                <TableCellHeading data-pv-block="dvq1v7" suffixIcon="SortAsc" label="Date" />
                {/* pv-block-end:dvq1v7 */}
              {/* pv-editable-zone-end:gaptp7 */}
            </TableRowHeading>
          </thead>
          {/* pv-block-end:6chu7x */}
          {/* pv-block-start:tktxwe */}
          <tbody data-pv-block="tktxwe">
            {/* pv-editable-zone-start:hbj2zp */}
              {/* pv-block-start:vjudeo */}
              <TableRowContent data-pv-block="vjudeo">
                {/* pv-editable-zone-start:wzhfct */}
                  {/* pv-block-start:h032eq */}
                  <TableCellContent className="flex flex-row items-center gap-4" data-pv-block="h032eq">
                    {/* pv-editable-zone-start:lxa6iw */}
                      {/* pv-block-start:byzu9h */}
                      <Container className="flex-row items-center gap-4" data-pv-block="byzu9h">
                        {/* pv-editable-zone-start:ixm25n */}
                        {/* pv-block-start:6welk8 */}
                      <Avatar data-pv-block="6welk8" initials="AB" size="md" bgColor="default" imageSrc="https://i.pravatar.cc/60" />
                      {/* pv-block-end:6welk8 */}

                          {/* pv-block-start:rq8nkh */}
                          <Container data-pv-block="rq8nkh">
                            {/* pv-editable-zone-start:h6l7bn */}
                            {/* pv-block-start:aoodxe */}
                      <TextBlock typography="heading-sm" data-pv-block="aoodxe" label="Value" />
                      {/* pv-block-end:aoodxe */}

                            {/* pv-block-start:8pbtzt */}
                      <TextBlock data-pv-block="8pbtzt" label="Value" />
                      {/* pv-block-end:8pbtzt */}
                            {/* pv-editable-zone-end:h6l7bn */}
                          </Container>
                          {/* pv-block-end:rq8nkh */}
                        {/* pv-editable-zone-end:ixm25n */}
                      </Container>
                      {/* pv-block-end:byzu9h */}
                    {/* pv-editable-zone-end:lxa6iw */}
                  </TableCellContent>
                  {/* pv-block-end:h032eq */}
                  {/* pv-block-start:mjb37s */}
                  <TableCellContent data-pv-block="mjb37s">
                    {/* pv-editable-zone-start:n34m90 */}
                      {/* pv-block-start:dafxy7 */}
                      <TextBlock data-pv-block="dafxy7" label="Active" />
                      {/* pv-block-end:dafxy7 */}
                    {/* pv-editable-zone-end:n34m90 */}
                  </TableCellContent>
                  {/* pv-block-end:mjb37s */}
                  {/* pv-block-start:m4n2fn */}
                  <TableCellContent data-pv-block="m4n2fn">
                    {/* pv-editable-zone-start:3e1eth */}
                      {/* pv-block-start:xbyjfh */}
                      <TextBlock data-pv-block="xbyjfh" label="Jan 1, 2024" />
                      {/* pv-block-end:xbyjfh */}
                    {/* pv-editable-zone-end:3e1eth */}
                  </TableCellContent>
                  {/* pv-block-end:m4n2fn */}
                {/* pv-editable-zone-end:wzhfct */}
              </TableRowContent>
              {/* pv-block-end:vjudeo */}
              {/* pv-block-start:t6313w */}
              <TableRowContent data-pv-block="t6313w">
                {/* pv-editable-zone-start:hju8xg */}
                  {/* pv-block-start:moxhpd */}
                  <TableCellContent data-pv-block="moxhpd">
                    {/* pv-editable-zone-start:pgtbp4 */}
                      {/* pv-block-start:mbjncd */}
                      <TextBlock data-pv-block="mbjncd" label="Value 2" />
                      {/* pv-block-end:mbjncd */}
                    {/* pv-editable-zone-end:pgtbp4 */}
                  </TableCellContent>
                  {/* pv-block-end:moxhpd */}
                  {/* pv-block-start:dak822 */}
                  <TableCellContent data-pv-block="dak822">
                    {/* pv-editable-zone-start:5u83gt */}
                      {/* pv-block-start:cl9b0r */}
                      <TextBlock data-pv-block="cl9b0r" label="Inactive" />
                      {/* pv-block-end:cl9b0r */}
                    {/* pv-editable-zone-end:5u83gt */}
                  </TableCellContent>
                  {/* pv-block-end:dak822 */}
                  {/* pv-block-start:csy11a */}
                  <TableCellContent data-pv-block="csy11a">
                    {/* pv-editable-zone-start:v9y631 */}
                      {/* pv-block-start:b0amxl */}
                      <TextBlock data-pv-block="b0amxl" label="Jan 2, 2024" />
                      {/* pv-block-end:b0amxl */}
                    {/* pv-editable-zone-end:v9y631 */}
                  </TableCellContent>
                  {/* pv-block-end:csy11a */}
                {/* pv-editable-zone-end:hju8xg */}
              </TableRowContent>
              {/* pv-block-end:t6313w */}
              {/* pv-block-start:8t4uwo */}
              <TableRowContent data-pv-block="8t4uwo">
                {/* pv-editable-zone-start:wkfhsc */}
                  {/* pv-block-start:dqh92y */}
                  <TableCellContent data-pv-block="dqh92y">
                    {/* pv-editable-zone-start:x7dohk */}
                      {/* pv-block-start:vaa0dc */}
                      <TextBlock data-pv-block="vaa0dc" label="Value 3" />
                      {/* pv-block-end:vaa0dc */}
                    {/* pv-editable-zone-end:x7dohk */}
                  </TableCellContent>
                  {/* pv-block-end:dqh92y */}
                  {/* pv-block-start:japsyx */}
                  <TableCellContent data-pv-block="japsyx">
                    {/* pv-editable-zone-start:p7ayrz */}
                      {/* pv-block-start:idhgk5 */}
                      <TextBlock data-pv-block="idhgk5" label="Active" />
                      {/* pv-block-end:idhgk5 */}
                    {/* pv-editable-zone-end:p7ayrz */}
                  </TableCellContent>
                  {/* pv-block-end:japsyx */}
                  {/* pv-block-start:ed9tpo */}
                  <TableCellContent data-pv-block="ed9tpo">
                    {/* pv-editable-zone-start:wtr5y2 */}
                      {/* pv-block-start:xh7i9l */}
                      <TextBlock data-pv-block="xh7i9l" label="Jan 3, 2024" />
                      {/* pv-block-end:xh7i9l */}
                    {/* pv-editable-zone-end:wtr5y2 */}
                  </TableCellContent>
                  {/* pv-block-end:ed9tpo */}
                {/* pv-editable-zone-end:wkfhsc */}
              </TableRowContent>
              {/* pv-block-end:8t4uwo */}
            {/* pv-editable-zone-end:hbj2zp */}
          </tbody>
          {/* pv-block-end:tktxwe */}
        {/* pv-editable-zone-end:rqlqwm */}
      </Table>
      {/* pv-block-end:4ka2gh */}

      {/* pv-block-start:aac2v5 */}
            <Card data-pv-block="aac2v5" variant="bordered" shadow="sm" className="bg-background-default" data-pv-sketchpad-el="aac2v5" style={{ position: 'absolute', left: 485, top: 65, width: 206 }}>
              {/* pv-editable-zone-start:c8d9e1 */}
                {/* pv-block-start:pgsa7t */}
                <div data-pv-block="pgsa7t" className="flex items-center gap-3 mb-2 text-foreground-secondary">
                  {/* pv-editable-zone-start:i5j6k7 */}
                    {/* pv-block-start:tjb27b */}
                    <TextBlock data-pv-block="tjb27b" typography="small" className="font-semibold uppercase tracking-wider">Total Headcount</TextBlock>
                    {/* pv-block-end:tjb27b */}
                  {/* pv-editable-zone-end:i5j6k7 */}
                </div>
                {/* pv-block-end:pgsa7t */}
                {/* pv-block-start:zqhd2f */}
                <TextBlock data-pv-block="zqhd2f" typography="heading-xxl" className="mb-2">142</TextBlock>
                {/* pv-block-end:zqhd2f */}

              {/* pv-block-start:x4hugl */}
                <Badge data-pv-block="x4hugl" label="+12% vs last year" color="success" prefixIcon="TrendingUp" />
                {/* pv-block-end:x4hugl */}
              {/* pv-editable-zone-end:c8d9e1 */}
            </Card>
            {/* pv-block-end:aac2v5 */}
      
      {/* pv-block-start:jwfcna */}
      <SuperLabel heading="Test" data-pv-block="jwfcna" data-pv-sketchpad-el="jwfcna" primaryText="Label" style={{ position: 'absolute', left: 90, top: 77 }} />
      {/* pv-block-end:jwfcna */}
      {/* pv-editable-zone-end:hxwp0f */}
    </div>
  );
}
