import { Button } from '@/components/ui/button'
import { Card } from '@/components/ui/card'
import { Icon } from '@/components/ui/icon'
import { TextBlock } from '@/components/ui/text-block'
import { Badge } from '@/components/ui/badge'
import { Table } from '@/components/ui/table';
import { TableRowHeading } from '@/components/ui/table-row-heading';
import { TableRowContent } from '@/components/ui/table-row-content';
import { TableCellHeading } from '@/components/ui/table-cell-heading';
import { TableCellContent } from '@/components/ui/table-cell-content';
import { Avatar } from '@/components/ui/avatar'
import { Container } from '@/components/ui/container'
import { SuperLabel } from '@/components/ui/super-label';
import { RadioGroup } from '@/components/ui/radio-group'
import { RadioItem } from '@/components/ui/radio-item'
import { TableBody } from '@/components/ui/table-body';
import { InfoBoxBanner } from '@/components/ui/info-box-banner';
import { Tabs } from '@/components/ui/tabs';
import { TabItem } from '@/components/ui/tab-item';
import { Rectangle } from '@/components/ui/sketchpad-rectangle';
// Auto-generated by Protovibe Sketchpad

export default function Frame2() {
  return (
    <div data-layout-mode="absolute" style={{ width: '100%', height: '100%', position: 'relative' }}>
      {/* pv-editable-zone-start:hxwp0f */}
      {/* pv-block-start:5ybvj3 */}
      <Rectangle data-pv-block="5ybvj3" data-pv-sketchpad-el="5ybvj3"  style={{ position: 'absolute', height: 79, left: 37, top: 84 }}>
        {/* pv-editable-zone-start:6xj4g5 */}
        {/* pv-editable-zone-end:6xj4g5 */}
      </Rectangle>
      {/* pv-block-end:5ybvj3 */}

      {/* pv-block-start:16xx1w */}
      <Rectangle data-pv-block="16xx1w" data-pv-sketchpad-el="16xx1w"  style={{ position: 'absolute', left: 50, top: 171 }}>
        {/* pv-editable-zone-start:znd5i5 */}
        {/* pv-editable-zone-end:znd5i5 */}
      </Rectangle>
      {/* pv-block-end:16xx1w */}

      {/* pv-block-start:n2qffv */}
      <Rectangle data-pv-block="n2qffv" data-pv-sketchpad-el="n2qffv"  style={{ position: 'absolute', height: 129, width: 460, left: -1083, top: 805 }}>
        {/* pv-editable-zone-start:no6vhn */}
        {/* pv-editable-zone-end:no6vhn */}
      </Rectangle>
      {/* pv-block-end:n2qffv */}
      
      {/* pv-block-start:65mrdq */}
      <Rectangle data-pv-block="65mrdq" data-pv-sketchpad-el="65mrdq"  style={{ position: 'absolute', left: 94, top: 30 }}>
        {/* pv-editable-zone-start:s0ibce */}
        {/* pv-editable-zone-end:s0ibce */}
      </Rectangle>
      {/* pv-block-end:65mrdq */}
      
      {/* pv-block-start:3blium */}
      <Rectangle data-pv-block="3blium" data-pv-sketchpad-el="3blium"  style={{ position: 'absolute', height: 219, width: 513, left: 192, top: 102 }}>
        {/* pv-editable-zone-start:bddck1 */}
        {/* pv-block-start:izab1l */}
        <div data-pv-block="izab1l" className="flex flex-col gap-4" data-pv-sketchpad-el="izab1l" style={{ position: 'absolute', width: 416, left: 36, top: 61 }}>
          {/* pv-editable-zone-start:aj26iu */}
          {/* pv-block-start:nryq47 */}
          <InfoBoxBanner data-pv-block="nryq47" icon="Info" heading="Heads up" secondaryText="Something needs your attention." color="info" showCloseButton={true} >
          {/* pv-editable-zone-start:17kg7f */}
          {/* pv-editable-zone-end:17kg7f */}
          </InfoBoxBanner>
          {/* pv-block-end:nryq47 */}
          {/* pv-block-start:szk8tq */}
          <SuperLabel heading="Dupa" data-pv-block="szk8tq" primaryText="Label" style={{ width: 179 }} />
          {/* pv-block-end:szk8tq */}
          {/* pv-editable-zone-end:aj26iu */}
        </div>
        {/* pv-block-end:izab1l */}

        {/* pv-block-start:tenj4v */}
      <TextBlock data-pv-block="tenj4v" data-pv-sketchpad-el="tenj4v" typography="heading-md" style={{ position: 'absolute', left: 33, top: 21 }}>
        Text block
      </TextBlock>
      {/* pv-block-end:tenj4v */}
        {/* pv-editable-zone-end:bddck1 */}
      </Rectangle>
      {/* pv-block-end:3blium */}

      {/* pv-block-start:tha28r */}
      <Rectangle data-pv-block="tha28r" data-pv-sketchpad-el="tha28r" className="w-[200px] h-[200px]" style={{ position: 'absolute', width: 532, height: 235, left: -903, top: 651 }}>
        {/* pv-editable-zone-start:ncq2df */}
        {/* pv-block-start:q38jxq */}
          <Card data-pv-block="q38jxq" variant="bordered" shadow="none" border="default" style={{ position: 'absolute', left: 71, top: 56, width: 365 }} data-pv-sketchpad-el="q38jxq">
          {/* pv-editable-zone-start:taxyss */}
          {/* pv-block-start:uzl0f1 */}
          <div data-pv-block="uzl0f1" className="flex gap-2 flex-row" >
          {/* pv-editable-zone-start:x6aovb */}
          {/* pv-editable-zone-end:x6aovb */}
          </div>
          {/* pv-block-end:uzl0f1 */}
          
          {/* pv-block-start:p6yq3q */}
          <div className="flex flex-col min-h-4" data-pv-block="p6yq3q">
          {/* pv-editable-zone-start:inside-p6yq3q */}
          {/* pv-editable-zone-end:inside-p6yq3q */}
          </div>
          {/* pv-block-end:p6yq3q */}
          {/* pv-editable-zone-end:taxyss */}
          </Card>
          {/* pv-block-end:q38jxq */}
        {/* pv-editable-zone-end:ncq2df */}
      </Rectangle>
      {/* pv-block-end:tha28r */}
      {/* pv-editable-zone-end:hxwp0f */}
    </div>
  );
}
