// Auto-generated by Protovibe Sketchpad
import { Container } from '@/components/ui/container';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { SuperLabel } from '@/components/ui/super-label';
import { Rectangle } from '@/components/ui/sketchpad-rectangle'
import { Checkbox } from '@/components/ui/checkbox'
import { Avatar } from '@/components/ui/avatar'

export default function Frame4() {
  return (
    <div data-layout-mode="absolute" style={{ width: '100%', height: '100%', position: 'relative' }}>
      {/* pv-editable-zone-start:6g9nd2 */}
      {/* pv-block-start:qndewo */}
      <Container data-pv-block="qndewo" data-pv-sketchpad-el="qndewo"  style={{ position: 'absolute', left: 140, top: 126 }}>
        {/* pv-editable-zone-start:z2yarx */}
        {/* pv-editable-zone-end:z2yarx */}
      </Container>
      {/* pv-block-end:qndewo */}
      
      {/* pv-block-start:lv8rzw */}
      <div data-pv-block="lv8rzw" className="flex flex-col gap-2" data-pv-sketchpad-el="lv8rzw" style={{ position: 'absolute', width: 374, left: 111, top: 97 }}>
        {/* pv-editable-zone-start:i7bwgp */}
        {/* pv-block-start:yzabkm */}
      <SuperLabel secondaryText="Uważaj co wpisujesz!" heading="Wybierz co tam chcesz!" data-pv-block="yzabkm" primaryText=""  />
      {/* pv-block-end:yzabkm */}
        {/* pv-block-start:ie8zg7 */}
        <Input data-pv-block="ie8zg7" placeholder="Enter text..."  />
        {/* pv-block-end:ie8zg7 */}

        {/* pv-block-start:hnanzk */}
        <Button data-pv-block="hnanzk" label="Button" variant="solid" color="primary" size="md" />
        {/* pv-block-end:hnanzk */}
        {/* pv-editable-zone-end:i7bwgp */}
      </div>
      {/* pv-block-end:lv8rzw */}
      
      {/* pv-block-start:1a41sf */}
      <div data-pv-block="1a41sf" className="flex flex-col gap-2" data-pv-sketchpad-el="1a41sf" style={{ position: 'absolute', left: 92, top: 299 }}>
        {/* pv-editable-zone-start:e0x6wo */}
        {/* pv-block-start:8uh2vh */}
        <Avatar data-pv-block="8uh2vh" initials="AB" size="md" bgColor="default" imageSrc="https://i.pravatar.cc/60"  />
        {/* pv-block-end:8uh2vh */}
        {/* pv-block-start:fn5ugj */}
        <Avatar data-pv-block="fn5ugj" initials="AB" size="md" bgColor="default" imageSrc="https://i.pravatar.cc/60"  />
        {/* pv-block-end:fn5ugj */}
        {/* pv-editable-zone-end:e0x6wo */}
      </div>
      {/* pv-block-end:1a41sf */}
      {/* pv-editable-zone-end:6g9nd2 */}
    </div>
  );
}
