// Auto-generated by Protovibe Sketchpad
import { Rectangle } from '@/components/ui/sketchpad-rectangle';
import { TextBlock } from '@/components/ui/text-block'
import { Card } from '@/components/ui/card'
import { Icon } from '@/components/ui/icon'
import { SuperLabel } from '@/components/ui/super-label'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Tabs } from '@/components/ui/tabs'
import { TabItem } from '@/components/ui/tab-item'

export default function Frame3() {
  return (
    <div data-layout-mode="absolute" style={{ width: '100%', height: '100%', position: 'relative' }}>
      {/* pv-editable-zone-start:jzcc0h */}
      {/* pv-block-start:ctjldf */}
      <Rectangle data-pv-block="ctjldf" data-pv-sketchpad-el="ctjldf" className="w-[200px] h-[200px]" style={{ position: 'absolute', height: 248, width: 540, left: 97, top: 274 }}>
        {/* pv-editable-zone-start:ftt61c */}
        {/* pv-block-start:bqqcca */}
      <Rectangle data-pv-block="bqqcca" data-pv-sketchpad-el="bqqcca"  style={{ position: 'absolute', left: 25, top: 15, width: 322, height: 156 }}>
        {/* pv-editable-zone-start:1n9ihg */}
        {/* pv-block-start:lpu08x */}
          <div data-pv-block="lpu08x" className="flex flex-col gap-10"  data-pv-sketchpad-el="lpu08x" style={{ position: 'absolute', left: 28, top: 23 }}>
          {/* pv-editable-zone-start:c2rycc */}
          {/* pv-block-start:8ict78 */}
          <Button data-pv-block="8ict78" label="Button" variant="solid" color="primary" size="md"  />
          {/* pv-block-end:8ict78 */}
          {/* pv-editable-zone-end:c2rycc */}
          </div>
          {/* pv-block-end:lpu08x */}
        {/* pv-editable-zone-end:1n9ihg */}
      </Rectangle>
      {/* pv-block-end:bqqcca */}
        {/* pv-editable-zone-end:ftt61c */}
      </Rectangle>
      {/* pv-block-end:ctjldf */}

      {/* pv-block-start:0bjh21 */}
        <Rectangle data-pv-block="0bjh21" className="w-[200px] h-[200px]" data-pv-sketchpad-el="0bjh21" style={{ position: 'absolute', left: 460, top: 32 }}>
          {/* pv-editable-zone-start:fn1xxk */}
          {/* pv-block-start:8anhjk */}
                    <TextBlock data-pv-block="8anhjk" typography="heading-md" className="uppercase tracking-wider" data-pv-sketchpad-el="8anhjk" style={{ position: 'absolute', left: 25, top: 25 }}>Total Headcount</TextBlock>
                    {/* pv-block-end:8anhjk */}
          {/* pv-editable-zone-end:fn1xxk */}
        </Rectangle>
        {/* pv-block-end:0bjh21 */}
      
      {/* pv-block-start:zwwlih */}
      <Rectangle data-pv-block="zwwlih" data-pv-sketchpad-el="zwwlih"  style={{ position: 'absolute', left: 38, top: 44, height: 171, width: 262 }}>
        {/* pv-editable-zone-start:x4yctj */}
        {/* pv-block-start:8rlnau */}
      <Tabs data-pv-block="8rlnau" data-pv-sketchpad-el="8rlnau" value="tab1" style={{ position: 'absolute', left: 13, top: 27 }}>
        {/* pv-editable-zone-start:47jhz6 */}
          {/* pv-block-start:38soac */}
          <TabItem data-pv-block="38soac" label="Tab 1" value="tab1" />
          {/* pv-block-end:38soac */}
          {/* pv-block-start:urseod */}
          <TabItem data-pv-block="urseod" label="Tab 2" value="tab2" />
          {/* pv-block-end:urseod */}
          {/* pv-block-start:ns7jtp */}
          <TabItem data-pv-block="ns7jtp" label="Tab 3" value="tab3" />
          {/* pv-block-end:ns7jtp */}
        {/* pv-editable-zone-end:47jhz6 */}
      </Tabs>
      {/* pv-block-end:8rlnau */}
        {/* pv-editable-zone-end:x4yctj */}
      </Rectangle>
      {/* pv-block-end:zwwlih */}
      {/* pv-editable-zone-end:jzcc0h */}
    </div>
  );
}
