// Auto-generated by Protovibe Sketchpad
import { RadioGroup } from '@/components/ui/radio-group';
import { RadioItem } from '@/components/ui/radio-item';
import { Card } from '@/components/ui/card';

export default function Frame1() {
  return (
    <div data-layout-mode="absolute" style={{ width: '100%', height: '100%', position: 'relative' }}>
      {/* pv-editable-zone-start:t362fh */}
      
      {/* pv-block-start:umz5pu */}
      <RadioGroup data-pv-block="umz5pu" data-pv-sketchpad-el="umz5pu" orientation="vertical" value="opt1" style={{ position: 'absolute', left: 464, top: 327 }}>
        {/* pv-editable-zone-start:mvy8s3 */}
          {/* pv-block-start:beqo8v */}
          <RadioItem data-pv-block="beqo8v" value="opt1" primaryText="Option One" secondaryText="Description for option one" />
          {/* pv-block-end:beqo8v */}
          {/* pv-block-start:h2oia9 */}
          <RadioItem data-pv-block="h2oia9" value="opt2" primaryText="Option Two" secondaryText="Description for option two" />
          {/* pv-block-end:h2oia9 */}
          {/* pv-block-start:7cqx7l */}
          <RadioItem data-pv-block="7cqx7l" value="opt3" primaryText="Option Three" secondaryText="Third option" />
          {/* pv-block-end:7cqx7l */}
        {/* pv-editable-zone-end:mvy8s3 */}
      </RadioGroup>
      {/* pv-block-end:umz5pu */}
      
      {/* pv-block-start:f118lk */}
      <Card data-pv-block="f118lk" data-pv-sketchpad-el="f118lk" variant="bordered" shadow="none" style={{ position: 'absolute', left: 202, top: 242 }}>
        {/* pv-editable-zone-start:t1i2jj */}
        {/* pv-editable-zone-end:t1i2jj */}
      </Card>
      {/* pv-block-end:f118lk */}
      {/* pv-editable-zone-end:t362fh */}
    </div>
  );
}
