// Auto-generated by Protovibe Sketchpad
import { Rectangle } from '@/components/ui/sketchpad-rectangle';
import { Button } from '@/components/ui/button';
import { TextBlock } from '@/components/ui/text-block';

export default function Frame6() {
  return (
    <div data-layout-mode="absolute" style={{ width: '100%', height: '100%', position: 'relative' }}>
      {/* pv-editable-zone-start:kqlqv4 */}
      {/* pv-block-start:aoyklm */}
      <Rectangle data-pv-block="aoyklm" data-pv-sketchpad-el="aoyklm" className="w-[200px] h-[200px] bg-background-secondary border-transparent rounded-none" style={{ position: 'absolute', height: 53, width: 1433, left: -1, top: 1 }}>
        {/* pv-editable-zone-start:apj9nv */}
        {/* pv-block-start:7zz7le */}
      <Button data-pv-block="7zz7le" data-pv-sketchpad-el="7zz7le" label="Button" variant="solid" color="primary" size="md" style={{ position: 'absolute', left: 1352, top: 5 }} />
      {/* pv-block-end:7zz7le */}

        {/* pv-block-start:231mu2 */}
      <TextBlock data-pv-block="231mu2" data-pv-sketchpad-el="231mu2" typography="heading-md" style={{ position: 'absolute', left: 13, top: 14 }}>
        Witamix!
      </TextBlock>
      {/* pv-block-end:231mu2 */}
        {/* pv-editable-zone-end:apj9nv */}
      </Rectangle>
      {/* pv-block-end:aoyklm */}
      {/* pv-editable-zone-end:kqlqv4 */}
    </div>
  );
}
