import { Button } from '@/components/ui/button'
import { Card } from '@/components/ui/card'
import { Icon } from '@/components/ui/icon'
import { TextBlock } from '@/components/ui/text-block'
import { Badge } from '@/components/ui/badge'
import { Table } from '@/components/ui/table';
import { TableRowHeading } from '@/components/ui/table-row-heading';
import { TableRowContent } from '@/components/ui/table-row-content';
import { TableCellHeading } from '@/components/ui/table-cell-heading';
import { TableCellContent } from '@/components/ui/table-cell-content';
import { Avatar } from '@/components/ui/avatar'
import { Container } from '@/components/ui/container'
import { SuperLabel } from '@/components/ui/super-label';
import { RadioGroup } from '@/components/ui/radio-group'
import { RadioItem } from '@/components/ui/radio-item'
import { TableBody } from '@/components/ui/table-body';
import { InfoBoxBanner } from '@/components/ui/info-box-banner';
import { Tabs } from '@/components/ui/tabs';
import { TabItem } from '@/components/ui/tab-item';
import { Rectangle } from '@/components/ui/sketchpad-rectangle';
// Auto-generated by Protovibe Sketchpad

export default function Frame2() {
  return (
    <div data-layout-mode="absolute" style={{ width: '100%', height: '100%', position: 'relative' }}>
      {/* pv-editable-zone-start:hxwp0f */}
      {/* pv-block-start:5ybvj3 */}
      <Rectangle data-pv-block="5ybvj3" data-pv-sketchpad-el="5ybvj3"  style={{ position: 'absolute', height: 79, left: 37, top: 84 }}>
        {/* pv-editable-zone-start:6xj4g5 */}
        {/* pv-editable-zone-end:6xj4g5 */}
      </Rectangle>
      {/* pv-block-end:5ybvj3 */}

      {/* pv-block-start:16xx1w */}
      <Rectangle data-pv-block="16xx1w" data-pv-sketchpad-el="16xx1w"  style={{ position: 'absolute', left: 50, top: 171 }}>
        {/* pv-editable-zone-start:znd5i5 */}
        {/* pv-editable-zone-end:znd5i5 */}
      </Rectangle>
      {/* pv-block-end:16xx1w */}

      {/* pv-block-start:65mrdq */}
      <Rectangle data-pv-block="65mrdq" data-pv-sketchpad-el="65mrdq"  style={{ position: 'absolute', left: 94, top: 30 }}>
        {/* pv-editable-zone-start:s0ibce */}
        {/* pv-editable-zone-end:s0ibce */}
      </Rectangle>
      {/* pv-block-end:65mrdq */}
      
      {/* pv-block-start:3blium */}
      <Rectangle data-pv-block="3blium" data-pv-sketchpad-el="3blium"  style={{ position: 'absolute', height: 219, width: 513, left: 218, top: 54 }}>
        {/* pv-editable-zone-start:bddck1 */}
        {/* pv-block-start:izab1l */}
        <div data-pv-block="izab1l" className="flex flex-col gap-4" data-pv-sketchpad-el="izab1l" style={{ position: 'absolute', width: 416, left: 36, top: 61 }}>
          {/* pv-editable-zone-start:aj26iu */}
          {/* pv-block-start:nryq47 */}
          <InfoBoxBanner data-pv-block="nryq47" icon="Info" heading="Heads up" secondaryText="Something needs your attention." color="info" showCloseButton={true} >
          {/* pv-editable-zone-start:17kg7f */}
          {/* pv-editable-zone-end:17kg7f */}
          </InfoBoxBanner>
          {/* pv-block-end:nryq47 */}
          {/* pv-block-start:szk8tq */}
          <SuperLabel heading="Dupa" data-pv-block="szk8tq" primaryText="Label" style={{ width: 179 }} />
          {/* pv-block-end:szk8tq */}
          {/* pv-editable-zone-end:aj26iu */}
        </div>
        {/* pv-block-end:izab1l */}

        {/* pv-block-start:tenj4v */}
      <TextBlock data-pv-block="tenj4v" data-pv-sketchpad-el="tenj4v" typography="heading-md" style={{ position: 'absolute', left: 33, top: 21 }}>
        Text block
      </TextBlock>
      {/* pv-block-end:tenj4v */}
        {/* pv-editable-zone-end:bddck1 */}
      </Rectangle>
      {/* pv-block-end:3blium */}

      {/* pv-block-start:pro48d */}
          <div data-pv-block="pro48d" className="flex flex-col gap-2" data-pv-sketchpad-el="pro48d" style={{ position: 'absolute', left: 560, top: 562 }}>
          {/* pv-editable-zone-start:bla8ry */}
          {/* pv-editable-zone-end:bla8ry */}
          </div>
          {/* pv-block-end:pro48d */}

      {/* pv-block-start:t4hjjq */}
          <div data-pv-block="t4hjjq" className="flex flex-col gap-2" data-pv-sketchpad-el="t4hjjq" style={{ position: 'absolute', left: 390, top: 550 }}>
          {/* pv-editable-zone-start:bla8ry */}
          {/* pv-editable-zone-end:bla8ry */}
          </div>
          {/* pv-block-end:t4hjjq */}

      {/* pv-block-start:oz8gbk */}
      <div data-pv-block="oz8gbk" className="flex gap-2 flex-row" data-pv-sketchpad-el="oz8gbk" style={{ position: 'absolute', left: 234, top: 535 }}>
        {/* pv-editable-zone-start:1cxv9v */}
        {/* pv-block-start:yjh0f5 */}
        <Button data-pv-block="yjh0f5" label="Button" variant="outline" color="primary" size="md" />
        {/* pv-block-end:yjh0f5 */}
        {/* pv-block-start:2yr3pt */}
        <Button rightIcon="ArrowRight" data-pv-block="2yr3pt" label="Continue!" variant="solid" color="primary" size="md" />
        {/* pv-block-end:2yr3pt */}
        {/* pv-editable-zone-end:1cxv9v */}
      </div>
      {/* pv-block-end:oz8gbk */}

      {/* pv-block-start:r220ba */}
          <Card data-pv-block="r220ba" variant="bordered" shadow="none" border="default" style={{ position: 'absolute', left: 177, top: 327, width: 365 }} data-pv-sketchpad-el="r220ba">
          {/* pv-editable-zone-start:taxyss */}
          {/* pv-block-start:h4p0vu */}
      <Card data-pv-block="h4p0vu" variant="bordered" shadow="none" border="default" >
        {/* pv-editable-zone-start:xi74a7 */}
        {/* pv-editable-zone-end:xi74a7 */}
      </Card>
      {/* pv-block-end:h4p0vu */}

          {/* pv-block-start:o8izl4 */}
      <Card data-pv-block="o8izl4" variant="bordered" shadow="none" border="default" >
        {/* pv-editable-zone-start:xi74a7 */}
        {/* pv-editable-zone-end:xi74a7 */}
      </Card>
      {/* pv-block-end:o8izl4 */}

          {/* pv-block-start:rkwpcs */}
      <Card data-pv-block="rkwpcs" variant="bordered" shadow="none" border="default" >
        {/* pv-editable-zone-start:xi74a7 */}
        {/* pv-editable-zone-end:xi74a7 */}
      </Card>
      {/* pv-block-end:rkwpcs */}
          {/* pv-editable-zone-end:taxyss */}
          </Card>
          {/* pv-block-end:r220ba */}

      {/* pv-block-start:7bkjyx */}
      <Button data-pv-block="7bkjyx" label="Button" variant="solid" color="primary" size="md"   data-pv-sketchpad-el="7bkjyx" style={{ position: 'absolute', left: 100, top: 100 }}/>
      {/* pv-block-end:7bkjyx */}
      
      {/* pv-block-start:f3cl7i */}
          <Card data-pv-block="f3cl7i" variant="bordered" shadow="none" border="default" style={{ position: 'absolute', left: 183, top: 423, width: 365 }} data-pv-sketchpad-el="f3cl7i">
          {/* pv-editable-zone-start:taxyss */}
          {/* pv-block-start:2o75vk */}
          <div data-pv-block="2o75vk" className="flex gap-2 flex-row" >
          {/* pv-editable-zone-start:x6aovb */}
          {/* pv-editable-zone-end:x6aovb */}
          </div>
          {/* pv-block-end:2o75vk */}
          
          {/* pv-block-start:qab5st */}
          <div className="flex flex-col min-h-4" data-pv-block="qab5st">
          {/* pv-editable-zone-start:inside-qab5st */}
          {/* pv-editable-zone-end:inside-qab5st */}
          </div>
          {/* pv-block-end:qab5st */}
          {/* pv-editable-zone-end:taxyss */}
          </Card>
          {/* pv-block-end:f3cl7i */}

      {/* pv-block-start:7czgji */}
      <Rectangle data-pv-block="7czgji" data-pv-sketchpad-el="7czgji" className="w-[200px] h-[200px]" style={{ position: 'absolute', left: 579, top: 298 }}>
        {/* pv-editable-zone-start:wzfyo4 */}
        {/* pv-editable-zone-end:wzfyo4 */}
      </Rectangle>
      {/* pv-block-end:7czgji */}
      {/* pv-editable-zone-end:hxwp0f */}
    </div>
  );
}
