// Auto-generated by Protovibe Sketchpad
import { Rectangle } from '@/components/ui/sketchpad-rectangle';
import { TextBlock } from '@/components/ui/text-block'

export default function Frame3() {
  return (
    <div data-layout-mode="absolute" style={{ width: '100%', height: '100%', position: 'relative' }}>
      {/* pv-editable-zone-start:jzcc0h */}
      
      {/* pv-block-start:ctjldf */}
      <Rectangle data-pv-block="ctjldf" data-pv-sketchpad-el="ctjldf" className="w-[200px] h-[200px]" style={{ position: 'absolute', left: 83, top: 98 }}>
        {/* pv-editable-zone-start:ftt61c */}
        {/* pv-editable-zone-end:ftt61c */}
      </Rectangle>
      {/* pv-block-end:ctjldf */}

      {/* pv-block-start:0bjh21 */}
        <Rectangle data-pv-block="0bjh21" className="w-[200px] h-[200px]" data-pv-sketchpad-el="0bjh21" style={{ position: 'absolute', left: 331, top: 93 }}>
          {/* pv-editable-zone-start:fn1xxk */}
          {/* pv-block-start:8anhjk */}
                    <TextBlock data-pv-block="8anhjk" typography="heading-md" className="uppercase tracking-wider" data-pv-sketchpad-el="8anhjk" style={{ position: 'absolute', left: 25, top: 25 }}>Total Headcount</TextBlock>
                    {/* pv-block-end:8anhjk */}
          {/* pv-editable-zone-end:fn1xxk */}
        </Rectangle>
        {/* pv-block-end:0bjh21 */}
      {/* pv-editable-zone-end:jzcc0h */}
    </div>
  );
}
