import { Rectangle } from '@/components/ui/sketchpad-rectangle'
import { Card } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Avatar } from '@/components/ui/avatar'
// Auto-generated by Protovibe Sketchpad

export default function Frame3() {
  return (
    <div data-layout-mode="absolute" style={{ width: '100%', height: '100%', position: 'relative' }}>
      {/* pv-editable-zone-start:ryr9h3 */}
        {/* pv-block-start:cokp68 */}
        <Rectangle data-pv-block="cokp68" data-pv-sketchpad-el="cokp68" style={{ position: 'absolute', height: 285, left: 127, top: 424, width: 458 }} className="w-[200px] h-[200px]">
          {/* pv-editable-zone-start:lmhc48 */}
            {/* pv-block-start:z9s8p4 */}
            <Card data-pv-block="z9s8p4"  data-pv-sketchpad-el="z9s8p4" style={{ position: 'absolute', left: 306, top: 14 }}>
              {/* pv-editable-zone-start:07m0ee */}
                {/* pv-block-start:iktsh1 */}
                <Badge data-pv-block="iktsh1"  label="Badge" color="primary" />
                {/* pv-block-end:iktsh1 */}
            
                {/* pv-block-start:tq2v3n */}
                <Badge data-pv-block="tq2v3n"  label="Badge" color="primary" />
                {/* pv-block-end:tq2v3n */}
              {/* pv-editable-zone-end:07m0ee */}
            </Card>
            {/* pv-block-end:z9s8p4 */}
            
            {/* pv-block-start:xjb6wl */}
            <Button data-pv-block="xjb6wl"  label="Button" variant="solid" color="primary" size="md"  data-pv-sketchpad-el="xjb6wl" style={{ position: 'absolute', left: 36, top: 27 }}/>
            {/* pv-block-end:xjb6wl */}
            {/* pv-block-start:hoso2n */}
            <Card data-pv-block="hoso2n"  data-pv-sketchpad-el="hoso2n" style={{ position: 'absolute', left: 177, top: 23 }}>
              {/* pv-editable-zone-start:07m0ee */}
                {/* pv-block-start:i5z0jm */}
                <Badge data-pv-block="i5z0jm"  label="Badge" color="primary" />
                {/* pv-block-end:i5z0jm */}
              {/* pv-editable-zone-end:07m0ee */}
            </Card>
            {/* pv-block-end:hoso2n */}
            {/* pv-block-start:15nv3a */}
            <Rectangle data-pv-block="15nv3a" data-pv-sketchpad-el="15nv3a" style={{ position: 'absolute', left: 67, top: 142, height: 102, width: 353 }} className="w-[200px] h-[200px]">
              {/* pv-editable-zone-start:ptsmqu */}
                {/* pv-block-start:x49cfp */}
                <Button data-pv-block="x49cfp"  label="Button" variant="solid" color="primary" size="md"  data-pv-sketchpad-el="x49cfp" style={{ position: 'absolute', left: 126, top: 47 }}/>
                {/* pv-block-end:x49cfp */}
                
                    {/* pv-block-start:i6i1s3 */}
                    <Badge data-pv-block="i6i1s3"  label="Badge" color="primary"  data-pv-sketchpad-el="i6i1s3" style={{ position: 'absolute', left: 103, top: 14 }}/>
                    {/* pv-block-end:i6i1s3 */}
              {/* pv-editable-zone-end:ptsmqu */}
            </Rectangle>
            {/* pv-block-end:15nv3a */}
            {/* pv-block-start:mcxaz0 */}
            <Button data-pv-block="mcxaz0"  label="Button" variant="solid" color="primary" size="md"  data-pv-sketchpad-el="mcxaz0" style={{ position: 'absolute', left: 430, top: 237 }}/>
            {/* pv-block-end:mcxaz0 */}

            {/* pv-block-start:wizcuo */}
            <Button data-pv-block="wizcuo"  label="Button" variant="solid" color="primary" size="md"  data-pv-sketchpad-el="wizcuo" style={{ position: 'absolute', left: 266, top: 64 }}/>
            {/* pv-block-end:wizcuo */}
            {/* pv-block-start:dwljcy */}
            <Avatar data-pv-block="dwljcy" data-pv-sketchpad-el="dwljcy" style={{ position: 'absolute', left: 46, top: 86 }} initials="AB" size="md" bgColor="default" imageSrc="https://i.pravatar.cc/60" />
            {/* pv-block-end:dwljcy */}
          {/* pv-editable-zone-end:lmhc48 */}
        </Rectangle>
        {/* pv-block-end:cokp68 */}
        
        {/* pv-block-start:k167d8 */}
        <Rectangle data-pv-block="k167d8" data-pv-sketchpad-el="k167d8" style={{ position: 'absolute', left: 126, top: 125, width: 458 }} className="w-[200px] h-[200px]">
          {/* pv-editable-zone-start:lmhc48 */}
            {/* pv-block-start:u6ps4n */}
            <Card data-pv-block="u6ps4n"  data-pv-sketchpad-el="u6ps4n" style={{ position: 'absolute', left: 305, top: 14 }}>
              {/* pv-editable-zone-start:07m0ee */}
                {/* pv-block-start:kiupk5 */}
                <Badge data-pv-block="kiupk5"  label="Badge" color="primary" />
                {/* pv-block-end:kiupk5 */}
            
                {/* pv-block-start:ni8v5o */}
                <Badge data-pv-block="ni8v5o"  label="Badge" color="primary" />
                {/* pv-block-end:ni8v5o */}
                {/* pv-block-start:4pj587 */}
                <Button data-pv-block="4pj587"  label="Button" variant="solid" color="primary" size="md" />
                {/* pv-block-end:4pj587 */}
                
                {/* pv-block-start:xsxrxb */}
                <Button data-pv-block="xsxrxb"  label="Button" variant="solid" color="primary" size="md" />
                {/* pv-block-end:xsxrxb */}
              {/* pv-editable-zone-end:07m0ee */}
            </Card>
            {/* pv-block-end:u6ps4n */}
            
            {/* pv-block-start:a3rvgg */}
            <Button data-pv-block="a3rvgg"  label="Button" variant="solid" color="primary" size="md"  data-pv-sketchpad-el="a3rvgg" style={{ position: 'absolute', left: 35, top: 27 }}/>
            {/* pv-block-end:a3rvgg */}
          {/* pv-editable-zone-end:lmhc48 */}
        </Rectangle>
        {/* pv-block-end:k167d8 */}
        {/* pv-block-start:b1449o */}
        <Button data-pv-block="b1449o"  label="Button" variant="solid" color="primary" size="md"  data-pv-sketchpad-el="b1449o" style={{ position: 'absolute', left: 697, top: 382 }}/>
        {/* pv-block-end:b1449o */}
        {/* pv-block-start:lxrjql */}
        <Button data-pv-block="lxrjql"  label="Button" variant="solid" color="primary" size="md"  data-pv-sketchpad-el="lxrjql" style={{ position: 'absolute', left: 738, top: 192 }}/>
        {/* pv-block-end:lxrjql */}
        {/* pv-block-start:w53feg */}
        <Button data-pv-block="w53feg"  label="Button" variant="solid" color="primary" size="md"  data-pv-sketchpad-el="w53feg" style={{ position: 'absolute', left: 100, top: 100 }}/>
        {/* pv-block-end:w53feg */}
      {/* pv-editable-zone-end:ryr9h3 */}
    </div>
  );
}
