import { TextHeading } from '@/components/ui/text-heading'
import { TextParagraph } from '@/components/ui/text-paragraph'
import { Icon } from '@/components/ui/icon'
import { Rectangle } from '@/components/ui/sketchpad-rectangle'
import { Button } from '@/components/ui/button'
import { Card } from '@/components/ui/card'
// Auto-generated by Protovibe Sketchpad

export default function Frame4() {
  return (
    <div className="bg-background-sunken" data-layout-mode="absolute" style={{ width: '100%', height: '100%', position: 'relative' }}>
      {/* pv-editable-zone-start:2qgryk */}
        {/* pv-block-start:trph48 */}
        <Rectangle data-pv-block="trph48" data-pv-sketchpad-el="trph48" style={{ position: 'absolute', height: 683, width: 720, left: 376, top: 155 }} className="w-[200px] h-[200px] overflow-hidden border-0 bg-background-tertiary">
          {/* pv-editable-zone-start:tcajes */}
            {/* pv-block-start:ngm7rv */}
            <TextHeading data-pv-block="ngm7rv" data-pv-sketchpad-el="ngm7rv" style={{ position: 'absolute', left: 27, top: 24 }} typography="heading-md">
              Landing page
            </TextHeading>
            {/* pv-block-end:ngm7rv */}
            {/* pv-block-start:yp0qmq */}
            <div data-pv-block="yp0qmq" className="flex flex-row bg-background-success-subtle rounded-full py-1 px-2 gap-1" data-pv-sketchpad-el="yp0qmq" style={{ position: 'absolute', left: 465, top: 28 }}>
              {/* pv-editable-zone-start:ggzcx6 */}
              {/* pv-block-start:6ftqkc */}
              <Icon className="text-foreground-success" data-pv-block="6ftqkc"  iconSymbol="icon-park-outline:dot" size="md" />
              {/* pv-block-end:6ftqkc */}
              {/* pv-block-start:tjk8d6 */}
              <TextParagraph className="text-foreground-success" data-pv-block="tjk8d6"  typography="regular">
                Project is running
              </TextParagraph>
              {/* pv-block-end:tjk8d6 */}
              {/* pv-editable-zone-end:ggzcx6 */}
            </div>
            {/* pv-block-end:yp0qmq */}

            {/* pv-block-start:80fnz3 */}
            <Button leftIcon="ri:more-fill" iconOnly data-pv-block="80fnz3" data-pv-sketchpad-el="80fnz3" style={{ position: 'absolute', left: 638, top: 25 }} label="Button" variant="ghost" color="neutral" size="md" />
            {/* pv-block-end:80fnz3 */}
            {/* pv-block-start:brq2ii */}
            <Rectangle data-pv-block="brq2ii" data-pv-sketchpad-el="brq2ii" style={{ position: 'absolute', left: 30, top: 99, height: 69, width: 638 }} className="w-[200px] h-[200px] border-0 bg-background-primary">
              {/* pv-editable-zone-start:nhhnog */}
                {/* pv-block-start:d9srur */}
                <TextParagraph className="text-base text-foreground-on-primary" data-pv-block="d9srur" data-pv-sketchpad-el="d9srur" style={{ position: 'absolute', left: 62, top: 25 }} typography="regular">
                  Open Protovibe Editor
                </TextParagraph>
                {/* pv-block-end:d9srur */}
                {/* pv-block-start:8lgt70 */}
                <Icon className="text-foreground-on-primary" data-pv-block="8lgt70" data-pv-sketchpad-el="8lgt70" style={{ position: 'absolute', left: 22, top: 21 }} iconSymbol="majesticons:open" size="lg" />
                {/* pv-block-end:8lgt70 */}
              {/* pv-editable-zone-end:nhhnog */}
            </Rectangle>
            {/* pv-block-end:brq2ii */}
            {/* pv-block-start:ytk9a8 */}
            <TextParagraph className="text-foreground-secondary" data-pv-block="ytk9a8" data-pv-sketchpad-el="ytk9a8" style={{ position: 'absolute', left: 28, top: 51 }} typography="regular">
              Created 20 Dec 2028
            </TextParagraph>
            {/* pv-block-end:ytk9a8 */}
            {/* pv-block-start:j87d9l */}
            <Button rightIcon="mdi:chevron-down" data-pv-block="j87d9l" data-pv-sketchpad-el="j87d9l" style={{ position: 'absolute', left: 33, top: 604 }} label="Show logs" variant="ghost" color="neutral" size="md" />
            {/* pv-block-end:j87d9l */}
            {/* pv-block-start:obx64f */}
            <Rectangle data-pv-block="obx64f" data-pv-sketchpad-el="obx64f" style={{ position: 'absolute', left: 26, top: 265, height: 64, width: 635 }} className="w-[200px] h-[200px] border-0 bg-background-secondary">
              {/* pv-editable-zone-start:nhhnog */}
                {/* pv-block-start:tpejkj */}
                <TextParagraph className="text-foreground-secondary" data-pv-block="tpejkj" data-pv-sketchpad-el="tpejkj" style={{ position: 'absolute', left: 62, top: 23 }} typography="regular">
                  Restart server
                </TextParagraph>
                {/* pv-block-end:tpejkj */}
                {/* pv-block-start:0extc1 */}
                <Icon data-pv-block="0extc1" data-pv-sketchpad-el="0extc1" style={{ position: 'absolute', left: 22, top: 21 }} iconSymbol="mdi:restart" size="lg" />
                {/* pv-block-end:0extc1 */}
              {/* pv-editable-zone-end:nhhnog */}
            </Rectangle>
            {/* pv-block-end:obx64f */}
            {/* pv-block-start:qcevel */}
            <Rectangle data-pv-block="qcevel" data-pv-sketchpad-el="qcevel" style={{ position: 'absolute', left: 32, top: 349, height: 69, width: 628 }} className="w-[200px] h-[200px] border-0 bg-background-secondary">
              {/* pv-editable-zone-start:nhhnog */}
                {/* pv-block-start:o2muec */}
                <TextParagraph className="text-foreground-secondary" data-pv-block="o2muec" data-pv-sketchpad-el="o2muec" style={{ position: 'absolute', left: 62, top: 23 }} typography="regular">
                  Open in VS code
                </TextParagraph>
                {/* pv-block-end:o2muec */}
                {/* pv-block-start:4hpnlb */}
                <Icon data-pv-block="4hpnlb" data-pv-sketchpad-el="4hpnlb" style={{ position: 'absolute', left: 22, top: 21 }} iconSymbol="material-symbols:code" size="lg" />
                {/* pv-block-end:4hpnlb */}
              {/* pv-editable-zone-end:nhhnog */}
            </Rectangle>
            {/* pv-block-end:qcevel */}
            {/* pv-block-start:abl55o */}
            <Rectangle data-pv-block="abl55o" data-pv-sketchpad-el="abl55o" style={{ position: 'absolute', left: 33, top: 432, height: 69, width: 628 }} className="w-[200px] h-[200px] border-0 bg-background-secondary">
              {/* pv-editable-zone-start:nhhnog */}
                {/* pv-block-start:659p4t */}
                <TextParagraph className="text-foreground-secondary" data-pv-block="659p4t" data-pv-sketchpad-el="659p4t" style={{ position: 'absolute', left: 62, top: 23 }} typography="regular">
                  Open Folder
                </TextParagraph>
                {/* pv-block-end:659p4t */}
                {/* pv-block-start:wjee67 */}
                <Icon data-pv-block="wjee67" data-pv-sketchpad-el="wjee67" style={{ position: 'absolute', left: 22, top: 21 }} iconSymbol="material-symbols:folder-outline" size="lg" />
                {/* pv-block-end:wjee67 */}
              {/* pv-editable-zone-end:nhhnog */}
            </Rectangle>
            {/* pv-block-end:abl55o */}
            {/* pv-block-start:9dg1kc */}
            <Rectangle data-pv-block="9dg1kc" data-pv-sketchpad-el="9dg1kc" style={{ position: 'absolute', left: 30, top: 185, height: 62, width: 632 }} className="w-[200px] h-[200px] border-0 bg-background-secondary">
              {/* pv-editable-zone-start:nhhnog */}
                {/* pv-block-start:4lzp4z */}
                <TextParagraph className="text-foreground-secondary" data-pv-block="4lzp4z" data-pv-sketchpad-el="4lzp4z" style={{ position: 'absolute', left: 57, top: 22 }} typography="regular">
                  Stop server
                </TextParagraph>
                {/* pv-block-end:4lzp4z */}
                {/* pv-block-start:yrz3ka */}
                <Icon data-pv-block="yrz3ka" data-pv-sketchpad-el="yrz3ka" style={{ position: 'absolute', left: 22, top: 21 }} iconSymbol="material-symbols:stop" size="lg" />
                {/* pv-block-end:yrz3ka */}
              {/* pv-editable-zone-end:nhhnog */}
            </Rectangle>
            {/* pv-block-end:9dg1kc */}
            {/* pv-block-start:swqjw9 */}
            <TextParagraph className="text-foreground-tertiary" data-pv-block="swqjw9" data-pv-sketchpad-el="swqjw9" style={{ position: 'absolute', left: 491, top: 614 }} typography="small">
              Protovibe plugin v0.4 beta
            </TextParagraph>
            {/* pv-block-end:swqjw9 */}
            {/* pv-block-start:59qwj4 */}
            <Rectangle data-pv-block="59qwj4" data-pv-sketchpad-el="59qwj4" style={{ position: 'absolute', left: 35, top: 512, height: 69, width: 628 }} className="w-[200px] h-[200px] border-0 bg-background-secondary">
              {/* pv-editable-zone-start:nhhnog */}
                {/* pv-block-start:n0ej49 */}
                <TextParagraph className="text-foreground-secondary" data-pv-block="n0ej49" data-pv-sketchpad-el="n0ej49" style={{ position: 'absolute', left: 62, top: 23 }} typography="regular">
                  Open Folder
                </TextParagraph>
                {/* pv-block-end:n0ej49 */}
                {/* pv-block-start:0zflak */}
                <Icon data-pv-block="0zflak" data-pv-sketchpad-el="0zflak" style={{ position: 'absolute', left: 22, top: 21 }} iconSymbol="material-symbols:folder-outline" size="lg" />
                {/* pv-block-end:0zflak */}
              {/* pv-editable-zone-end:nhhnog */}
            </Rectangle>
            {/* pv-block-end:59qwj4 */}
          {/* pv-editable-zone-end:tcajes */}
        </Rectangle>
        {/* pv-block-end:trph48 */}
        {/* pv-block-start:1cf47t */}
        <Rectangle data-pv-block="1cf47t" data-pv-sketchpad-el="1cf47t" style={{ position: 'absolute', height: 53, width: 1438, left: 0, top: 0 }} className="w-[200px] h-[200px] rounded-none border-t-0 border-r-0 border-b border-l-0">
          {/* pv-editable-zone-start:nqtwmj */}
            {/* pv-block-start:s92mal */}
            <TextHeading data-pv-block="s92mal" data-pv-sketchpad-el="s92mal" style={{ position: 'absolute', left: 29, top: 12 }} typography="heading-md">
              Protovibe
            </TextHeading>
            {/* pv-block-end:s92mal */}
            {/* pv-block-start:kjir1k */}
            <TextParagraph className="text-foreground-tertiary" data-pv-block="kjir1k" data-pv-sketchpad-el="kjir1k" style={{ position: 'absolute', left: 1271, top: 19 }} typography="small">
              Version. 0.4 beta
            </TextParagraph>
            {/* pv-block-end:kjir1k */}
            {/* pv-block-start:ognuok */}
            <Button leftIcon="material-symbols:help-outline" iconOnly data-pv-block="ognuok" data-pv-sketchpad-el="ognuok" style={{ position: 'absolute', left: 1386, top: 5 }} label="Button" variant="ghost" color="neutral" size="lg" />
            {/* pv-block-end:ognuok */}
          {/* pv-editable-zone-end:nqtwmj */}
        </Rectangle>
        {/* pv-block-end:1cf47t */}
        {/* pv-block-start:5ba37x */}
        <Button leftIcon="material-symbols:arrow-back"  data-pv-block="5ba37x" data-pv-sketchpad-el="5ba37x" style={{ position: 'absolute', left: 376, top: 78 }} label="Back to projects" variant="ghost" color="neutral" size="md" />
        {/* pv-block-end:5ba37x */}
      {/* pv-editable-zone-end:2qgryk */}
    </div>
  );
}
