import { TextHeading } from '@/components/ui/text-heading'
import { TextParagraph } from '@/components/ui/text-paragraph'
import { Icon } from '@/components/ui/icon'
import { Rectangle } from '@/components/ui/sketchpad-rectangle'
import { Button } from '@/components/ui/button'
// Auto-generated by Protovibe Sketchpad

export default function Frame4() {
  return (
    <div className="bg-background-sunken" data-layout-mode="absolute" style={{ width: '100%', height: '100%', position: 'relative' }}>
      {/* pv-editable-zone-start:r320ux */}
        {/* pv-block-start:0jy17y */}
        <Rectangle data-pv-block="0jy17y" data-pv-sketchpad-el="0jy17y" style={{ position: 'absolute', height: 607, width: 702, left: 368, top: 173 }} className="w-[200px] h-[200px] bg-background-default">
          {/* pv-editable-zone-start:h8b78m */}
            {/* pv-block-start:iilprx */}
            <TextHeading data-pv-block="iilprx" data-pv-sketchpad-el="iilprx" style={{ position: 'absolute', left: 27, top: 24 }} typography="heading-md">
              Landing page
            </TextHeading>
            {/* pv-block-end:iilprx */}
            {/* pv-block-start:8u8hx8 */}
            <div data-pv-block="8u8hx8" className="flex flex-row bg-background-success-subtle rounded-full py-1 px-2 gap-1" data-pv-sketchpad-el="8u8hx8" style={{ position: 'absolute', left: 465, top: 28 }}>
              {/* pv-editable-zone-start:yo5bb9 */}
              {/* pv-block-start:eehs9o */}
              <Icon className="text-foreground-success" data-pv-block="eehs9o"  iconSymbol="icon-park-outline:dot" size="md" />
              {/* pv-block-end:eehs9o */}
              {/* pv-block-start:ll1cyw */}
              <TextParagraph className="text-foreground-success" data-pv-block="ll1cyw"  typography="regular">
                Project is running
              </TextParagraph>
              {/* pv-block-end:ll1cyw */}
              {/* pv-editable-zone-end:yo5bb9 */}
            </div>
            {/* pv-block-end:8u8hx8 */}

            {/* pv-block-start:rcsnjv */}
            <Button leftIcon="ri:more-fill" iconOnly data-pv-block="rcsnjv" data-pv-sketchpad-el="rcsnjv" style={{ position: 'absolute', left: 638, top: 25 }} label="Button" variant="ghost" color="neutral" size="md" />
            {/* pv-block-end:rcsnjv */}
            {/* pv-block-start:kiif9e */}
            <Rectangle data-pv-block="kiif9e" data-pv-sketchpad-el="kiif9e" style={{ position: 'absolute', left: 33, top: 102, height: 69, width: 635 }} className="w-[200px] h-[200px] bg-background-primary-subtle border-0">
              {/* pv-editable-zone-start:8ly1e7 */}
                {/* pv-block-start:ixoym8 */}
                <TextParagraph className="text-base text-foreground-default" data-pv-block="ixoym8" data-pv-sketchpad-el="ixoym8" style={{ position: 'absolute', left: 62, top: 25 }} typography="regular">
                  Open Protovibe Editor
                </TextParagraph>
                {/* pv-block-end:ixoym8 */}
                {/* pv-block-start:lnxxko */}
                <Icon data-pv-block="lnxxko" data-pv-sketchpad-el="lnxxko" style={{ position: 'absolute', left: 22, top: 21 }} iconSymbol="majesticons:open" size="lg" />
                {/* pv-block-end:lnxxko */}
              {/* pv-editable-zone-end:8ly1e7 */}
            </Rectangle>
            {/* pv-block-end:kiif9e */}
            {/* pv-block-start:pyuofe */}
            <TextParagraph className="text-foreground-secondary" data-pv-block="pyuofe" data-pv-sketchpad-el="pyuofe" style={{ position: 'absolute', left: 28, top: 51 }} typography="regular">
              Created 20 Dec 2028
            </TextParagraph>
            {/* pv-block-end:pyuofe */}
            {/* pv-block-start:3kqn89 */}
            <Button rightIcon="mdi:chevron-down" data-pv-block="3kqn89" data-pv-sketchpad-el="3kqn89" style={{ position: 'absolute', left: 33, top: 534 }} label="Show logs" variant="ghost" color="neutral" size="md" />
            {/* pv-block-end:3kqn89 */}
            {/* pv-block-start:j2mc2z */}
            <Rectangle data-pv-block="j2mc2z" data-pv-sketchpad-el="j2mc2z" style={{ position: 'absolute', left: 33, top: 264, height: 64, width: 635 }} className="w-[200px] h-[200px] border-0 bg-background-secondary">
              {/* pv-editable-zone-start:8ly1e7 */}
                {/* pv-block-start:qv7g0p */}
                <TextParagraph className="text-foreground-secondary" data-pv-block="qv7g0p" data-pv-sketchpad-el="qv7g0p" style={{ position: 'absolute', left: 62, top: 23 }} typography="regular">
                  Restart server
                </TextParagraph>
                {/* pv-block-end:qv7g0p */}
                {/* pv-block-start:gklgbk */}
                <Icon data-pv-block="gklgbk" data-pv-sketchpad-el="gklgbk" style={{ position: 'absolute', left: 22, top: 21 }} iconSymbol="mdi:restart" size="lg" />
                {/* pv-block-end:gklgbk */}
              {/* pv-editable-zone-end:8ly1e7 */}
            </Rectangle>
            {/* pv-block-end:j2mc2z */}
            {/* pv-block-start:j4mo1i */}
            <Rectangle data-pv-block="j4mo1i" data-pv-sketchpad-el="j4mo1i" style={{ position: 'absolute', left: 33, top: 340, height: 69, width: 635 }} className="w-[200px] h-[200px] border-0 bg-background-secondary">
              {/* pv-editable-zone-start:8ly1e7 */}
                {/* pv-block-start:tagw6l */}
                <TextParagraph className="text-foreground-secondary" data-pv-block="tagw6l" data-pv-sketchpad-el="tagw6l" style={{ position: 'absolute', left: 62, top: 23 }} typography="regular">
                  Open in VS code
                </TextParagraph>
                {/* pv-block-end:tagw6l */}
                {/* pv-block-start:pv22c8 */}
                <Icon data-pv-block="pv22c8" data-pv-sketchpad-el="pv22c8" style={{ position: 'absolute', left: 22, top: 21 }} iconSymbol="material-symbols:code" size="lg" />
                {/* pv-block-end:pv22c8 */}
              {/* pv-editable-zone-end:8ly1e7 */}
            </Rectangle>
            {/* pv-block-end:j4mo1i */}
            {/* pv-block-start:9v49po */}
            <Rectangle data-pv-block="9v49po" data-pv-sketchpad-el="9v49po" style={{ position: 'absolute', left: 33, top: 423, height: 69, width: 635 }} className="w-[200px] h-[200px] border-0 bg-background-secondary">
              {/* pv-editable-zone-start:8ly1e7 */}
                {/* pv-block-start:1h4n21 */}
                <TextParagraph className="text-foreground-secondary" data-pv-block="1h4n21" data-pv-sketchpad-el="1h4n21" style={{ position: 'absolute', left: 62, top: 23 }} typography="regular">
                  Open Folder
                </TextParagraph>
                {/* pv-block-end:1h4n21 */}
                {/* pv-block-start:dqht1w */}
                <Icon data-pv-block="dqht1w" data-pv-sketchpad-el="dqht1w" style={{ position: 'absolute', left: 22, top: 21 }} iconSymbol="material-symbols:folder-outline" size="lg" />
                {/* pv-block-end:dqht1w */}
              {/* pv-editable-zone-end:8ly1e7 */}
            </Rectangle>
            {/* pv-block-end:9v49po */}
            {/* pv-block-start:mlswim */}
            <Rectangle data-pv-block="mlswim" data-pv-sketchpad-el="mlswim" style={{ position: 'absolute', left: 33, top: 186, height: 62, width: 635 }} className="w-[200px] h-[200px] border-0 bg-background-secondary">
              {/* pv-editable-zone-start:8ly1e7 */}
                {/* pv-block-start:tf209j */}
                <TextParagraph className="text-foreground-secondary" data-pv-block="tf209j" data-pv-sketchpad-el="tf209j" style={{ position: 'absolute', left: 57, top: 22 }} typography="regular">
                  Stop server
                </TextParagraph>
                {/* pv-block-end:tf209j */}
                {/* pv-block-start:apxgkl */}
                <Icon data-pv-block="apxgkl" data-pv-sketchpad-el="apxgkl" style={{ position: 'absolute', left: 22, top: 21 }} iconSymbol="material-symbols:stop" size="lg" />
                {/* pv-block-end:apxgkl */}
              {/* pv-editable-zone-end:8ly1e7 */}
            </Rectangle>
            {/* pv-block-end:mlswim */}
            {/* pv-block-start:3zp85h */}
            <TextParagraph className="text-foreground-tertiary" data-pv-block="3zp85h" data-pv-sketchpad-el="3zp85h" style={{ position: 'absolute', left: 509, top: 544 }} typography="small">
              Protovibe plugin v0.4 beta
            </TextParagraph>
            {/* pv-block-end:3zp85h */}
          {/* pv-editable-zone-end:h8b78m */}
        </Rectangle>
        {/* pv-block-end:0jy17y */}
        {/* pv-block-start:l8mo1b */}
        <Rectangle data-pv-block="l8mo1b" data-pv-sketchpad-el="l8mo1b" style={{ position: 'absolute', height: 53, width: 1438, left: 0, top: 0 }} className="w-[200px] h-[200px] rounded-none border-t-0 border-r-0 border-b border-l-0">
          {/* pv-editable-zone-start:ex4e93 */}
            {/* pv-block-start:gspawp */}
            <TextHeading data-pv-block="gspawp" data-pv-sketchpad-el="gspawp" style={{ position: 'absolute', left: 29, top: 12 }} typography="heading-md">
              Protovibe
            </TextHeading>
            {/* pv-block-end:gspawp */}
            {/* pv-block-start:u2en85 */}
            <TextParagraph className="text-foreground-tertiary" data-pv-block="u2en85" data-pv-sketchpad-el="u2en85" style={{ position: 'absolute', left: 1271, top: 19 }} typography="small">
              Version. 0.4 beta
            </TextParagraph>
            {/* pv-block-end:u2en85 */}
            {/* pv-block-start:1sstgg */}
            <Button leftIcon="material-symbols:help-outline" iconOnly data-pv-block="1sstgg" data-pv-sketchpad-el="1sstgg" style={{ position: 'absolute', left: 1386, top: 5 }} label="Button" variant="ghost" color="neutral" size="lg" />
            {/* pv-block-end:1sstgg */}
          {/* pv-editable-zone-end:ex4e93 */}
        </Rectangle>
        {/* pv-block-end:l8mo1b */}
        {/* pv-block-start:c779wm */}
        <Button leftIcon="material-symbols:arrow-back"  data-pv-block="c779wm" data-pv-sketchpad-el="c779wm" style={{ position: 'absolute', left: 368, top: 106 }} label="Back to projects" variant="ghost" color="neutral" size="md" />
        {/* pv-block-end:c779wm */}
      {/* pv-editable-zone-end:r320ux */}
    </div>
  );
}
