import { TextHeading } from '@/components/ui/text-heading'
import { TextParagraph } from '@/components/ui/text-paragraph'
import { Icon } from '@/components/ui/icon'
import { Rectangle } from '@/components/ui/sketchpad-rectangle'
import { Button } from '@/components/ui/button'
import { Card } from '@/components/ui/card'
// Auto-generated by Protovibe Sketchpad

export default function Frame4() {
  return (
    <div data-layout-mode="absolute" style={{ width: '100%', height: '100%', position: 'relative' }}>
      {/* pv-editable-zone-start:5i8fr3 */}
        {/* pv-block-start:9y11p6 */}
        <Rectangle data-pv-block="9y11p6" data-pv-sketchpad-el="9y11p6" style={{ position: 'absolute', height: 607, width: 702, left: 378, top: 142 }} className="w-[200px] h-[200px] bg-background-elevated">
          {/* pv-editable-zone-start:mhi2f7 */}
            {/* pv-block-start:9v7sg0 */}
            <TextHeading data-pv-block="9v7sg0" data-pv-sketchpad-el="9v7sg0" style={{ position: 'absolute', left: 27, top: 24 }} typography="heading-md">
              Landing page
            </TextHeading>
            {/* pv-block-end:9v7sg0 */}
            {/* pv-block-start:vdx7m4 */}
            <Icon className="text-foreground-success" data-pv-block="vdx7m4" data-pv-sketchpad-el="vdx7m4" style={{ position: 'absolute', left: 489, top: 25 }} iconSymbol="icon-park-outline:dot" size="md" />
            {/* pv-block-end:vdx7m4 */}
            {/* pv-block-start:j5b4zv */}
            <TextParagraph className="text-foreground-success" data-pv-block="j5b4zv" data-pv-sketchpad-el="j5b4zv" style={{ position: 'absolute', left: 512, top: 25 }} typography="regular">
              Project is running
            </TextParagraph>
            {/* pv-block-end:j5b4zv */}
            {/* pv-block-start:ga1xa2 */}
            <Button leftIcon="ri:more-fill" iconOnly data-pv-block="ga1xa2" data-pv-sketchpad-el="ga1xa2" style={{ position: 'absolute', left: 642, top: 18 }} label="Button" variant="ghost" color="primary" size="md" />
            {/* pv-block-end:ga1xa2 */}
            {/* pv-block-start:82gkix */}
            <Rectangle data-pv-block="82gkix" data-pv-sketchpad-el="82gkix" style={{ position: 'absolute', left: 27, top: 102, height: 69, width: 635 }} className="w-[200px] h-[200px] bg-background-primary-subtle border-0">
              {/* pv-editable-zone-start:2s5zqz */}
                {/* pv-block-start:tief9g */}
                <TextParagraph className="text-foreground-secondary" data-pv-block="tief9g" data-pv-sketchpad-el="tief9g" style={{ position: 'absolute', left: 62, top: 23 }} typography="regular">
                  Open Protovibe Editor
                </TextParagraph>
                {/* pv-block-end:tief9g */}
                {/* pv-block-start:3do6n0 */}
                <Icon data-pv-block="3do6n0" data-pv-sketchpad-el="3do6n0" style={{ position: 'absolute', left: 22, top: 21 }} iconSymbol="majesticons:open" size="lg" />
                {/* pv-block-end:3do6n0 */}
              {/* pv-editable-zone-end:2s5zqz */}
            </Rectangle>
            {/* pv-block-end:82gkix */}
            {/* pv-block-start:fnjzp0 */}
            <TextParagraph className="text-foreground-secondary" data-pv-block="fnjzp0" data-pv-sketchpad-el="fnjzp0" style={{ position: 'absolute', left: 28, top: 51 }} typography="regular">
              Created 20 Dec 2028
            </TextParagraph>
            {/* pv-block-end:fnjzp0 */}
            {/* pv-block-start:ag7hk7 */}
            <Button rightIcon="mdi:chevron-down" data-pv-block="ag7hk7" data-pv-sketchpad-el="ag7hk7" style={{ position: 'absolute', left: 33, top: 542 }} label="Show logs" variant="ghost" color="neutral" size="md" />
            {/* pv-block-end:ag7hk7 */}
            {/* pv-block-start:la8i62 */}
            <Rectangle data-pv-block="la8i62" data-pv-sketchpad-el="la8i62" style={{ position: 'absolute', left: 27, top: 186, height: 69, width: 641 }} className="w-[200px] h-[200px] border-0 bg-background-secondary">
              {/* pv-editable-zone-start:2s5zqz */}
                {/* pv-block-start:9gaur2 */}
                <TextParagraph className="text-foreground-secondary" data-pv-block="9gaur2" data-pv-sketchpad-el="9gaur2" style={{ position: 'absolute', left: 62, top: 23 }} typography="regular">
                  Open Protovibe Editor
                </TextParagraph>
                {/* pv-block-end:9gaur2 */}
                {/* pv-block-start:pk6xy5 */}
                <Icon data-pv-block="pk6xy5" data-pv-sketchpad-el="pk6xy5" style={{ position: 'absolute', left: 22, top: 21 }} iconSymbol="majesticons:open" size="lg" />
                {/* pv-block-end:pk6xy5 */}
              {/* pv-editable-zone-end:2s5zqz */}
            </Rectangle>
            {/* pv-block-end:la8i62 */}
            {/* pv-block-start:q8inad */}
            <Rectangle data-pv-block="q8inad" data-pv-sketchpad-el="q8inad" style={{ position: 'absolute', left: 29, top: 268, height: 69, width: 641 }} className="w-[200px] h-[200px] border-0 bg-background-secondary">
              {/* pv-editable-zone-start:2s5zqz */}
                {/* pv-block-start:t5yahu */}
                <TextParagraph className="text-foreground-secondary" data-pv-block="t5yahu" data-pv-sketchpad-el="t5yahu" style={{ position: 'absolute', left: 62, top: 23 }} typography="regular">
                  Open Protovibe Editor
                </TextParagraph>
                {/* pv-block-end:t5yahu */}
                {/* pv-block-start:wbkpqs */}
                <Icon data-pv-block="wbkpqs" data-pv-sketchpad-el="wbkpqs" style={{ position: 'absolute', left: 22, top: 21 }} iconSymbol="majesticons:open" size="lg" />
                {/* pv-block-end:wbkpqs */}
              {/* pv-editable-zone-end:2s5zqz */}
            </Rectangle>
            {/* pv-block-end:q8inad */}
            {/* pv-block-start:ihrzin */}
            <Rectangle data-pv-block="ihrzin" data-pv-sketchpad-el="ihrzin" style={{ position: 'absolute', left: 29, top: 354, height: 69, width: 641 }} className="w-[200px] h-[200px] border-0 bg-background-secondary">
              {/* pv-editable-zone-start:2s5zqz */}
                {/* pv-block-start:kpx8q8 */}
                <TextParagraph className="text-foreground-secondary" data-pv-block="kpx8q8" data-pv-sketchpad-el="kpx8q8" style={{ position: 'absolute', left: 62, top: 23 }} typography="regular">
                  Open Protovibe Editor
                </TextParagraph>
                {/* pv-block-end:kpx8q8 */}
                {/* pv-block-start:tdjd6l */}
                <Icon data-pv-block="tdjd6l" data-pv-sketchpad-el="tdjd6l" style={{ position: 'absolute', left: 22, top: 21 }} iconSymbol="majesticons:open" size="lg" />
                {/* pv-block-end:tdjd6l */}
              {/* pv-editable-zone-end:2s5zqz */}
            </Rectangle>
            {/* pv-block-end:ihrzin */}
          {/* pv-editable-zone-end:mhi2f7 */}
        </Rectangle>
        {/* pv-block-end:9y11p6 */}
        {/* pv-block-start:15zxnd */}
        <TextHeading data-pv-block="15zxnd" data-pv-sketchpad-el="15zxnd" style={{ position: 'absolute', left: 377, top: 13 }} typography="heading-md">
          Protovibe
        </TextHeading>
        {/* pv-block-end:15zxnd */}
        {/* pv-block-start:8t0skv */}
        <Button leftIcon="material-symbols:arrow-back"  data-pv-block="8t0skv" data-pv-sketchpad-el="8t0skv" style={{ position: 'absolute', left: 376, top: 86 }} label="Back to projects" variant="ghost" color="neutral" size="md" />
        {/* pv-block-end:8t0skv */}
      {/* pv-editable-zone-end:5i8fr3 */}
    </div>
  );
}
