import { TextHeading } from '@/components/ui/text-heading'
import { TextParagraph } from '@/components/ui/text-paragraph'
import { Icon } from '@/components/ui/icon'
import { Rectangle } from '@/components/ui/sketchpad-rectangle'
import { Button } from '@/components/ui/button'
// Auto-generated by Protovibe Sketchpad

export default function Frame4() {
  return (
    <div data-layout-mode="absolute" style={{ width: '100%', height: '100%', position: 'relative' }}>
      {/* pv-editable-zone-start:jvssh6 */}
        {/* pv-block-start:1rk1fc */}
        <Rectangle data-pv-block="1rk1fc" data-pv-sketchpad-el="1rk1fc" style={{ position: 'absolute', height: 607, width: 702, left: 378, top: 142 }} className="w-[200px] h-[200px] bg-background-elevated">
          {/* pv-editable-zone-start:vpc8eh */}
            {/* pv-block-start:g78uyg */}
            <TextHeading data-pv-block="g78uyg" data-pv-sketchpad-el="g78uyg" style={{ position: 'absolute', left: 27, top: 24 }} typography="heading-md">
              Landing page
            </TextHeading>
            {/* pv-block-end:g78uyg */}
            {/* pv-block-start:50fvfe */}
            <Icon className="text-foreground-success" data-pv-block="50fvfe" data-pv-sketchpad-el="50fvfe" style={{ position: 'absolute', left: 489, top: 25 }} iconSymbol="icon-park-outline:dot" size="md" />
            {/* pv-block-end:50fvfe */}
            {/* pv-block-start:1qm1e7 */}
            <TextParagraph className="text-foreground-success" data-pv-block="1qm1e7" data-pv-sketchpad-el="1qm1e7" style={{ position: 'absolute', left: 512, top: 25 }} typography="regular">
              Project is running
            </TextParagraph>
            {/* pv-block-end:1qm1e7 */}
            {/* pv-block-start:inl6ta */}
            <Button leftIcon="ri:more-fill" iconOnly data-pv-block="inl6ta" data-pv-sketchpad-el="inl6ta" style={{ position: 'absolute', left: 642, top: 18 }} label="Button" variant="ghost" color="primary" size="md" />
            {/* pv-block-end:inl6ta */}
            {/* pv-block-start:ppm5na */}
            <Rectangle data-pv-block="ppm5na" data-pv-sketchpad-el="ppm5na" style={{ position: 'absolute', left: 27, top: 102, height: 69, width: 635 }} className="w-[200px] h-[200px] bg-background-primary-subtle border-0">
              {/* pv-editable-zone-start:gaixke */}
                {/* pv-block-start:7tat8u */}
                <TextParagraph className="text-foreground-secondary" data-pv-block="7tat8u" data-pv-sketchpad-el="7tat8u" style={{ position: 'absolute', left: 62, top: 23 }} typography="regular">
                  Open Protovibe Editor
                </TextParagraph>
                {/* pv-block-end:7tat8u */}
                {/* pv-block-start:7dib1t */}
                <Icon data-pv-block="7dib1t" data-pv-sketchpad-el="7dib1t" style={{ position: 'absolute', left: 22, top: 21 }} iconSymbol="majesticons:open" size="lg" />
                {/* pv-block-end:7dib1t */}
              {/* pv-editable-zone-end:gaixke */}
            </Rectangle>
            {/* pv-block-end:ppm5na */}
            {/* pv-block-start:8ndw0d */}
            <TextParagraph className="text-foreground-secondary" data-pv-block="8ndw0d" data-pv-sketchpad-el="8ndw0d" style={{ position: 'absolute', left: 28, top: 51 }} typography="regular">
              Created 20 Dec 2028
            </TextParagraph>
            {/* pv-block-end:8ndw0d */}
            {/* pv-block-start:cyebew */}
            <Button rightIcon="mdi:chevron-down" data-pv-block="cyebew" data-pv-sketchpad-el="cyebew" style={{ position: 'absolute', left: 33, top: 542 }} label="Show logs" variant="ghost" color="neutral" size="md" />
            {/* pv-block-end:cyebew */}
            {/* pv-block-start:v4be59 */}
            <Rectangle data-pv-block="v4be59" data-pv-sketchpad-el="v4be59" style={{ position: 'absolute', left: 27, top: 186, height: 69, width: 641 }} className="w-[200px] h-[200px] border-0 bg-background-secondary">
              {/* pv-editable-zone-start:gaixke */}
                {/* pv-block-start:j9q6g3 */}
                <TextParagraph className="text-foreground-secondary" data-pv-block="j9q6g3" data-pv-sketchpad-el="j9q6g3" style={{ position: 'absolute', left: 62, top: 23 }} typography="regular">
                  Open Protovibe Editor
                </TextParagraph>
                {/* pv-block-end:j9q6g3 */}
                {/* pv-block-start:lm51e1 */}
                <Icon data-pv-block="lm51e1" data-pv-sketchpad-el="lm51e1" style={{ position: 'absolute', left: 22, top: 21 }} iconSymbol="majesticons:open" size="lg" />
                {/* pv-block-end:lm51e1 */}
              {/* pv-editable-zone-end:gaixke */}
            </Rectangle>
            {/* pv-block-end:v4be59 */}
            {/* pv-block-start:621zdt */}
            <Rectangle data-pv-block="621zdt" data-pv-sketchpad-el="621zdt" style={{ position: 'absolute', left: 29, top: 268, height: 69, width: 641 }} className="w-[200px] h-[200px] border-0 bg-background-secondary">
              {/* pv-editable-zone-start:gaixke */}
                {/* pv-block-start:lm2x6d */}
                <TextParagraph className="text-foreground-secondary" data-pv-block="lm2x6d" data-pv-sketchpad-el="lm2x6d" style={{ position: 'absolute', left: 62, top: 23 }} typography="regular">
                  Open Protovibe Editor
                </TextParagraph>
                {/* pv-block-end:lm2x6d */}
                {/* pv-block-start:mcez9t */}
                <Icon data-pv-block="mcez9t" data-pv-sketchpad-el="mcez9t" style={{ position: 'absolute', left: 22, top: 21 }} iconSymbol="majesticons:open" size="lg" />
                {/* pv-block-end:mcez9t */}
              {/* pv-editable-zone-end:gaixke */}
            </Rectangle>
            {/* pv-block-end:621zdt */}
            {/* pv-block-start:g35qgq */}
            <Rectangle data-pv-block="g35qgq" data-pv-sketchpad-el="g35qgq" style={{ position: 'absolute', left: 29, top: 354, height: 69, width: 641 }} className="w-[200px] h-[200px] border-0 bg-background-secondary">
              {/* pv-editable-zone-start:gaixke */}
                {/* pv-block-start:q07lco */}
                <TextParagraph className="text-foreground-secondary" data-pv-block="q07lco" data-pv-sketchpad-el="q07lco" style={{ position: 'absolute', left: 62, top: 23 }} typography="regular">
                  Open Protovibe Editor
                </TextParagraph>
                {/* pv-block-end:q07lco */}
                {/* pv-block-start:cxl92w */}
                <Icon data-pv-block="cxl92w" data-pv-sketchpad-el="cxl92w" style={{ position: 'absolute', left: 22, top: 21 }} iconSymbol="majesticons:open" size="lg" />
                {/* pv-block-end:cxl92w */}
              {/* pv-editable-zone-end:gaixke */}
            </Rectangle>
            {/* pv-block-end:g35qgq */}
          {/* pv-editable-zone-end:vpc8eh */}
        </Rectangle>
        {/* pv-block-end:1rk1fc */}
        {/* pv-block-start:4bzl0e */}
        <TextHeading data-pv-block="4bzl0e" data-pv-sketchpad-el="4bzl0e" style={{ position: 'absolute', left: 377, top: 13 }} typography="heading-md">
          Protovibe
        </TextHeading>
        {/* pv-block-end:4bzl0e */}
        {/* pv-block-start:61t9gw */}
        <Button leftIcon="material-symbols:arrow-back"  data-pv-block="61t9gw" data-pv-sketchpad-el="61t9gw" style={{ position: 'absolute', left: 376, top: 86 }} label="Back to projects" variant="ghost" color="neutral" size="md" />
        {/* pv-block-end:61t9gw */}
      {/* pv-editable-zone-end:jvssh6 */}
    </div>
  );
}
