// Auto-generated by Protovibe Sketchpad
import { Button } from '@/components/ui/button';

export default function Frame1() {
  return (
    <div data-layout-mode="absolute" style={{ width: '100%', height: '100%', position: 'relative' }}>
      {/* pv-editable-zone-start:alnspl */}
      
      {/* pv-block-start:g44al7 */}
      <Button data-pv-block="g44al7" data-pv-sketchpad-el="g44al7" label="Button" variant="solid" color="primary" size="md" style={{ position: 'absolute', left: 100, top: 100 }} />
      {/* pv-block-end:g44al7 */}
      {/* pv-editable-zone-end:alnspl */}
    </div>
  );
}
