// Auto-generated by Protovibe Sketchpad
import { Button } from '@/components/ui/button';

export default function Frame1() {
  return (
    <div data-layout-mode="absolute" style={{ width: '100%', height: '100%', position: 'relative' }}>
      {/* pv-editable-zone-start:cnzto1 */}
      
      {/* pv-block-start:mzc8fb */}
      <Button data-pv-block="mzc8fb" data-pv-sketchpad-el="mzc8fb" label="Button" variant="solid" color="primary" size="md" style={{ position: 'absolute', left: 377, top: 228 }} />
      {/* pv-block-end:mzc8fb */}
      {/* pv-editable-zone-end:cnzto1 */}
    </div>
  );
}
