// Auto-generated by Protovibe Sketchpad
import { Avatar } from '@/components/ui/avatar';

export default function Frame1() {
  return (
    <div data-layout-mode="absolute" style={{ width: '100%', height: '100%', position: 'relative' }}>
      {/* pv-editable-zone-start:e20uun */}
      
      {/* pv-block-start:82zs17 */}
      <Avatar data-pv-block="82zs17" data-pv-sketchpad-el="82zs17" initials="AB" size="md" bgColor="default" imageSrc="https://i.pravatar.cc/60" style={{ position: 'absolute', left: 158, top: 263 }} />
      {/* pv-block-end:82zs17 */}
      {/* pv-editable-zone-end:e20uun */}
    </div>
  );
}
