import { Card } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { TextBlock } from '@/components/ui/text-block'
// Auto-generated by Protovibe Sketchpad

export default function Frame5() {
  return (
    <div style={{ width: '100%', height: '100%', position: 'relative' }}>
      {/* pv-editable-zone-start:desjuh */}

      {/* pv-block-start:6fne21 */}
          <Card className="flex justify-center flex-col w-1/2 items-start" data-pv-block="6fne21" variant="bordered" shadow="none">
            {/* pv-editable-zone-start:c1cn2h */}

            {/* pv-block-start:3en3ya */}
          <Button data-pv-block="3en3ya" label="Button" variant="solid" color="primary" size="md" />
          {/* pv-block-end:3en3ya */}

            {/* pv-block-start:3qcc7j */}
          <Button data-pv-block="3qcc7j" label="Button" variant="solid" color="primary" size="md" />
          {/* pv-block-end:3qcc7j */}
            {/* pv-editable-zone-end:c1cn2h */}
          </Card>
          {/* pv-block-end:6fne21 */}

      {/* pv-block-start:hprmw5 */}
          <Card className="my-10 w-full data-[variant=bordered]:border-px border-l-5 data-[variant=bordered]:border-t-4 data-[variant=bordered]:rounded-tl-none data-[variant=bordered]:rounded-tr-none bg-background-primary-subtle" data-pv-block="hprmw5"  >
            {/* pv-editable-zone-start:c5gbka */}
            {/* pv-block-start:e5qwgp */}
          <TextBlock className="font-thin" data-pv-block="e5qwgp" text="Text block Test" typography="heading-md" />
          {/* pv-block-end:e5qwgp */}

              {/* pv-block-start:3mulgt */}
              <Button data-pv-block="3mulgt" label="Button" variant="solid" color="primary" size="md" />
              {/* pv-block-end:3mulgt */}

            {/* pv-block-start:aqm5kc */}
          <Card className="flex justify-center flex-col w-1/2 items-start" data-pv-block="aqm5kc" variant="bordered" shadow="none">
            {/* pv-editable-zone-start:c1cn2h */}

            {/* pv-block-start:d1rm2u */}
          <Button data-pv-block="d1rm2u" label="Button" variant="solid" color="primary" size="md" />
          {/* pv-block-end:d1rm2u */}

            {/* pv-block-start:g3bioo */}
          <Button data-pv-block="g3bioo" label="Button" variant="solid" color="primary" size="md" />
          {/* pv-block-end:g3bioo */}
            {/* pv-editable-zone-end:c1cn2h */}
          </Card>
          {/* pv-block-end:aqm5kc */}

            {/* pv-block-start:1809yg */}
          <div className="flex-col min-h-4 bg-background-secondary rounded-md py-5 pl-2 pr-5" data-pv-block="1809yg">
            {/* pv-editable-zone-start:inside-1809yg */}
              {/* pv-block-start:l6pd1u */}
              <span data-pv-block="l6pd1u">
                Lorem ipsum
                {/* pv-editable-zone-start:inside-l6pd1u */}
                {/* pv-editable-zone-end:inside-l6pd1u */}
              </span>
              {/* pv-block-end:l6pd1u */}
            {/* pv-editable-zone-end:inside-1809yg */}
          </div>
          {/* pv-block-end:1809yg */}
            {/* pv-editable-zone-end:c5gbka */}
          </Card>
          {/* pv-block-end:hprmw5 */}
      {/* pv-editable-zone-end:desjuh */}
    </div>
  );
}
