// Auto-generated by Protovibe Sketchpad
import { VerticalTabs } from '@/components/ui/vertical-tabs';
import { VerticalTabItem } from '@/components/ui/vertical-tab-item';
import { DialogWindow } from '@/components/ui/dialog-window';
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge';
import { DropdownItem } from '@/components/ui/dropdown-item';

export default function Frame1() {
  return (
    <div style={{ width: '100%', height: '100%', position: 'relative' }}>
      {/* pv-editable-zone-start:ecam39 */}
      {/* pv-block-start:ak8bcl */}
      <Button data-pv-block="ak8bcl" data-pv-sketchpad-el="ak8bcl" label="Button" variant="solid" color="primary" size="md" style={{ position: 'absolute', left: 565, top: 399 }} />
      {/* pv-block-end:ak8bcl */}

      {/* pv-block-start:zvaeej */}
      <VerticalTabs data-pv-block="zvaeej" data-pv-sketchpad-el="zvaeej" value="tab1" style={{ position: 'absolute', width: 177, left: 40, top: 117 }}>
        {/* pv-editable-zone-start:6fhden */}
          {/* pv-block-start:rkwxmd */}
          <VerticalTabItem data-pv-block="rkwxmd" label="Dashboard" value="tab1" prefixIcon="LayoutDashboard">
            {/* pv-editable-zone-start:u3o2y1 */}
            {/* pv-editable-zone-end:u3o2y1 */}
          </VerticalTabItem>
          {/* pv-block-end:rkwxmd */}
          {/* pv-block-start:gd66vd */}
          <VerticalTabItem data-pv-block="gd66vd" label="Analytics" value="tab2" prefixIcon="BarChart2">
            {/* pv-editable-zone-start:i6pw48 */}
            {/* pv-editable-zone-end:i6pw48 */}
          </VerticalTabItem>
          {/* pv-block-end:gd66vd */}
          {/* pv-block-start:fo46cw */}
          <VerticalTabItem data-pv-block="fo46cw" label="Settings" value="tab3" prefixIcon="Settings">
            {/* pv-editable-zone-start:n8hkb2 */}
            {/* pv-editable-zone-end:n8hkb2 */}
          </VerticalTabItem>
          {/* pv-block-end:fo46cw */}
        {/* pv-editable-zone-end:6fhden */}
      </VerticalTabs>
      {/* pv-block-end:zvaeej */}
      
        {/* pv-block-start:ulvcic */}
        <div className="flex flex-col min-h-4 p-5" data-pv-block="ulvcic">
          {/* pv-editable-zone-start:inside-ulvcic */}
            {/* pv-block-start:9li3yc */}
            <Button data-pv-block="9li3yc" label="Button" variant="solid" color="primary" size="md" />
            {/* pv-block-end:9li3yc */}
          {/* pv-editable-zone-end:inside-ulvcic */}
        </div>
        {/* pv-block-end:ulvcic */}
      
      {/* pv-block-start:wy11we */}
      <Badge data-pv-block="wy11we" data-pv-sketchpad-el="wy11we" label="Test" color="primary" style={{ position: 'absolute', left: 333, top: 142 }} />
      {/* pv-block-end:wy11we */}

      {/* pv-block-start:q0b81h */}
      <DropdownItem data-pv-block="q0b81h" data-pv-sketchpad-el="q0b81h" label="Menu Item" style={{ position: 'absolute', left: 323, top: 198 }} />
      {/* pv-block-end:q0b81h */}

      {/* pv-block-start:xvi355 */}
      <Button data-pv-block="xvi355" data-pv-sketchpad-el="xvi355" label="Button" variant="solid" color="primary" size="md" style={{ position: 'absolute', left: 612, top: -86 }} />
      {/* pv-block-end:xvi355 */}
      {/* pv-editable-zone-end:ecam39 */}
    </div>
  );
}
