import { Button } from '@/components/ui/button'
// Auto-generated by Protovibe Sketchpad

export default function Frame6() {
  return (
    <div style={{ width: '100%', height: '100%', position: 'relative' }}>
      {/* pv-editable-zone-start:98hmpw */}
      {/* pv-block-start:5j3to0 */}
          <Button data-pv-block="5j3to0" label="Open Dialog" variant="solid" color="primary" size="md" />
          {/* pv-block-end:5j3to0 */}

                        {/* pv-block-start:73g490 */}
          <div className="flex flex-col min-h-4 p-5 bg-background-secondary rounded-md" data-pv-block="73g490">
            {/* pv-editable-zone-start:inside-73g490 */}
              {/* pv-block-start:49n227 */}
              <span data-pv-block="49n227">
                Lorem ipsum
                {/* pv-editable-zone-start:inside-49n227 */}
                {/* pv-editable-zone-end:inside-49n227 */}
              </span>
              {/* pv-block-end:49n227 */}
            {/* pv-editable-zone-end:inside-73g490 */}
          </div>
          {/* pv-block-end:73g490 */}
                                                {/* pv-editable-zone-end:98hmpw */}
    </div>
  );
}
