// Auto-generated by Protovibe Sketchpad

export default function Frame4() {
  return (
    <div style={{ width: '100%', height: '100%', position: 'relative' }}>
      {/* pv-editable-zone-start:a96c1l */}
      {/* pv-editable-zone-end:a96c1l */}
    </div>
  );
}
