import { Button } from '@/components/ui/button'
// Auto-generated by Protovibe Sketchpad

export default function Frame6() {
  return (
    <div style={{ width: '100%', height: '100%', position: 'relative' }}>
      {/* pv-editable-zone-start:98hmpw */}

      {/* pv-block-start:5j3to0 */}
          <Button data-pv-block="5j3to0" label="Open Dialog" variant="solid" color="primary" size="md" />
          {/* pv-block-end:5j3to0 */}
      {/* pv-editable-zone-end:98hmpw */}
    </div>
  );
}
