// Auto-generated by Protovibe Sketchpad
import { DialogTrigger } from '@/components/ui/dialog-trigger';
import { Button } from '@/components/ui/button';
import { DialogOverlay } from '@/components/ui/dialog-overlay';
import { DialogWindow } from '@/components/ui/dialog-window';
import { SegmentedControlItem } from '@/components/ui/segmented-control-item';

export default function Frame4() {
  return (
    <div style={{ width: '100%', height: '100%', position: 'relative' }}>
      {/* pv-editable-zone-start:qmqv3i */}
      {/* pv-block-start:168bo8 */}
      <DialogTrigger data-pv-block="168bo8" data-pv-sketchpad-el="168bo8"  style={{ position: 'absolute', left: 176, top: 126 }}>
        {/* pv-editable-zone-start:z2dpv9 */}
          {/* pv-block-start:3587v5 */}
          <DialogOverlay data-pv-block="3587v5">
            <DialogWindow size="md">
              {/* pv-editable-zone-start:5deq9o */}
              {/* pv-block-start:8gzmd9 */}
              <h2 data-pv-block="8gzmd9" className="text-xl font-semibold text-foreground-default mb-2">Dialog Title</h2>
              {/* pv-block-end:8gzmd9 */}
              {/* pv-block-start:vtip2c */}
              <p data-pv-block="vtip2c" className="text-foreground-secondary mb-6">This is the dialog content. Click the button below or press Escape to close.</p>
              {/* pv-block-end:vtip2c */}
              {/* pv-editable-zone-end:5deq9o */}
            </DialogWindow>
          </DialogOverlay>
          {/* pv-block-end:3587v5 */}
        {/* pv-editable-zone-end:z2dpv9 */}
      </DialogTrigger>
      {/* pv-block-end:168bo8 */}
      
      {/* pv-block-start:7pv2kq */}
      <DialogTrigger data-pv-block="7pv2kq" data-pv-sketchpad-el="7pv2kq"  style={{ position: 'absolute', left: 156, top: 229 }}>
        {/* pv-editable-zone-start:crk7zn */}
          {/* pv-block-start:357l4g */}
          <DialogOverlay data-pv-block="357l4g">
            <DialogWindow size="md">
              {/* pv-editable-zone-start:1feqrp */}
              {/* pv-block-start:9mqyve */}
              <h2 data-pv-block="9mqyve" className="text-xl font-semibold text-foreground-default mb-2">Dialog Title</h2>
              {/* pv-block-end:9mqyve */}
              {/* pv-block-start:dpksxs */}
              <p data-pv-block="dpksxs" className="text-foreground-secondary mb-6">This is the dialog content. Click the button below or press Escape to close.</p>
              {/* pv-block-end:dpksxs */}
              {/* pv-editable-zone-end:1feqrp */}
            </DialogWindow>
          </DialogOverlay>
          {/* pv-block-end:357l4g */}
        {/* pv-editable-zone-end:crk7zn */}
      </DialogTrigger>
      {/* pv-block-end:7pv2kq */}
      {/* pv-editable-zone-end:qmqv3i */}
    </div>
  );
}
