// Auto-generated by Protovibe Sketchpad
import { Card } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { DialogTrigger } from '@/components/ui/dialog-trigger';
import { DialogOverlay } from '@/components/ui/dialog-overlay';
import { DialogWindow } from '@/components/ui/dialog-window';

export default function Frame7() {
  return (
    <div style={{ width: '100%', height: '100%', position: 'relative' }}>
      {/* pv-editable-zone-start:ad2bkd */}
      {/* pv-block-start:hnrems */}
      <DialogWindow data-pv-block="hnrems" data-pv-sketchpad-el="hnrems"  style={{ position: 'absolute', left: 131, top: 226 }}>
        {/* pv-editable-zone-start:ygy99k */}
          {/* pv-block-start:5r4fl4 */}
          <h2 data-pv-block="5r4fl4" className="text-xl font-semibold text-foreground-default mb-2">Dialog Title</h2>
          {/* pv-block-end:5r4fl4 */}
          {/* pv-block-start:e66w00 */}
          <p data-pv-block="e66w00" className="text-foreground-secondary mb-6">This is the dialog content. Click the button below or press Escape to close.</p>
          {/* pv-block-end:e66w00 */}
          <div>
            {/* pv-editable-zone-start:k3h0rt */}
              {/* pv-block-start:82202o */}
              <p data-pv-block="82202o" className="text-foreground-secondary mb-6">This is additional editable content.</p>
              {/* pv-block-end:82202o */}
            {/* pv-editable-zone-end:k3h0rt */}
          </div>

        {/* pv-block-start:a6tsiq */}
      <Card data-pv-block="a6tsiq" variant="bordered" shadow="none" >
        {/* pv-editable-zone-start:c24xmv */}
        {/* pv-block-start:ndie1a */}
      <Button data-pv-block="ndie1a" label="Button" variant="solid" color="primary" size="md"  />
      {/* pv-block-end:ndie1a */}
        {/* pv-editable-zone-end:c24xmv */}
      </Card>
      {/* pv-block-end:a6tsiq */}

        {/* pv-block-start:9brwbc */}
      <DialogTrigger data-pv-block="9brwbc"  >
        {/* pv-editable-zone-start:7qs1zd */}
          {/* pv-block-start:n2ya98 */}
          <Button data-pv-block="n2ya98" label="Open Dialog" variant="solid" color="primary" size="md" />
          {/* pv-block-end:n2ya98 */}
          {/* pv-block-start:82yloh */}
          <DialogOverlay data-pv-block="82yloh">
            <DialogWindow size="md">
              {/* pv-editable-zone-start:8laltp */}
              {/* pv-block-start:9hdi66 */}
              <h2 data-pv-block="9hdi66" className="text-xl font-semibold text-foreground-default mb-2">Dialog Title</h2>
              {/* pv-block-end:9hdi66 */}
              {/* pv-block-start:n6qqqp */}
              <p data-pv-block="n6qqqp" className="text-foreground-secondary mb-6">This is the dialog content. Click the button below or press Escape to close.</p>
              {/* pv-block-end:n6qqqp */}
              {/* pv-editable-zone-end:8laltp */}
            </DialogWindow>
          </DialogOverlay>
          {/* pv-block-end:82yloh */}
        {/* pv-editable-zone-end:7qs1zd */}
      </DialogTrigger>
      {/* pv-block-end:9brwbc */}

        {/* pv-block-start:ic3176 */}
      <DialogTrigger data-pv-block="ic3176"  >
        {/* pv-editable-zone-start:p3jkol */}
          {/* pv-block-start:zlnd5u */}
          <DialogOverlay data-pv-block="zlnd5u">
            <DialogWindow size="md">
              {/* pv-editable-zone-start:9h1nol */}
              {/* pv-block-start:2xio2f */}
              <h2 data-pv-block="2xio2f" className="text-xl font-semibold text-foreground-default mb-2">Dialog Title</h2>
              {/* pv-block-end:2xio2f */}
              {/* pv-block-start:6job8y */}
              <p data-pv-block="6job8y" className="text-foreground-secondary mb-6">This is the dialog content. Click the button below or press Escape to close.</p>
              {/* pv-block-end:6job8y */}
              {/* pv-editable-zone-end:9h1nol */}
            </DialogWindow>
          </DialogOverlay>
          {/* pv-block-end:zlnd5u */}
        {/* pv-editable-zone-end:p3jkol */}
      </DialogTrigger>
      {/* pv-block-end:ic3176 */}
        {/* pv-editable-zone-end:ygy99k */}
      </DialogWindow>
      {/* pv-block-end:hnrems */}
      {/* pv-editable-zone-end:ad2bkd */}
    </div>
  );
}
