// Auto-generated by Protovibe Sketchpad

export default function Frame8() {
  return (
    <div style={{ width: '100%', height: '100%', position: 'relative' }}>
      {/* pv-editable-zone-start:3qxdrt */}
      {/* pv-editable-zone-end:3qxdrt */}
    </div>
  );
}
