// Auto-generated by Protovibe Sketchpad
import { Button } from '@/components/ui/button';
import { RadioGroup } from '@/components/ui/radio-group'
import { RadioItem } from '@/components/ui/radio-item'

export default function Frame2() {
  return (
    <div style={{ width: '100%', height: '100%', position: 'relative' }}>
      {/* pv-editable-zone-start:zb8lla */}
        {/* pv-block-start:o5mtmq */}
        <div className="flex flex-col min-h-4 p-5" data-pv-block="o5mtmq">
          {/* pv-editable-zone-start:inside-o5mtmq */}

          {/* pv-block-start:82m3f6 */}
        <RadioGroup data-pv-block="82m3f6" orientation="vertical" value="opt1">
          {/* pv-editable-zone-start:jjuwp8 */}
            {/* pv-block-start:55u5r3 */}
            <RadioItem data-pv-block="55u5r3" value="opt1" primaryText="Option One" secondaryText="Description for option one" />
            {/* pv-block-end:55u5r3 */}
            {/* pv-block-start:jnvh1c */}
            <RadioItem data-pv-block="jnvh1c" value="opt2" primaryText="Option Two" secondaryText="Description for option two" />
            {/* pv-block-end:jnvh1c */}
            {/* pv-block-start:4gdoyx */}
            <RadioItem data-pv-block="4gdoyx" value="opt3" primaryText="Option Three" disabled={true} secondaryText="Disabled option" />
            {/* pv-block-end:4gdoyx */}
          {/* pv-editable-zone-end:jjuwp8 */}
        </RadioGroup>
        {/* pv-block-end:82m3f6 */}
          {/* pv-editable-zone-end:inside-o5mtmq */}
        </div>
        {/* pv-block-end:o5mtmq */}
      {/* pv-editable-zone-end:zb8lla */}
    </div>
  );
}
