// Auto-generated by Protovibe Sketchpad
import { DialogTrigger } from '@/components/ui/dialog-trigger';
import { Button } from '@/components/ui/button';
import { DialogOverlay } from '@/components/ui/dialog-overlay';
import { DialogWindow } from '@/components/ui/dialog-window';
import { RadioGroup } from '@/components/ui/radio-group';
import { RadioItem } from '@/components/ui/radio-item';
import { SegmentedControl } from '@/components/ui/segmented-control';
import { SegmentedControlItem } from '@/components/ui/segmented-control-item';
import { VerticalTabs } from '@/components/ui/vertical-tabs';
import { VerticalTabItem } from '@/components/ui/vertical-tab-item';

export default function Frame4() {
  return (
    <div style={{ width: '100%', height: '100%', position: 'relative' }}>
      {/* pv-editable-zone-start:a96c1l */}
      
      {/* pv-block-start:7ji6da */}
      <DialogTrigger data-pv-block="7ji6da" data-pv-sketchpad-el="7ji6da"  style={{ position: 'absolute', left: 330, top: 228 }}>
        {/* pv-editable-zone-start:bnwczl */}
          {/* pv-block-start:ju2di7 */}
          <Button data-pv-block="ju2di7" label="Open Dialog" variant="solid" color="primary" size="md" />
          {/* pv-block-end:ju2di7 */}
          {/* pv-block-start:fnboou */}
          <DialogOverlay data-pv-block="fnboou">
            <DialogWindow size="md">
              {/* pv-editable-zone-start:pw7aj4 */}
              {/* pv-block-start:28qk5r */}
              <h2 data-pv-block="28qk5r" className="text-xl font-semibold text-foreground-default mb-2">Dialog Title</h2>
              {/* pv-block-end:28qk5r */}
              {/* pv-block-start:6v7b2z */}
              <p data-pv-block="6v7b2z" className="text-foreground-secondary mb-6">This is the dialog content. Click the button below or press Escape to close.</p>
              {/* pv-block-end:6v7b2z */}
              {/* pv-editable-zone-end:pw7aj4 */}
            </DialogWindow>
          </DialogOverlay>
          {/* pv-block-end:fnboou */}
        {/* pv-editable-zone-end:bnwczl */}
      </DialogTrigger>
      {/* pv-block-end:7ji6da */}
      
      {/* pv-block-start:z7mdml */}
      <DialogTrigger data-pv-block="z7mdml" data-pv-sketchpad-el="z7mdml"  style={{ position: 'absolute', left: 171, top: 214 }}>
        {/* pv-editable-zone-start:pemejx */}
          {/* pv-block-start:89xft2 */}
          <Button data-pv-block="89xft2" label="Open Dialog" variant="solid" color="primary" size="md" />
          {/* pv-block-end:89xft2 */}
          {/* pv-block-start:t2wd64 */}
          <DialogOverlay data-pv-block="t2wd64">
            <DialogWindow size="md">
              {/* pv-editable-zone-start:5pzmd5 */}
              {/* pv-block-start:utykok */}
              <h2 data-pv-block="utykok" className="text-xl font-semibold text-foreground-default mb-2">Dialog Title</h2>
              {/* pv-block-end:utykok */}
              {/* pv-block-start:e984at */}
              <p data-pv-block="e984at" className="text-foreground-secondary mb-6">This is the dialog content. Click the button below or press Escape to close.</p>
              {/* pv-block-end:e984at */}
              {/* pv-editable-zone-end:5pzmd5 */}
            </DialogWindow>
          </DialogOverlay>
          {/* pv-block-end:t2wd64 */}
        {/* pv-editable-zone-end:pemejx */}
      </DialogTrigger>
      {/* pv-block-end:z7mdml */}
      
      {/* pv-block-start:ntddhh */}
      <DialogTrigger data-pv-block="ntddhh" data-pv-sketchpad-el="ntddhh"  style={{ position: 'absolute', left: 72, top: 128 }}>
        {/* pv-editable-zone-start:ns2njv */}
          {/* pv-block-start:1mk58n */}
          <DialogOverlay data-pv-block="1mk58n">
            <DialogWindow size="md">
              {/* pv-editable-zone-start:89qsqn */}
              {/* pv-block-start:ljqnvs */}
              <h2 data-pv-block="ljqnvs" className="text-xl font-semibold text-foreground-default mb-2">Dialog Title</h2>
              {/* pv-block-end:ljqnvs */}
              {/* pv-block-start:n63udy */}
              <p data-pv-block="n63udy" className="text-foreground-secondary mb-6">This is the dialog content. Click the button below or press Escape to close.</p>
              {/* pv-block-end:n63udy */}
              {/* pv-editable-zone-end:89qsqn */}
            </DialogWindow>
          </DialogOverlay>
          {/* pv-block-end:1mk58n */}
        {/* pv-editable-zone-end:ns2njv */}
      </DialogTrigger>
      {/* pv-block-end:ntddhh */}
      
      {/* pv-block-start:g117pr */}
      <DialogWindow data-pv-block="g117pr" data-pv-sketchpad-el="g117pr"  style={{ position: 'absolute', left: 247, top: 425 }}>
        {/* pv-editable-zone-start:wyd1mh */}
          {/* pv-block-start:sctwe8 */}
          <h2 data-pv-block="sctwe8" className="text-xl font-semibold text-foreground-default mb-2">Dialog Title</h2>
          {/* pv-block-end:sctwe8 */}
          {/* pv-block-start:q8r5ry */}
          <p data-pv-block="q8r5ry" className="text-foreground-secondary mb-6">This is the dialog content. Click the button below or press Escape to close.</p>
          {/* pv-block-end:q8r5ry */}
          <div>
            {/* pv-editable-zone-start:7fzip8 */}
              {/* pv-block-start:8i10si */}
              <p data-pv-block="8i10si" className="text-foreground-secondary mb-6">This is additional editable content.</p>
              {/* pv-block-end:8i10si */}
            {/* pv-editable-zone-end:7fzip8 */}
          </div>
        {/* pv-editable-zone-end:wyd1mh */}
      </DialogWindow>
      {/* pv-block-end:g117pr */}
      
      {/* pv-block-start:twgbou */}
      <DialogWindow data-pv-block="twgbou" data-pv-sketchpad-el="twgbou"  style={{ position: 'absolute', left: 486, top: 125 }}>
        {/* pv-editable-zone-start:rdfy45 */}
          {/* pv-block-start:wogbnt */}
          <h2 data-pv-block="wogbnt" className="text-xl font-semibold text-foreground-default mb-2">Dialog Title</h2>
          {/* pv-block-end:wogbnt */}
          {/* pv-block-start:o6ikrx */}
          <p data-pv-block="o6ikrx" className="text-foreground-secondary mb-6">This is the dialog content. Click the button below or press Escape to close.</p>
          {/* pv-block-end:o6ikrx */}
          <div>
            {/* pv-editable-zone-start:7xvg7w */}
              {/* pv-block-start:8ahl7c */}
              <p data-pv-block="8ahl7c" className="text-foreground-secondary mb-6">This is additional editable content.</p>
              {/* pv-block-end:8ahl7c */}
            {/* pv-editable-zone-end:7xvg7w */}
          </div>
        {/* pv-editable-zone-end:rdfy45 */}
      </DialogWindow>
      {/* pv-block-end:twgbou */}
      
      {/* pv-block-start:2tul0e */}
      <RadioGroup data-pv-block="2tul0e" data-pv-sketchpad-el="2tul0e" orientation="vertical" value="opt1" style={{ position: 'absolute', left: 296, top: 54 }}>
        {/* pv-editable-zone-start:6fc7m1 */}
          {/* pv-block-start:r69132 */}
          <RadioItem data-pv-block="r69132" value="opt1" primaryText="Option One" secondaryText="Description for option one" />
          {/* pv-block-end:r69132 */}
          {/* pv-block-start:d02wii */}
          <RadioItem data-pv-block="d02wii" value="opt2" primaryText="Option Two" secondaryText="Description for option two" />
          {/* pv-block-end:d02wii */}
          {/* pv-block-start:81i5pd */}
          <RadioItem data-pv-block="81i5pd" value="opt3" primaryText="Option Three" secondaryText="Third option" />
          {/* pv-block-end:81i5pd */}
        {/* pv-editable-zone-end:6fc7m1 */}
      </RadioGroup>
      {/* pv-block-end:2tul0e */}
      
      {/* pv-block-start:b23w64 */}
      <SegmentedControl data-pv-block="b23w64" data-pv-sketchpad-el="b23w64" value="opt1" style={{ position: 'absolute', left: 37, top: 313 }}>
        {/* pv-editable-zone-start:klmbul */}
          {/* pv-block-start:das0sq */}
          <SegmentedControlItem data-pv-block="das0sq" label="Option 1" value="opt1" />
          {/* pv-block-end:das0sq */}
          {/* pv-block-start:bbks7u */}
          <SegmentedControlItem data-pv-block="bbks7u" label="Option 2" value="opt2" />
          {/* pv-block-end:bbks7u */}
          {/* pv-block-start:r8qax9 */}
          <SegmentedControlItem data-pv-block="r8qax9" label="Option 3" value="opt3" />
          {/* pv-block-end:r8qax9 */}
        {/* pv-editable-zone-end:klmbul */}
      </SegmentedControl>
      {/* pv-block-end:b23w64 */}
      
      {/* pv-block-start:bjb82l */}
      <VerticalTabs data-pv-block="bjb82l" data-pv-sketchpad-el="bjb82l" value="tab1" style={{ position: 'absolute', width: 211, left: 46, top: 378 }}>
        {/* pv-editable-zone-start:7bwnuk */}
          {/* pv-block-start:73dm1h */}
          <VerticalTabItem data-pv-block="73dm1h" label="Dashboard" value="tab1" prefixIcon="LayoutDashboard">
            {/* pv-editable-zone-start:8r39ta */}
            {/* pv-editable-zone-end:8r39ta */}
          </VerticalTabItem>
          {/* pv-block-end:73dm1h */}
          {/* pv-block-start:do03di */}
          <VerticalTabItem data-pv-block="do03di" label="Analytics" value="tab2" prefixIcon="BarChart2">
            {/* pv-editable-zone-start:k6qqek */}
            {/* pv-editable-zone-end:k6qqek */}
          </VerticalTabItem>
          {/* pv-block-end:do03di */}
          {/* pv-block-start:54nhlr */}
          <VerticalTabItem data-pv-block="54nhlr" label="Settings" value="tab3" prefixIcon="Settings">
            {/* pv-editable-zone-start:3ua92g */}
            {/* pv-editable-zone-end:3ua92g */}
          </VerticalTabItem>
          {/* pv-block-end:54nhlr */}
        {/* pv-editable-zone-end:7bwnuk */}
      </VerticalTabs>
      {/* pv-block-end:bjb82l */}
      
      {/* pv-block-start:m9te0j */}
      <Button className="bg-background-secondary" data-pv-block="m9te0j" data-pv-sketchpad-el="m9te0j" label="Button" variant="solid" color="primary" size="md" style={{ position: 'absolute', left: 48, top: 50, width: 172 }} />
      {/* pv-block-end:m9te0j */}
            {/* pv-editable-zone-end:a96c1l */}
    </div>
  );
}
