// Auto-generated by Protovibe Sketchpad
import { Card } from '@/components/ui/card';
import { RadioGroup } from '@/components/ui/radio-group';
import { RadioItem } from '@/components/ui/radio-item';
import { DialogTrigger } from '@/components/ui/dialog-trigger';
import { Button } from '@/components/ui/button';
import { DialogOverlay } from '@/components/ui/dialog-overlay';
import { DialogWindow } from '@/components/ui/dialog-window';

export default function Frame3() {
  return (
    <div data-layout-mode="absolute" style={{ width: '100%', height: '100%', position: 'relative' }}>
      {/* pv-editable-zone-start:bcg8bz */}
      {/* pv-block-start:md6v4z */}
      <Card data-pv-block="md6v4z" data-pv-sketchpad-el="md6v4z" variant="bordered" shadow="none" style={{ position: 'absolute', width: 239, left: 124, top: 83 }}>
        {/* pv-editable-zone-start:smt3d9 */}
        {/* pv-block-start:now9y8 */}
      <DialogTrigger data-pv-block="now9y8"  >
        {/* pv-editable-zone-start:r8fg6t */}
          {/* pv-block-start:lg9978 */}
          <Button data-pv-block="lg9978" label="Open Dialog" variant="solid" color="primary" size="md" />
          {/* pv-block-end:lg9978 */}
          {/* pv-block-start:ulcw9o */}
          <DialogOverlay data-pv-block="ulcw9o">
            <DialogWindow size="md">
              {/* pv-editable-zone-start:u9ohml */}
              {/* pv-block-start:ycjwg1 */}
              <h2 data-pv-block="ycjwg1" className="text-xl font-semibold text-foreground-default mb-2">Dialog Title</h2>
              {/* pv-block-end:ycjwg1 */}
              {/* pv-block-start:kej9fs */}
              <p data-pv-block="kej9fs" className="text-foreground-secondary mb-6">This is the dialog content. Click the button below or press Escape to close.</p>
              {/* pv-block-end:kej9fs */}
              {/* pv-editable-zone-end:u9ohml */}
            </DialogWindow>
          </DialogOverlay>
          {/* pv-block-end:ulcw9o */}
        {/* pv-editable-zone-end:r8fg6t */}
      </DialogTrigger>
      {/* pv-block-end:now9y8 */}

        {/* pv-block-start:632fb3 */}
      <Card data-pv-block="632fb3" variant="bordered" shadow="none" >
        {/* pv-editable-zone-start:4dvg10 */}
        {/* pv-block-start:7qwmzb */}
      <RadioGroup data-pv-block="7qwmzb" orientation="vertical" value="opt1" >
        {/* pv-editable-zone-start:le66pi */}
          {/* pv-block-start:l1tu8x */}
          <RadioItem data-pv-block="l1tu8x" value="opt1" primaryText="Option One" secondaryText="Description for option one" />
          {/* pv-block-end:l1tu8x */}
          {/* pv-block-start:4trqoe */}
          <RadioItem data-pv-block="4trqoe" value="opt2" primaryText="Option Two" secondaryText="Description for option two" />
          {/* pv-block-end:4trqoe */}
          {/* pv-block-start:tq952x */}
          <RadioItem data-pv-block="tq952x" value="opt3" primaryText="Option Three" secondaryText="Third option" />
          {/* pv-block-end:tq952x */}
        {/* pv-editable-zone-end:le66pi */}
      </RadioGroup>
      {/* pv-block-end:7qwmzb */}
        {/* pv-editable-zone-end:4dvg10 */}
      </Card>
      {/* pv-block-end:632fb3 */}
        {/* pv-editable-zone-end:smt3d9 */}
      </Card>
      {/* pv-block-end:md6v4z */}
      
      {/* pv-block-start:zlpzm3 */}
      <Card data-pv-block="zlpzm3" data-pv-sketchpad-el="zlpzm3" variant="bordered" shadow="none" style={{ position: 'absolute', left: 426, top: 80 }}>
        {/* pv-editable-zone-start:pucms9 */}
        {/* pv-block-start:x01dvh */}
      <DialogTrigger data-pv-block="x01dvh"  >
        {/* pv-editable-zone-start:0qc45c */}
          {/* pv-block-start:pxl6zn */}
          <Button data-pv-block="pxl6zn" label="Open Dialog" variant="solid" color="primary" size="md" />
          {/* pv-block-end:pxl6zn */}
          {/* pv-block-start:48tn8v */}
          <DialogOverlay data-pv-block="48tn8v">
            <DialogWindow size="md">
              {/* pv-editable-zone-start:wlup44 */}
              {/* pv-block-start:kcn1ri */}
              <h2 data-pv-block="kcn1ri" className="text-xl font-semibold text-foreground-default mb-2">Dialog Title</h2>
              {/* pv-block-end:kcn1ri */}
              {/* pv-block-start:2dc89m */}
              <p data-pv-block="2dc89m" className="text-foreground-secondary mb-6">This is the dialog content. Click the button below or press Escape to close.</p>
              {/* pv-block-end:2dc89m */}
              {/* pv-editable-zone-end:wlup44 */}
            </DialogWindow>
          </DialogOverlay>
          {/* pv-block-end:48tn8v */}
        {/* pv-editable-zone-end:0qc45c */}
      </DialogTrigger>
      {/* pv-block-end:x01dvh */}

        {/* pv-block-start:jxrqso */}
      <RadioGroup data-pv-block="jxrqso" orientation="vertical" value="opt1" >
        {/* pv-editable-zone-start:tzgeto */}
          {/* pv-block-start:kcs3c4 */}
          <RadioItem data-pv-block="kcs3c4" value="opt1" primaryText="Option One" secondaryText="Description for option one" />
          {/* pv-block-end:kcs3c4 */}
          {/* pv-block-start:g6j0zg */}
          <RadioItem data-pv-block="g6j0zg" value="opt2" primaryText="Option Two" secondaryText="Description for option two" />
          {/* pv-block-end:g6j0zg */}
          {/* pv-block-start:xjn0un */}
          <RadioItem data-pv-block="xjn0un" value="opt3" primaryText="Option Three" secondaryText="Third option" />
          {/* pv-block-end:xjn0un */}
        {/* pv-editable-zone-end:tzgeto */}
      </RadioGroup>
      {/* pv-block-end:jxrqso */}

        {/* pv-block-start:v4pmkp */}
      <DialogTrigger data-pv-block="v4pmkp"  >
        {/* pv-editable-zone-start:nyx8kd */}
          {/* pv-block-start:lg27lt */}
          <Button data-pv-block="lg27lt" label="Open Dialog" variant="solid" color="primary" size="md" />
          {/* pv-block-end:lg27lt */}
          {/* pv-block-start:8446ow */}
          <DialogOverlay data-pv-block="8446ow">
            <DialogWindow size="md">
              {/* pv-editable-zone-start:4yw9rp */}
              {/* pv-block-start:b6xskn */}
              <h2 data-pv-block="b6xskn" className="text-xl font-semibold text-foreground-default mb-2">Dialog Title</h2>
              {/* pv-block-end:b6xskn */}
              {/* pv-block-start:xc0qtp */}
              <p data-pv-block="xc0qtp" className="text-foreground-secondary mb-6">This is the dialog content. Click the button below or press Escape to close.</p>
              {/* pv-block-end:xc0qtp */}
              {/* pv-editable-zone-end:4yw9rp */}
            </DialogWindow>
          </DialogOverlay>
          {/* pv-block-end:8446ow */}
        {/* pv-editable-zone-end:nyx8kd */}
      </DialogTrigger>
      {/* pv-block-end:v4pmkp */}

        {/* pv-block-start:mqj498 */}
      <DialogTrigger data-pv-block="mqj498"  >
        {/* pv-editable-zone-start:nyx8kd */}
          {/* pv-block-start:dpl758 */}
          <Button data-pv-block="dpl758" label="Open Dialog" variant="solid" color="primary" size="md" />
          {/* pv-block-end:dpl758 */}
          {/* pv-block-start:7n3uiv */}
          <DialogOverlay data-pv-block="7n3uiv">
            <DialogWindow size="md">
              {/* pv-editable-zone-start:4yw9rp */}
              {/* pv-block-start:4hy1rz */}
              <h2 data-pv-block="4hy1rz" className="text-xl font-semibold text-foreground-default mb-2">Dialog Title</h2>
              {/* pv-block-end:4hy1rz */}
              {/* pv-block-start:9bgo8n */}
              <p data-pv-block="9bgo8n" className="text-foreground-secondary mb-6">This is the dialog content. Click the button below or press Escape to close.</p>
              {/* pv-block-end:9bgo8n */}
              {/* pv-editable-zone-end:4yw9rp */}
            </DialogWindow>
          </DialogOverlay>
          {/* pv-block-end:7n3uiv */}
        {/* pv-editable-zone-end:nyx8kd */}
      </DialogTrigger>
      {/* pv-block-end:mqj498 */}
        {/* pv-editable-zone-end:pucms9 */}
      </Card>
      {/* pv-block-end:zlpzm3 */}
      {/* pv-editable-zone-end:bcg8bz */}
    </div>
  );
}
