// Auto-generated by Protovibe Sketchpad
import { DialogTrigger } from '@/components/ui/dialog-trigger';
import { Button } from '@/components/ui/button';
import { DialogOverlay } from '@/components/ui/dialog-overlay';
import { DialogWindow } from '@/components/ui/dialog-window';
import { Card } from '@/components/ui/card'
import { RadioGroup } from '@/components/ui/radio-group';
import { RadioItem } from '@/components/ui/radio-item';

export default function Frame2() {
  return (
    <div data-layout-mode="absolute" style={{ width: '100%', height: '100%', position: 'relative' }}>
      {/* pv-editable-zone-start:0zel3z */}
      {/* pv-block-start:3xxs7r */}
          <Card className="flex justify-center flex-col items-start self-start shrink pr-10" data-pv-block="3xxs7r" variant="bordered" shadow="none" data-pv-sketchpad-el="3xxs7r" style={{ position: 'absolute', width: 563, left: 62, top: 58 }}>
            {/* pv-editable-zone-start:c1cn2h */}
            {/* pv-block-start:mxnmct */}
          <Button data-pv-block="mxnmct" label="Button" variant="solid" color="primary" size="md" />
          {/* pv-block-end:mxnmct */}

            {/* pv-block-start:e0qjph */}
          <Button data-pv-block="e0qjph" label="Button" variant="solid" color="primary" size="md" />
          {/* pv-block-end:e0qjph */}

            {/* pv-block-start:v2ncfi */}
      <DialogTrigger data-pv-block="v2ncfi"  >
        {/* pv-editable-zone-start:63nn1v */}
          {/* pv-block-start:ovj9fr */}
          <Button data-pv-block="ovj9fr" label="Open Dialog" variant="solid" color="primary" size="md" />
          {/* pv-block-end:ovj9fr */}
          {/* pv-block-start:hx6v3w */}
          <DialogOverlay data-pv-block="hx6v3w">
            <DialogWindow size="md">
              {/* pv-editable-zone-start:sux7bu */}
              {/* pv-block-start:zbee2y */}
              <h2 data-pv-block="zbee2y" className="text-xl font-semibold text-foreground-default mb-2">Dialog Title</h2>
              {/* pv-block-end:zbee2y */}
              {/* pv-block-start:26smhi */}
              <p data-pv-block="26smhi" className="text-foreground-secondary mb-6">This is the dialog content. Click the button below or press Escape to close.</p>
              {/* pv-block-end:26smhi */}
              {/* pv-editable-zone-end:sux7bu */}
            </DialogWindow>
          </DialogOverlay>
          {/* pv-block-end:hx6v3w */}
        {/* pv-editable-zone-end:63nn1v */}
      </DialogTrigger>
      {/* pv-block-end:v2ncfi */}

            {/* pv-block-start:tmwkw7 */}
      <DialogTrigger data-pv-block="tmwkw7"   data-pv-sketchpad-el="tmwkw7" style={{ position: 'absolute', left: 127, top: 411 }}>
        {/* pv-editable-zone-start:z19ouz */}
          {/* pv-block-start:3jc6mp */}
          <Button data-pv-block="3jc6mp" label="Open Dialog" variant="solid" color="primary" size="md" />
          {/* pv-block-end:3jc6mp */}
          {/* pv-block-start:4q64q4 */}
          <DialogOverlay data-pv-block="4q64q4">
            <DialogWindow size="md">
              {/* pv-editable-zone-start:02xey8 */}
              {/* pv-block-start:elsk1h */}
              <h2 data-pv-block="elsk1h" className="text-xl font-semibold text-foreground-default mb-2">Dialog Title</h2>
              {/* pv-block-end:elsk1h */}
              {/* pv-block-start:hyvfli */}
              <p data-pv-block="hyvfli" className="text-foreground-secondary mb-6">This is the dialog content. Click the button below or press Escape to close.</p>
              {/* pv-block-end:hyvfli */}
              {/* pv-editable-zone-end:02xey8 */}
            </DialogWindow>
          </DialogOverlay>
          {/* pv-block-end:4q64q4 */}
        {/* pv-editable-zone-end:z19ouz */}
      </DialogTrigger>
      {/* pv-block-end:tmwkw7 */}

            {/* pv-block-start:q4ba8s */}
      <Card data-pv-block="q4ba8s" variant="bordered" shadow="none" >
        {/* pv-editable-zone-start:fjfs74 */}
        {/* pv-block-start:nldi14 */}
          <Button data-pv-block="nldi14" label="Button" variant="solid" color="primary" size="md" />
          {/* pv-block-end:nldi14 */}
        {/* pv-editable-zone-end:fjfs74 */}
      </Card>
      {/* pv-block-end:q4ba8s */}
            {/* pv-editable-zone-end:c1cn2h */}
          </Card>
          {/* pv-block-end:3xxs7r */}

      {/* pv-block-start:195pu0 */}
          <Button data-pv-block="195pu0" label="Open Dialog" variant="solid" color="primary" size="md"  data-pv-sketchpad-el="195pu0" style={{ position: 'absolute', left: 471, top: 420 }}/>
          {/* pv-block-end:195pu0 */}

      {/* pv-block-start:lrt7qh */}
      <DialogTrigger data-pv-block="lrt7qh"   data-pv-sketchpad-el="lrt7qh" style={{ position: 'absolute', left: 54, top: 443 }}>
        {/* pv-editable-zone-start:z19ouz */}
          {/* pv-block-start:vgql6t */}
          <Button data-pv-block="vgql6t" label="Open Dialog" variant="solid" color="primary" size="md" />
          {/* pv-block-end:vgql6t */}
          {/* pv-block-start:cnkjqr */}
          <DialogOverlay data-pv-block="cnkjqr">
            <DialogWindow size="md">
              {/* pv-editable-zone-start:02xey8 */}
              {/* pv-block-start:ud39t0 */}
              <h2 data-pv-block="ud39t0" className="text-xl font-semibold text-foreground-default mb-2">Dialog Title</h2>
              {/* pv-block-end:ud39t0 */}
              {/* pv-block-start:4i6opv */}
              <p data-pv-block="4i6opv" className="text-foreground-secondary mb-6">This is the dialog content. Click the button below or press Escape to close.</p>
              {/* pv-block-end:4i6opv */}
              {/* pv-editable-zone-end:02xey8 */}
            </DialogWindow>
          </DialogOverlay>
          {/* pv-block-end:cnkjqr */}
        {/* pv-editable-zone-end:z19ouz */}
      </DialogTrigger>
      {/* pv-block-end:lrt7qh */}
            {/* pv-editable-zone-end:0zel3z */}
    </div>
  );
}
