import { DialogTrigger } from '@/components/ui/dialog-trigger'
import { Button } from '@/components/ui/button'
import { DialogOverlay } from '@/components/ui/dialog-overlay'
import { DialogWindow } from '@/components/ui/dialog-window'
import { Card } from '@/components/ui/card';
import { RadioGroup } from '@/components/ui/radio-group'
import { RadioItem } from '@/components/ui/radio-item'
// Auto-generated by Protovibe Sketchpad

export default function Frame1() {
  return (
    <div data-layout-mode="absolute" style={{ width: '100%', height: '100%', position: 'relative' }}>
      {/* pv-editable-zone-start:fzhckc */}
      {/* pv-block-start:opc0u2 */}
      <Card data-pv-block="opc0u2" data-pv-sketchpad-el="opc0u2" variant="bordered" shadow="none" style={{ position: 'absolute', width: 203, left: 520, top: 42 }}>
        {/* pv-editable-zone-start:t57su3 */}
        {/* pv-block-start:4ndiup */}
      <DialogTrigger data-pv-block="4ndiup"  >
        {/* pv-editable-zone-start:dedwi5 */}
          {/* pv-block-start:7ymeuq */}
          <Button data-pv-block="7ymeuq" label="Open Dialog" variant="solid" color="primary" size="md" />
          {/* pv-block-end:7ymeuq */}
          {/* pv-block-start:rsldd9 */}
          <DialogOverlay data-pv-block="rsldd9">
            <DialogWindow size="md">
              {/* pv-editable-zone-start:jwqdqp */}
              {/* pv-block-start:0nur2a */}
              <h2 data-pv-block="0nur2a" className="text-xl font-semibold text-foreground-default mb-2">Dialog Title</h2>
              {/* pv-block-end:0nur2a */}
              {/* pv-block-start:zqxgsh */}
              <p data-pv-block="zqxgsh" className="text-foreground-secondary mb-6">This is the dialog content. Click the button below or press Escape to close.</p>
              {/* pv-block-end:zqxgsh */}
              {/* pv-editable-zone-end:jwqdqp */}
            </DialogWindow>
          </DialogOverlay>
          {/* pv-block-end:rsldd9 */}
        {/* pv-editable-zone-end:dedwi5 */}
      </DialogTrigger>
      {/* pv-block-end:4ndiup */}

        {/* pv-block-start:g923if */}
      <DialogTrigger data-pv-block="g923if"  >
        {/* pv-editable-zone-start:4t5v6o */}
          {/* pv-block-start:k1kd6j */}
          <Button data-pv-block="k1kd6j" label="Open Dialog" variant="solid" color="primary" size="md" />
          {/* pv-block-end:k1kd6j */}
          {/* pv-block-start:tal7k3 */}
          <DialogOverlay data-pv-block="tal7k3">
            <DialogWindow size="md">
              {/* pv-editable-zone-start:r7xm1z */}
              {/* pv-block-start:gmhqgr */}
              <h2 data-pv-block="gmhqgr" className="text-xl font-semibold text-foreground-default mb-2">Dialog Title</h2>
              {/* pv-block-end:gmhqgr */}
              {/* pv-block-start:ecwbbb */}
              <p data-pv-block="ecwbbb" className="text-foreground-secondary mb-6">This is the dialog content. Click the button below or press Escape to close.</p>
              {/* pv-block-end:ecwbbb */}
              {/* pv-editable-zone-end:r7xm1z */}
            </DialogWindow>
          </DialogOverlay>
          {/* pv-block-end:tal7k3 */}
        {/* pv-editable-zone-end:4t5v6o */}
      </DialogTrigger>
      {/* pv-block-end:g923if */}

        {/* pv-block-start:w10e6i */}
      <RadioGroup data-pv-block="w10e6i" orientation="vertical" value="opt1" >
        {/* pv-editable-zone-start:tzgeto */}
          {/* pv-block-start:1avgq4 */}
          <RadioItem data-pv-block="1avgq4" value="opt1" primaryText="Option One" secondaryText="Description for option one" />
          {/* pv-block-end:1avgq4 */}
          {/* pv-block-start:oie32i */}
          <RadioItem data-pv-block="oie32i" value="opt2" primaryText="Option Two" secondaryText="Description for option two" />
          {/* pv-block-end:oie32i */}
          {/* pv-block-start:xs3bnx */}
          <RadioItem data-pv-block="xs3bnx" value="opt3" primaryText="Option Three" secondaryText="Third option" />
          {/* pv-block-end:xs3bnx */}
        {/* pv-editable-zone-end:tzgeto */}
      </RadioGroup>
      {/* pv-block-end:w10e6i */}

        {/* pv-block-start:nujnh1 */}
      <Card data-pv-block="nujnh1" variant="bordered" shadow="none" >
        {/* pv-editable-zone-start:fjfs74 */}
        {/* pv-block-start:jri5c5 */}
          <Button data-pv-block="jri5c5" label="Button" variant="solid" color="primary" size="md" />
          {/* pv-block-end:jri5c5 */}
        {/* pv-editable-zone-end:fjfs74 */}
      </Card>
      {/* pv-block-end:nujnh1 */}
        {/* pv-editable-zone-end:t57su3 */}
      </Card>
      {/* pv-block-end:opc0u2 */}
      
      {/* pv-block-start:17s6v5 */}
      <Card data-pv-block="17s6v5" data-pv-sketchpad-el="17s6v5" variant="bordered" shadow="none" style={{ position: 'absolute', width: 192, left: 120, top: 110 }}>
        {/* pv-editable-zone-start:jeo10g */}
        {/* pv-editable-zone-end:jeo10g */}
      </Card>
      {/* pv-block-end:17s6v5 */}
      
      {/* pv-block-start:mjmhb5 */}
      <Card data-pv-block="mjmhb5" data-pv-sketchpad-el="mjmhb5" variant="bordered" shadow="none" style={{ position: 'absolute', width: 340, left: 89, top: 353 }}>
        {/* pv-editable-zone-start:5h15xo */}

        {/* pv-block-start:lxrdhc */}
      <DialogTrigger data-pv-block="lxrdhc"  >
        {/* pv-editable-zone-start:7yngvo */}
          {/* pv-block-start:f9wmoe */}
          <Button data-pv-block="f9wmoe" label="Open Dialog" variant="solid" color="primary" size="md" />
          {/* pv-block-end:f9wmoe */}
          {/* pv-block-start:vxtscm */}
          <DialogOverlay data-pv-block="vxtscm">
            <DialogWindow size="md">
              {/* pv-editable-zone-start:ciwcgw */}
              {/* pv-block-start:kcgma8 */}
              <h2 data-pv-block="kcgma8" className="text-xl font-semibold text-foreground-default mb-2">Dialog Title</h2>
              {/* pv-block-end:kcgma8 */}
              {/* pv-block-start:iy05ao */}
              <p data-pv-block="iy05ao" className="text-foreground-secondary mb-6">This is the dialog content. Click the button below or press Escape to close.</p>
              {/* pv-block-end:iy05ao */}
              {/* pv-editable-zone-end:ciwcgw */}
            </DialogWindow>
          </DialogOverlay>
          {/* pv-block-end:vxtscm */}
        {/* pv-editable-zone-end:7yngvo */}
      </DialogTrigger>
      {/* pv-block-end:lxrdhc */}
        {/* pv-editable-zone-end:5h15xo */}
      </Card>
      {/* pv-block-end:mjmhb5 */}
      {/* pv-editable-zone-end:fzhckc */}
    </div>
  );
}
