// Auto-generated by Protovibe Sketchpad
import { Card } from '@/components/ui/card';
import { RadioGroup } from '@/components/ui/radio-group';
import { RadioItem } from '@/components/ui/radio-item';
import { DialogTrigger } from '@/components/ui/dialog-trigger';
import { Button } from '@/components/ui/button';
import { DialogOverlay } from '@/components/ui/dialog-overlay';
import { DialogWindow } from '@/components/ui/dialog-window';

export default function Frame3() {
  return (
    <div data-layout-mode="absolute" style={{ width: '100%', height: '100%', position: 'relative' }}>
      {/* pv-editable-zone-start:bcg8bz */}
      {/* pv-block-start:0jpa46 */}
      <Card data-pv-block="0jpa46" data-pv-sketchpad-el="0jpa46" variant="bordered" shadow="none" style={{ position: 'absolute', left: 107, top: 55 }}>
        {/* pv-editable-zone-start:4dvg10 */}
        {/* pv-block-start:qrz4rv */}
      <RadioGroup data-pv-block="qrz4rv" orientation="vertical" value="opt1" >
        {/* pv-editable-zone-start:le66pi */}
          {/* pv-block-start:1kvmy9 */}
          <RadioItem data-pv-block="1kvmy9" value="opt1" primaryText="Option One" secondaryText="Description for option one" />
          {/* pv-block-end:1kvmy9 */}
          {/* pv-block-start:2eqg3z */}
          <RadioItem data-pv-block="2eqg3z" value="opt2" primaryText="Option Two" secondaryText="Description for option two" />
          {/* pv-block-end:2eqg3z */}
          {/* pv-block-start:7yt4nw */}
          <RadioItem data-pv-block="7yt4nw" value="opt3" primaryText="Option Three" secondaryText="Third option" />
          {/* pv-block-end:7yt4nw */}
        {/* pv-editable-zone-end:le66pi */}
      </RadioGroup>
      {/* pv-block-end:qrz4rv */}
        {/* pv-editable-zone-end:4dvg10 */}
      </Card>
      {/* pv-block-end:0jpa46 */}

      {/* pv-block-start:md6v4z */}
      <Card data-pv-block="md6v4z" data-pv-sketchpad-el="md6v4z" variant="bordered" shadow="none" style={{ position: 'absolute', width: 239, left: 420, top: 111 }}>
        {/* pv-editable-zone-start:smt3d9 */}
        {/* pv-editable-zone-end:smt3d9 */}
      </Card>
      {/* pv-block-end:md6v4z */}
      {/* pv-editable-zone-end:bcg8bz */}
    </div>
  );
}
