import { Rectangle } from '@/components/ui/sketchpad-rectangle'
import { Card } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
// Auto-generated by Protovibe Sketchpad

export default function Frame3() {
  return (
    <div data-layout-mode="absolute" style={{ width: '100%', height: '100%', position: 'relative' }}>
      {/* pv-editable-zone-start:ia82r5 */}
        {/* pv-block-start:e3dgif */}
        <Rectangle data-pv-block="e3dgif" data-pv-sketchpad-el="e3dgif" style={{ position: 'absolute', height: 285, left: 127, top: 424, width: 458 }} className="w-[200px] h-[200px]">
          {/* pv-editable-zone-start:i1t9r5 */}
            {/* pv-block-start:0mqx7n */}
            <Card data-pv-block="0mqx7n"  data-pv-sketchpad-el="0mqx7n" style={{ position: 'absolute', left: 306, top: 14 }}>
              {/* pv-editable-zone-start:d3pro3 */}
                {/* pv-block-start:ojwaf5 */}
                <Badge data-pv-block="ojwaf5"  label="Badge" color="primary" />
                {/* pv-block-end:ojwaf5 */}
            
                {/* pv-block-start:579cu1 */}
                <Badge data-pv-block="579cu1"  label="Badge" color="primary" />
                {/* pv-block-end:579cu1 */}
              {/* pv-editable-zone-end:d3pro3 */}
            </Card>
            {/* pv-block-end:0mqx7n */}
            
            {/* pv-block-start:dri7at */}
            <Button data-pv-block="dri7at"  label="Button" variant="solid" color="primary" size="md"  data-pv-sketchpad-el="dri7at" style={{ position: 'absolute', left: 36, top: 27 }}/>
            {/* pv-block-end:dri7at */}
            {/* pv-block-start:i2bc1h */}
            <Card data-pv-block="i2bc1h"  data-pv-sketchpad-el="i2bc1h" style={{ position: 'absolute', left: 177, top: 23 }}>
              {/* pv-editable-zone-start:d3pro3 */}
                {/* pv-block-start:hqfzbz */}
                <Badge data-pv-block="hqfzbz"  label="Badge" color="primary" />
                {/* pv-block-end:hqfzbz */}
              {/* pv-editable-zone-end:d3pro3 */}
            </Card>
            {/* pv-block-end:i2bc1h */}
            {/* pv-block-start:g42x0x */}
            <Rectangle data-pv-block="g42x0x" data-pv-sketchpad-el="g42x0x" style={{ position: 'absolute', left: 67, top: 142, height: 102, width: 353 }} className="w-[200px] h-[200px]">
              {/* pv-editable-zone-start:ih2eip */}
                {/* pv-block-start:yfpr8w */}
                <Button data-pv-block="yfpr8w"  label="Button" variant="solid" color="primary" size="md"  data-pv-sketchpad-el="yfpr8w" style={{ position: 'absolute', left: 126, top: 47 }}/>
                {/* pv-block-end:yfpr8w */}
                
                    {/* pv-block-start:fioctn */}
                    <Badge data-pv-block="fioctn"  label="Badge" color="primary"  data-pv-sketchpad-el="fioctn" style={{ position: 'absolute', left: 103, top: 14 }}/>
                    {/* pv-block-end:fioctn */}
              {/* pv-editable-zone-end:ih2eip */}
            </Rectangle>
            {/* pv-block-end:g42x0x */}
            {/* pv-block-start:78hz5o */}
            <Button data-pv-block="78hz5o"  label="Button" variant="solid" color="primary" size="md"  data-pv-sketchpad-el="78hz5o" style={{ position: 'absolute', left: 430, top: 237 }}/>
            {/* pv-block-end:78hz5o */}

            {/* pv-block-start:axamoo */}
            <Button data-pv-block="axamoo"  label="Button" variant="solid" color="primary" size="md"  data-pv-sketchpad-el="axamoo" style={{ position: 'absolute', left: 266, top: 64 }}/>
            {/* pv-block-end:axamoo */}
          {/* pv-editable-zone-end:i1t9r5 */}
        </Rectangle>
        {/* pv-block-end:e3dgif */}
        
        {/* pv-block-start:ok65gh */}
        <Rectangle data-pv-block="ok65gh" data-pv-sketchpad-el="ok65gh" style={{ position: 'absolute', left: 126, top: 125, width: 458 }} className="w-[200px] h-[200px]">
          {/* pv-editable-zone-start:i1t9r5 */}
            {/* pv-block-start:7b9sut */}
            <Card data-pv-block="7b9sut"  data-pv-sketchpad-el="7b9sut" style={{ position: 'absolute', left: 305, top: 14 }}>
              {/* pv-editable-zone-start:d3pro3 */}
                {/* pv-block-start:9zoydz */}
                <Badge data-pv-block="9zoydz"  label="Badge" color="primary" />
                {/* pv-block-end:9zoydz */}
            
                {/* pv-block-start:nx98w5 */}
                <Badge data-pv-block="nx98w5"  label="Badge" color="primary" />
                {/* pv-block-end:nx98w5 */}
                {/* pv-block-start:qq8jzt */}
                <Button data-pv-block="qq8jzt"  label="Button" variant="solid" color="primary" size="md" />
                {/* pv-block-end:qq8jzt */}
                
                {/* pv-block-start:lk2riu */}
                <Button data-pv-block="lk2riu"  label="Button" variant="solid" color="primary" size="md" />
                {/* pv-block-end:lk2riu */}
              {/* pv-editable-zone-end:d3pro3 */}
            </Card>
            {/* pv-block-end:7b9sut */}
            
            {/* pv-block-start:yrqrbk */}
            <Button data-pv-block="yrqrbk"  label="Button" variant="solid" color="primary" size="md"  data-pv-sketchpad-el="yrqrbk" style={{ position: 'absolute', left: 35, top: 27 }}/>
            {/* pv-block-end:yrqrbk */}
          {/* pv-editable-zone-end:i1t9r5 */}
        </Rectangle>
        {/* pv-block-end:ok65gh */}
        {/* pv-block-start:m64pxz */}
        <Button data-pv-block="m64pxz"  label="Button" variant="solid" color="primary" size="md"  data-pv-sketchpad-el="m64pxz" style={{ position: 'absolute', left: 697, top: 382 }}/>
        {/* pv-block-end:m64pxz */}
        {/* pv-block-start:0kseix */}
        <Button data-pv-block="0kseix"  label="Button" variant="solid" color="primary" size="md"  data-pv-sketchpad-el="0kseix" style={{ position: 'absolute', left: 792, top: 184 }}/>
        {/* pv-block-end:0kseix */}
        {/* pv-block-start:y12rqf */}
        <Button data-pv-block="y12rqf"  label="Button" variant="solid" color="primary" size="md"  data-pv-sketchpad-el="y12rqf" style={{ position: 'absolute', left: 100, top: 100 }}/>
        {/* pv-block-end:y12rqf */}
        {/* pv-block-start:n0vxbc */}
        <span data-pv-block="n0vxbc" data-pv-sketchpad-el="n0vxbc" style={{ position: 'absolute', left: 462, top: 49 }}>Lorem ipsum</span>
        {/* pv-block-end:n0vxbc */}
      {/* pv-editable-zone-end:ia82r5 */}
    </div>
  );
}
