import { Card } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { Rectangle } from '@/components/ui/sketchpad-rectangle'
import { Button } from '@/components/ui/button'
import { RadioGroup } from '@/components/ui/radio-group'
import { RadioItem } from '@/components/ui/radio-item'
// Auto-generated by Protovibe Sketchpad

export default function Frame2() {
  return (
    <div data-layout-mode="absolute" style={{ width: '100%', height: '100%', position: 'relative' }}>
      {/* pv-editable-zone-start:bibqg8 */}
        {/* pv-block-start:8c8sfy */}
        <Card data-pv-block="8c8sfy" data-pv-sketchpad-el="8c8sfy" style={{ position: 'absolute', width: 614, left: 651, top: 54 }}>
          {/* pv-editable-zone-start:dupkaw */}
            {/* pv-block-start:ou8li2 */}
            <Card data-pv-block="ou8li2" >
              {/* pv-editable-zone-start:d3pro3 */}
                {/* pv-block-start:uge8hh */}
                <Badge data-pv-block="uge8hh"  label="Badge" color="primary" />
                {/* pv-block-end:uge8hh */}
                {/* pv-block-start:vtg48d */}
                <Button data-pv-block="vtg48d"  label="Button" variant="solid" color="primary" size="md" />
                {/* pv-block-end:vtg48d */}
                
                {/* pv-block-start:uhw5im */}
                <Badge data-pv-block="uhw5im"  label="Badge" color="primary" />
                {/* pv-block-end:uhw5im */}
              {/* pv-editable-zone-end:d3pro3 */}
            </Card>
            {/* pv-block-end:ou8li2 */}
            {/* pv-block-start:jn33ge */}
            <Card data-pv-block="jn33ge" >
              {/* pv-editable-zone-start:d3pro3 */}
              {/* pv-editable-zone-end:d3pro3 */}
            </Card>
            {/* pv-block-end:jn33ge */}

            {/* pv-block-start:cwetnv */}
            <Button data-pv-block="cwetnv"  label="Button" variant="solid" color="primary" size="md" />
            {/* pv-block-end:cwetnv */}

            {/* pv-block-start:md2k3c */}
            <Badge data-pv-block="md2k3c"  label="Badge" color="primary" />
            {/* pv-block-end:md2k3c */}
            {/* pv-block-start:lsl7qw */}
            <Badge data-pv-block="lsl7qw"  label="Badge" color="primary" />
            {/* pv-block-end:lsl7qw */}
            
            {/* pv-block-start:efe60s */}
            <Button data-pv-block="efe60s"  label="Button" variant="solid" color="primary" size="md" />
            {/* pv-block-end:efe60s */}
          {/* pv-editable-zone-end:dupkaw */}
        </Card>
        {/* pv-block-end:8c8sfy */}
        
        {/* pv-block-start:h7lval */}
        <RadioGroup data-pv-block="h7lval"  orientation="vertical" value="opt1" data-pv-sketchpad-el="h7lval" style={{ position: 'absolute', left: 899, top: 651 }}>
          {/* pv-editable-zone-start:jf0hi0 */}
            {/* pv-block-start:8guw9i */}
            <RadioItem data-pv-block="8guw9i" value="opt1" primaryText="Option One" secondaryText="Description for option one" />
            {/* pv-block-end:8guw9i */}
            {/* pv-block-start:6gt0bw */}
            <RadioItem data-pv-block="6gt0bw" value="opt2" primaryText="Option Two" secondaryText="Description for option two" />
            {/* pv-block-end:6gt0bw */}
            {/* pv-block-start:gtplgq */}
            <RadioItem data-pv-block="gtplgq" value="opt3" primaryText="Option Three" secondaryText="Third option" />
            {/* pv-block-end:gtplgq */}
          {/* pv-editable-zone-end:jf0hi0 */}
        </RadioGroup>
        {/* pv-block-end:h7lval */}
        {/* pv-block-start:2n40cz */}
        <Rectangle data-pv-block="2n40cz" data-pv-sketchpad-el="2n40cz" style={{ position: 'absolute', width: 542, left: 76, top: 60 }} className="w-[200px] h-[200px]">
          {/* pv-editable-zone-start:o6rx04 */}
            {/* pv-block-start:tibi0q */}
            <Button data-pv-block="tibi0q"  label="Button" variant="solid" color="primary" size="md"  data-pv-sketchpad-el="tibi0q" style={{ position: 'absolute', left: 58, top: 21 }}/>
            {/* pv-block-end:tibi0q */}
            
            {/* pv-block-start:jfgfe8 */}
            <Button data-pv-block="jfgfe8"  label="Button" variant="solid" color="primary" size="md"  data-pv-sketchpad-el="jfgfe8" style={{ position: 'absolute', left: 59, top: 72 }}/>
            {/* pv-block-end:jfgfe8 */}
          {/* pv-editable-zone-end:o6rx04 */}
        </Rectangle>
        {/* pv-block-end:2n40cz */}
        
        {/* pv-block-start:fyu1og */}
        <Card data-pv-block="fyu1og"  data-pv-sketchpad-el="fyu1og" style={{ position: 'absolute', left: 76, top: 411 }}>
          {/* pv-editable-zone-start:d3pro3 */}
            {/* pv-block-start:4xupvu */}
            <RadioGroup data-pv-block="4xupvu"  orientation="vertical" value="opt1" >
              {/* pv-editable-zone-start:jf0hi0 */}
                {/* pv-block-start:m5nnip */}
                <RadioItem data-pv-block="m5nnip" value="opt1" primaryText="Option One" secondaryText="Description for option one" />
                {/* pv-block-end:m5nnip */}
                {/* pv-block-start:nm1ccd */}
                <RadioItem data-pv-block="nm1ccd" value="opt2" primaryText="Option Two" secondaryText="Description for option two" />
                {/* pv-block-end:nm1ccd */}
                {/* pv-block-start:8oj7n8 */}
                <RadioItem data-pv-block="8oj7n8" value="opt3" primaryText="Option Three" secondaryText="Third option" />
                {/* pv-block-end:8oj7n8 */}
              {/* pv-editable-zone-end:jf0hi0 */}
            </RadioGroup>
            {/* pv-block-end:4xupvu */}
            
            {/* pv-block-start:fo2t4c */}
            <RadioGroup data-pv-block="fo2t4c"  orientation="vertical" value="opt1" >
              {/* pv-editable-zone-start:jf0hi0 */}
                {/* pv-block-start:4w5n6i */}
                <RadioItem data-pv-block="4w5n6i" value="opt1" primaryText="Option One" secondaryText="Description for option one" />
                {/* pv-block-end:4w5n6i */}
                {/* pv-block-start:s5hpyd */}
                <RadioItem data-pv-block="s5hpyd" value="opt2" primaryText="Option Two" secondaryText="Description for option two" />
                {/* pv-block-end:s5hpyd */}
                {/* pv-block-start:j0oupt */}
                <RadioItem data-pv-block="j0oupt" value="opt3" primaryText="Option Three" secondaryText="Third option" />
                {/* pv-block-end:j0oupt */}
              {/* pv-editable-zone-end:jf0hi0 */}
            </RadioGroup>
            {/* pv-block-end:fo2t4c */}
          {/* pv-editable-zone-end:d3pro3 */}
        </Card>
        {/* pv-block-end:fyu1og */}
        {/* pv-block-start:kepcn8 */}
        <Button data-pv-block="kepcn8"  label="Button" variant="solid" color="primary" size="md"  data-pv-sketchpad-el="kepcn8" style={{ position: 'absolute', left: 412, top: 419 }}/>
        {/* pv-block-end:kepcn8 */}
      {/* pv-editable-zone-end:bibqg8 */}
    </div>
  );
}
