// Auto-generated by Protovibe Sketchpad
import { Card } from '@/components/ui/card';
import { TextBlock } from '@/components/ui/text-block'
import { Button } from '@/components/ui/button'
import { Icon } from '@/components/ui/icon';

export default function Frame2() {
  return (
    <div data-layout-mode="absolute" style={{ width: '100%', height: '100%', position: 'relative' }}>
      {/* pv-editable-zone-start:aspdc9 */}
      {/* pv-block-start:p2ktzm */}
      <Card className="gap-4" data-pv-block="p2ktzm" data-pv-sketchpad-el="p2ktzm" variant="bordered" shadow="none" border="default" style={{ position: 'absolute', width: 301, left: 36, top: 36 }}>
        {/* pv-editable-zone-start:lrwdju */}
        {/* pv-block-start:j2omk4 */}
      <Icon data-pv-block="j2omk4" name="Star" size="md"  />
      {/* pv-block-end:j2omk4 */}

          {/* pv-block-start:tgurr8 */}
          <div data-pv-block="tgurr8" className="flex flex-col gap-1">
            {/* pv-editable-zone-start:s81j6r */}
            {/* pv-block-start:2cbm4a */}
            <div data-pv-block="2cbm4a" className="flex flex-col gap-02">
            {/* pv-editable-zone-start:s46ukl */}
            {/* pv-block-start:vvg6u9 */}
            <TextBlock data-pv-block="vvg6u9" typography="heading-sm">
            Text block
            </TextBlock>
            {/* pv-block-end:vvg6u9 */}
            {/* pv-editable-zone-end:s46ukl */}
            </div>
            {/* pv-block-end:2cbm4a */}
            {/* pv-block-start:payx7w */}
            <div data-pv-block="payx7w" className="flex flex-col gap-02">
            {/* pv-editable-zone-start:s46ukl */}
            {/* pv-block-start:q9x14w */}
            <TextBlock data-pv-block="q9x14w" typography="regular">
            Witam serdecznie proszę państwa i pozdrawiam!<br />
            
            </TextBlock>
            {/* pv-block-end:q9x14w */}
            {/* pv-editable-zone-end:s46ukl */}
            </div>
            {/* pv-block-end:payx7w */}
            {/* pv-editable-zone-end:s81j6r */}
          </div>
          {/* pv-block-end:tgurr8 */}

          {/* pv-block-start:h6uh3b */}
          <Button data-pv-block="h6uh3b" label="Button" variant="solid" color="primary" size="md" />
          {/* pv-block-end:h6uh3b */}
        {/* pv-editable-zone-end:lrwdju */}
      </Card>
      {/* pv-block-end:p2ktzm */}
      
      {/* pv-block-start:15eb2w */}
      <Card className="gap-4" data-pv-block="15eb2w" data-pv-sketchpad-el="15eb2w" variant="bordered" shadow="none" border="default" style={{ position: 'absolute', left: 43, top: 262, width: 301 }}>
        {/* pv-editable-zone-start:lrwdju */}
        {/* pv-block-start:yvi2z2 */}
      <Icon data-pv-block="yvi2z2" name="Star" size="md"  />
      {/* pv-block-end:yvi2z2 */}

          {/* pv-block-start:luwmq6 */}
          <div data-pv-block="luwmq6" className="flex flex-col gap-1">
            {/* pv-editable-zone-start:s81j6r */}
            {/* pv-block-start:4kvu9p */}
            <div data-pv-block="4kvu9p" className="flex flex-col gap-02">
            {/* pv-editable-zone-start:s46ukl */}
            {/* pv-block-start:u9qfdo */}
            <TextBlock data-pv-block="u9qfdo" typography="heading-sm">
            Text block
            </TextBlock>
            {/* pv-block-end:u9qfdo */}
            {/* pv-editable-zone-end:s46ukl */}
            </div>
            {/* pv-block-end:4kvu9p */}
            {/* pv-block-start:u4ohxn */}
            <div data-pv-block="u4ohxn" className="flex flex-col gap-02">
            {/* pv-editable-zone-start:s46ukl */}
            {/* pv-block-start:sx7wjf */}
            <TextBlock data-pv-block="sx7wjf" typography="regular">
            Witam serdecznie proszę państwa i pozdrawiam!<br />
            
            </TextBlock>
            {/* pv-block-end:sx7wjf */}
            {/* pv-editable-zone-end:s46ukl */}
            </div>
            {/* pv-block-end:u4ohxn */}
            {/* pv-editable-zone-end:s81j6r */}
          </div>
          {/* pv-block-end:luwmq6 */}

          {/* pv-block-start:fw0dt2 */}
          <Button data-pv-block="fw0dt2" label="Button" variant="solid" color="primary" size="md" />
          {/* pv-block-end:fw0dt2 */}

        {/* pv-block-start:k6bqr8 */}
      <Icon className="absolute top-2 right-2" data-pv-block="k6bqr8" name="X" size="md"  />
      {/* pv-block-end:k6bqr8 */}
        {/* pv-editable-zone-end:lrwdju */}
      </Card>
      {/* pv-block-end:15eb2w */}
      
      {/* pv-block-start:pfw253 */}
      <Card className="gap-4" data-pv-block="pfw253" data-pv-sketchpad-el="pfw253" variant="bordered" shadow="none" border="default" style={{ position: 'absolute', left: 43, top: 500, width: 301 }}>
        {/* pv-editable-zone-start:lrwdju */}
        {/* pv-block-start:aa55k8 */}
      <Icon data-pv-block="aa55k8" name="Star" size="md"  />
      {/* pv-block-end:aa55k8 */}

          {/* pv-block-start:rxd2ew */}
          <div data-pv-block="rxd2ew" className="flex flex-col gap-1">
            {/* pv-editable-zone-start:s81j6r */}
            {/* pv-block-start:kwz7o5 */}
            <div data-pv-block="kwz7o5" className="flex flex-col gap-02">
            {/* pv-editable-zone-start:s46ukl */}
            {/* pv-block-start:v3prmr */}
            <TextBlock data-pv-block="v3prmr" typography="heading-sm">
            Text block
            </TextBlock>
            {/* pv-block-end:v3prmr */}
            {/* pv-editable-zone-end:s46ukl */}
            </div>
            {/* pv-block-end:kwz7o5 */}
            {/* pv-block-start:z6xcuc */}
            <div data-pv-block="z6xcuc" className="flex flex-col gap-02">
            {/* pv-editable-zone-start:s46ukl */}
            {/* pv-block-start:j4hrps */}
            <TextBlock data-pv-block="j4hrps" typography="regular">
            Witam serdecznie proszę państwa i pozdrawiam!<br />
            
            </TextBlock>
            {/* pv-block-end:j4hrps */}
            {/* pv-editable-zone-end:s46ukl */}
            </div>
            {/* pv-block-end:z6xcuc */}
            {/* pv-editable-zone-end:s81j6r */}
          </div>
          {/* pv-block-end:rxd2ew */}

          {/* pv-block-start:t1jv93 */}
          <Button data-pv-block="t1jv93" label="Button" variant="solid" color="primary" size="md" />
          {/* pv-block-end:t1jv93 */}
        {/* pv-editable-zone-end:lrwdju */}
      </Card>
      {/* pv-block-end:pfw253 */}
      {/* pv-editable-zone-end:aspdc9 */}
    </div>
  );
}
