// Auto-generated by Protovibe Sketchpad
import { Tabs } from '@/components/ui/tabs';
import { TabItem } from '@/components/ui/tab-item';
import { RadioGroup } from '@/components/ui/radio-group';
import { RadioItem } from '@/components/ui/radio-item';
import { RadioIcon } from '@/components/ui/radio-icon';

export default function Frame1() {
  return (
    <div style={{ width: '100%', height: '100%', position: 'relative' }}>
      {/* pv-editable-zone-start:9kul9k */}
      
      {/* pv-block-start:1davm1 */}
      <Tabs data-pv-block="1davm1" data-pv-sketchpad-el="1davm1" value="tab1" style={{ position: 'absolute', left: 92, top: 137 }}>
        {/* pv-editable-zone-start:wdryh9 */}
          {/* pv-block-start:wb2htm */}
          <TabItem data-pv-block="wb2htm" label="Tab 1" value="tab1" />
          {/* pv-block-end:wb2htm */}
          {/* pv-block-start:xzmy1r */}
          <TabItem data-pv-block="xzmy1r" label="Tab 2" value="tab2" />
          {/* pv-block-end:xzmy1r */}
          {/* pv-block-start:6unoz4 */}
          <TabItem data-pv-block="6unoz4" label="Tab 3" value="tab3" />
          {/* pv-block-end:6unoz4 */}
      {/* pv-editable-zone-end:wdryh9 */}
      </Tabs>
      {/* pv-block-end:1davm1 */}
      
      {/* pv-block-start:wv56uj */}
      <RadioGroup data-pv-block="wv56uj" data-pv-sketchpad-el="wv56uj" orientation="vertical" value="opt1" style={{ position: 'absolute', left: 214, top: 240 }}>
        {/* pv-editable-zone-start:5rrvi3 */}
          {/* pv-block-start:y47q7f */}
          <RadioItem data-pv-block="y47q7f" value="opt1" primaryText="Option One" secondaryText="Description for option one" />
          {/* pv-block-end:y47q7f */}
          {/* pv-block-start:ndn4st */}
          <RadioItem data-pv-block="ndn4st" value="opt2" primaryText="Option Two" secondaryText="Description for option two" />
          {/* pv-block-end:ndn4st */}
          {/* pv-block-start:gwkce4 */}
          <RadioItem data-pv-block="gwkce4" value="opt3" primaryText="Option Three" disabled={true} secondaryText="Disabled option" />
          {/* pv-block-end:gwkce4 */}
        {/* pv-editable-zone-end:5rrvi3 */}
      </RadioGroup>
      {/* pv-block-end:wv56uj */}
      
      {/* pv-block-start:nv9rkl */}
      <RadioItem data-pv-block="nv9rkl" data-pv-sketchpad-el="nv9rkl" primaryText="Option 1" value="opt1" style={{ position: 'absolute', left: 85, top: 446 }} />
      {/* pv-block-end:nv9rkl */}
      
      {/* pv-block-start:1cogsw */}
      <RadioIcon data-pv-block="1cogsw" data-pv-sketchpad-el="1cogsw" state="unselected" style={{ position: 'absolute', left: 513, top: 418 }} />
      {/* pv-block-end:1cogsw */}
      {/* pv-editable-zone-end:9kul9k */}
    </div>
  );
}
