// Auto-generated by Protovibe Sketchpad

export default function Frame2() {
  return (
    <div style={{ width: '100%', height: '100%', position: 'relative' }}>
      {/* pv-editable-zone-start:qowi40 */}
      {/* pv-editable-zone-end:qowi40 */}
    </div>
  );
}
