// plugins/protovibe/src/ui/utils/domSnapshot.ts
//
// Serializes a live DOM subtree (inside the app iframe) into a JSON tree that
// the backend /__convert-to-sketchpad endpoint can turn into flat, logic-free
// JSX. The shell has same-origin access to the iframe DOM, so this runs
// synchronously on the real elements.

export interface SnapshotRect {
  left: number;
  top: number;
  width: number;
  height: number;
}

export interface SnapshotNode {
  kind: 'element' | 'text';
  /** Collapsed text content (text nodes only). */
  text?: string;
  /** Lowercased tag name (element nodes only). SVG keeps its real tag. */
  tag?: string;
  /** Raw class attribute value. */
  className?: string;
  /** Safelisted non-protovibe attributes (kebab/native names, values raw). */
  attrs?: Record<string, string>;
  /** data-pv-component-id when present. */
  componentId?: string;
  /** data-pv-block id when present. */
  pvBlockId?: string;
  /** App-level source locator (data-pv-loc-app-<hash> suffix), for AST prop recovery. */
  locId?: string;
  /** True when the node lives inside an <svg> subtree. */
  isSvg?: boolean;
  /** Viewport-absolute bounding rect (iframe coordinate space). */
  rect?: SnapshotRect;
  children?: SnapshotNode[];
}

export interface DomSnapshot {
  root: SnapshotNode;
  foundComponents: Array<{ componentId: string; count: number }>;
}

const SKIPPED_TAGS = new Set(['script', 'style', 'link', 'template', 'noscript', 'meta']);

// Attributes we never carry over: protovibe bookkeeping, inline styles
// (regenerated by the converter) and ids (would duplicate).
function isDroppedAttr(name: string): boolean {
  return (
    name === 'style' ||
    name === 'id' ||
    name === 'class' ||
    name.startsWith('on') ||
    name.startsWith('data-pv-')
  );
}

function toRect(r: DOMRect): SnapshotRect {
  return {
    left: Math.round(r.left),
    top: Math.round(r.top),
    width: Math.round(r.width),
    height: Math.round(r.height),
  };
}

function walkElement(el: Element, insideSvg: boolean, counts: Map<string, number>): SnapshotNode | null {
  const tag = el.tagName.toLowerCase();
  if (SKIPPED_TAGS.has(tag)) return null;
  if (el.hasAttribute('data-pv-ui')) return null;

  const isSvg = insideSvg || tag === 'svg';
  const doc = el.ownerDocument;
  const win = doc.defaultView;
  if (!isSvg && win && win.getComputedStyle(el).display === 'none') return null;

  const node: SnapshotNode = { kind: 'element', tag, rect: toRect(el.getBoundingClientRect()) };
  if (isSvg) node.isSvg = true;

  const attrs: Record<string, string> = {};
  for (const attr of Array.from(el.attributes)) {
    const name = attr.name;
    if (name === 'class') {
      if (attr.value.trim()) node.className = attr.value.trim();
      continue;
    }
    if (name === 'data-pv-component-id') {
      node.componentId = attr.value;
      continue;
    }
    if (name === 'data-pv-block') {
      node.pvBlockId = attr.value;
      continue;
    }
    if (name.startsWith('data-pv-loc-app-')) {
      node.locId = name.replace('data-pv-loc-app-', '');
      continue;
    }
    if (isSvg) {
      // Keep every SVG presentation attribute (d, viewBox, fill, …) verbatim;
      // the converter camelCases them for JSX.
      if (!name.startsWith('data-pv-') && !name.startsWith('xlink') && name !== 'xmlns:xlink') {
        attrs[name] = attr.value;
      }
      continue;
    }
    if (isDroppedAttr(name)) continue;
    attrs[name] = attr.value;
  }

  // Form controls: capture the *current* value so the flat copy shows what the
  // user sees on screen, not the initial markup value.
  if (el instanceof HTMLInputElement) {
    if (el.type === 'checkbox' || el.type === 'radio') {
      if (el.checked) attrs['checked'] = 'true';
      else delete attrs['checked'];
    } else if (el.value) {
      attrs['value'] = el.value;
    }
  } else if (el instanceof HTMLTextAreaElement && el.value) {
    attrs['value'] = el.value;
  }

  if (Object.keys(attrs).length > 0) node.attrs = attrs;

  if (node.componentId) {
    counts.set(node.componentId, (counts.get(node.componentId) || 0) + 1);
  }

  const children: SnapshotNode[] = [];
  for (const child of Array.from(el.childNodes)) {
    if (child.nodeType === Node.TEXT_NODE) {
      const text = (child.textContent || '').replace(/\s+/g, ' ').trim();
      if (!text) continue;
      const range = doc.createRange();
      range.selectNodeContents(child);
      children.push({ kind: 'text', text, rect: toRect(range.getBoundingClientRect()) });
    } else if (child.nodeType === Node.ELEMENT_NODE) {
      const childNode = walkElement(child as Element, isSvg, counts);
      if (childNode) children.push(childNode);
    }
  }
  if (children.length > 0) node.children = children;

  return node;
}

export function snapshotElement(root: HTMLElement): DomSnapshot | null {
  const counts = new Map<string, number>();
  const rootNode = walkElement(root, false, counts);
  if (!rootNode) return null;
  return {
    root: rootNode,
    foundComponents: Array.from(counts.entries()).map(([componentId, count]) => ({ componentId, count })),
  };
}
