// Auto-generated by Protovibe Sketchpad
import { TextHeading } from '@/components/ui/text-heading';
import { TextParagraph } from '@/components/ui/text-paragraph';
import { Card } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Container } from '@/components/ui/container';
import { Rectangle } from '@/components/ui/sketchpad-rectangle';
import { Icon } from '@/components/ui/icon';
import { Image } from '@/components/ui/image';
import { RadioGroup } from '@/components/ui/radio-group';
import { RadioItem } from '@/components/ui/radio-item';
import { DropdownButton } from '@/components/ui/dropdown-button';
import { DropdownItem } from '@/components/ui/dropdown-item';
import { DropdownSeparator } from '@/components/ui/dropdown-separator';

export default function Frame1() {
  return (
    <div data-layout-mode="absolute" style={{ width: '100%', height: '100%', position: 'relative' }}>
      {/* pv-editable-zone-start:d3dvka */}
      {/* pv-block-start:439g8m */}
      <Container data-pv-block="439g8m" data-pv-sketchpad-el="439g8m"  style={{ position: 'absolute', left: 81, top: 113, width: 264 }}>
        {/* pv-editable-zone-start:qqn7ay */}
        {/* pv-block-start:qiistx */}
      <TextHeading data-pv-block="qiistx" typography="heading-md" >
        Heading
      </TextHeading>
      {/* pv-block-end:qiistx */}

        {/* pv-block-start:133jjb */}
      <TextParagraph data-pv-block="133jjb" typography="regular" >
        Paragraph text Paragraph text Paragraph text Paragraph text Paragraph text Paragraph text Paragraph text Paragraph text 
      </TextParagraph>
      {/* pv-block-end:133jjb */}

        {/* pv-block-start:yd778w */}
      <Button data-pv-block="yd778w" label="Button" variant="solid" color="primary" size="md"  />
      {/* pv-block-end:yd778w */}

        {/* pv-block-start:yc9c30 */}
      <Button data-pv-block="yc9c30" label="Button" variant="solid" color="primary" size="md" />
      {/* pv-block-end:yc9c30 */}

        {/* pv-block-start:v1tqn4 */}
      <Button data-pv-block="v1tqn4" label="Button" variant="solid" color="primary" size="md" />
      {/* pv-block-end:v1tqn4 */}

        {/* pv-block-start:5wvp6d */}
      <Button data-pv-block="5wvp6d" label="Button" variant="solid" color="primary" size="md" />
      {/* pv-block-end:5wvp6d */}

          {/* pv-block-start:ajgck6 */}
          <span data-pv-block="ajgck6">
            adasdasd
          </span>
          {/* pv-block-end:ajgck6 */}
        {/* pv-editable-zone-end:qqn7ay */}
      </Container>
      {/* pv-block-end:439g8m */}

      {/* pv-block-start:bbx8bi */}
      <Button data-pv-block="bbx8bi" label="Button" variant="solid" color="primary" size="md"  data-pv-sketchpad-el="bbx8bi" style={{ position: 'absolute', left: 520, top: 145 }}/>
      {/* pv-block-end:bbx8bi */}



      {/* pv-block-start:qa89kp */}
      <Image randomImage data-pv-block="qa89kp" data-pv-sketchpad-el="qa89kp" className="bg-[url('/src/images/from-protovibe/image-placeholder.svg')] bg-cover bg-center bg-no-repeat aspect-video w-full" style={{ position: 'absolute', left: 798, top: 81, width: 213 }} />
      {/* pv-block-end:qa89kp */}
      
      {/* pv-block-start:rs0fdw */}
      <Image  data-pv-block="rs0fdw" data-pv-sketchpad-el="rs0fdw" className="bg-[url('/src/images/from-protovibe/image-placeholder.svg')] bg-cover bg-center bg-no-repeat aspect-video w-full" style={{ position: 'absolute', left: 1098, top: 79, width: 238 }} />
      {/* pv-block-end:rs0fdw */}

      {/* pv-block-start:s4leqk */}
      <Card data-pv-block="s4leqk" data-pv-sketchpad-el="s4leqk"  style={{ position: 'absolute', width: 526, left: 795, top: 276 }}>
        {/* pv-editable-zone-start:jxr5ey */}
        {/* pv-block-start:6qhmpi */}
      <Button data-pv-block="6qhmpi" label="Button" variant="solid" color="primary" size="md" />
      {/* pv-block-end:6qhmpi */}

        {/* pv-block-start:wmxcu2 */}
      <Button data-pv-block="wmxcu2" label="Button" variant="solid" color="primary" size="md" />
      {/* pv-block-end:wmxcu2 */}

        {/* pv-block-start:p6i999 */}
      <Container data-pv-block="p6i999"  >
        {/* pv-editable-zone-start:eyutv0 */}
        {/* pv-editable-zone-end:eyutv0 */}
      </Container>
      {/* pv-block-end:p6i999 */}


        {/* pv-block-start:zppmsv */}
      <Image randomImage data-pv-block="zppmsv" className="bg-[url('/src/images/from-protovibe/image-placeholder.svg')] bg-cover bg-center bg-no-repeat aspect-video w-full"  />
      {/* pv-block-end:zppmsv */}        {/* pv-editable-zone-end:jxr5ey */}
      </Card>
      {/* pv-block-end:s4leqk */}

        {/* pv-block-start:2g8vkk */}
        <div className="flex flex-col min-h-4" data-pv-block="2g8vkk" data-pv-sketchpad-el="2g8vkk" style={{ position: 'absolute', left: 86, top: 49 }}>
          {/* pv-editable-zone-start:inside-2g8vkk */}
            {/* pv-block-start:dd6bm5 */}
            <span data-pv-block="dd6bm5">Lorem ipsum</span>
            {/* pv-block-end:dd6bm5 */}
          {/* pv-editable-zone-end:inside-2g8vkk */}
        </div>
        {/* pv-block-end:2g8vkk */}
      
      {/* pv-block-start:y0csap */}
      <Rectangle data-pv-block="y0csap" data-pv-sketchpad-el="y0csap" className="w-[200px] h-[200px]" style={{ position: 'absolute', left: 74, top: 414, height: 450, width: 661 }}>
        {/* pv-editable-zone-start:wlrv4v */}
        {/* pv-block-start:w11xb3 */}
      <Button data-pv-block="w11xb3" label="Button" variant="solid" color="primary" size="md"  data-pv-sketchpad-el="w11xb3" style={{ position: 'absolute', left: 41, top: 101 }}/>
      {/* pv-block-end:w11xb3 */}

        {/* pv-block-start:m9hvoh */}
      <Button data-pv-block="m9hvoh" label="Button" variant="outline" color="primary" size="md"  data-pv-sketchpad-el="m9hvoh" style={{ position: 'absolute', left: 124, top: 104 }}/>
      {/* pv-block-end:m9hvoh */}

        {/* pv-block-start:dmnvft */}
      <TextHeading data-pv-block="dmnvft" data-pv-sketchpad-el="dmnvft" typography="heading-md" style={{ position: 'absolute', left: 39, top: 32 }}>
        Heading
      </TextHeading>
      {/* pv-block-end:dmnvft */}

        {/* pv-block-start:2s4xyi */}
      <TextParagraph data-pv-block="2s4xyi" data-pv-sketchpad-el="2s4xyi" typography="regular" style={{ position: 'absolute', left: 41, top: 61 }}>
        Paragraph text
      </TextParagraph>
      {/* pv-block-end:2s4xyi */}

        {/* pv-block-start:v6iaql */}
      <Icon data-pv-block="v6iaql" data-pv-sketchpad-el="v6iaql" name="Edit" size="md" style={{ position: 'absolute', width: 20, left: 618, top: 22 }} />
      {/* pv-block-end:v6iaql */}

        {/* pv-block-start:oyjiq2 */}
      <Image randomImage data-pv-block="oyjiq2" data-pv-sketchpad-el="oyjiq2" className="bg-[url('/src/images/from-protovibe/image-placeholder.svg')] bg-cover bg-center bg-no-repeat aspect-video w-full" style={{ position: 'absolute', left: 45, top: 168, width: 406 }} />
      {/* pv-block-end:oyjiq2 */}

        {/* pv-block-start:pv1ak2 */}
      <RadioGroup data-pv-block="pv1ak2" data-pv-sketchpad-el="pv1ak2" orientation="vertical" value="opt1" style={{ position: 'absolute', left: 230, top: 30 }}>
        {/* pv-editable-zone-start:jfm4b2 */}
          {/* pv-block-start:x08a9y */}
          <RadioItem data-pv-block="x08a9y" value="opt1" primaryText="Option One" secondaryText="Description for option one" />
          {/* pv-block-end:x08a9y */}
          {/* pv-block-start:kz79gf */}
          <RadioItem data-pv-block="kz79gf" value="opt2" primaryText="Option Two" secondaryText="Description for option two" />
          {/* pv-block-end:kz79gf */}
          {/* pv-block-start:pk2f8v */}
          <RadioItem data-pv-block="pk2f8v" value="opt3" primaryText="Option Three" secondaryText="Third option" />
          {/* pv-block-end:pk2f8v */}
        {/* pv-editable-zone-end:jfm4b2 */}
      </RadioGroup>
      {/* pv-block-end:pv1ak2 */}
        {/* pv-editable-zone-end:wlrv4v */}
      </Rectangle>
      {/* pv-block-end:y0csap */}
      

      
      {/* pv-block-start:20210x */}
      <TextHeading data-pv-block="20210x" data-pv-sketchpad-el="20210x" typography="heading-lg" style={{ position: 'absolute', left: 516, top: 95 }}>
        asdasdad
      </TextHeading>
      {/* pv-block-end:20210x */}
      
      {/* pv-block-start:4nt458 */}
      <div data-pv-block="4nt458" className="flex flex-col gap-2"  data-pv-sketchpad-el="4nt458" style={{ position: 'absolute', left: 428, top: 174 }}>
        {/* pv-editable-zone-start:geeh4m */}
        {/* pv-block-start:04yrq2 */}
        <Button data-pv-block="04yrq2" label="Button" variant="solid" color="primary" size="md" />
        {/* pv-block-end:04yrq2 */}
        {/* pv-block-start:ailiov */}
        <Button data-pv-block="ailiov" label="Button" variant="solid" color="primary" size="md" />
        {/* pv-block-end:ailiov */}
        {/* pv-editable-zone-end:geeh4m */}
      </div>
      {/* pv-block-end:4nt458 */}
      
      {/* pv-block-start:93y9w3 */}
      <DropdownButton data-pv-block="93y9w3" data-pv-sketchpad-el="93y9w3" label="Options" variant="outline" color="neutral" rightIcon="ChevronDown" style={{ position: 'absolute', left: 322, top: 313 }}>
        {/* pv-editable-zone-start:wdq1jz */}
          {/* pv-block-start:11mk00 */}
          <DropdownItem data-pv-block="11mk00" label="Edit" prefixIcon="Edit2" />
          {/* pv-block-end:11mk00 */}
          {/* pv-block-start:sjtki7 */}
          <DropdownItem data-pv-block="sjtki7" label="Duplicate" prefixIcon="Copy" />
          {/* pv-block-end:sjtki7 */}
          {/* pv-block-start:pjpi9b */}
          <DropdownSeparator data-pv-block="pjpi9b" />
          {/* pv-block-end:pjpi9b */}
          {/* pv-block-start:pxxcwh */}
          <DropdownItem data-pv-block="pxxcwh" label="Delete" prefixIcon="Trash2" destructive={true} />
          {/* pv-block-end:pxxcwh */}
        {/* pv-editable-zone-end:wdq1jz */}
      </DropdownButton>
      {/* pv-block-end:93y9w3 */}
      
      {/* pv-block-start:hq6ukf */}
      <Rectangle data-pv-block="hq6ukf" data-pv-sketchpad-el="hq6ukf" className="w-[200px] h-[200px]" style={{ position: 'absolute', left: 483, top: 289 }}>
        {/* pv-editable-zone-start:rkdn2p */}
        {/* pv-editable-zone-end:rkdn2p */}
      </Rectangle>
      {/* pv-block-end:hq6ukf */}
      {/* pv-editable-zone-end:d3dvka */}
    </div>
  );
}
