import { Image } from '@/components/ui/image'
import { Card } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
// Auto-generated by Protovibe Sketchpad

export default function Frame2() {
  return (
    <div data-layout-mode="absolute" style={{ width: '100%', height: '100%', position: 'relative' }}>
      {/* pv-editable-zone-start:jr37z0 */}
      
      {/* pv-block-start:6k6y2h */}
      <Image randomImage data-pv-block="6k6y2h" data-pv-sketchpad-el="6k6y2h" className="bg-[url('/src/images/from-protovibe/image-placeholder.svg')] bg-cover bg-center bg-no-repeat aspect-video w-full" style={{ position: 'absolute', left: 118, top: 212, width: 178 }} />
      {/* pv-block-end:6k6y2h */}
      
      {/* pv-block-start:j94omq */}
      <Card data-pv-block="j94omq" data-pv-sketchpad-el="j94omq"  style={{ position: 'absolute', left: 158, top: 493, width: 330 }}>
        {/* pv-editable-zone-start:jxr5ey */}
        {/* pv-block-start:3linjw */}
      <Button data-pv-block="3linjw" label="Button" variant="solid" color="primary" size="md" />
      {/* pv-block-end:3linjw */}

        {/* pv-block-start:wca2ok */}
      <Button data-pv-block="wca2ok" label="Button" variant="solid" color="primary" size="md" />
      {/* pv-block-end:wca2ok */}
        {/* pv-editable-zone-end:jxr5ey */}
      </Card>
      {/* pv-block-end:j94omq */}
      {/* pv-editable-zone-end:jr37z0 */}
    </div>
  );
}
