// Auto-generated by Protovibe Sketchpad

export default function Frame5() {
  return (
    <div data-layout-mode="absolute" style={{ width: '100%', height: '100%', position: 'relative' }}>
      {/* pv-editable-zone-start:ep46o3 */}
      {/* pv-editable-zone-end:ep46o3 */}
    </div>
  );
}
