// Auto-generated by Protovibe Sketchpad
import { TextHeading } from '@/components/ui/text-heading';
import { TextParagraph } from '@/components/ui/text-paragraph';
import { Card } from '@/components/ui/card';
import { Button } from '@/components/ui/button';

export default function Frame1() {
  return (
    <div data-layout-mode="absolute" style={{ width: '100%', height: '100%', position: 'relative' }}>
      {/* pv-editable-zone-start:d3dvka */}
      {/* pv-block-start:sq6hc8 */}
      <Card className="gap-4" data-pv-block="sq6hc8" data-pv-sketchpad-el="sq6hc8"  style={{ position: 'absolute', width: 396, left: 354, top: 361 }}>
        {/* pv-editable-zone-start:vwbmom */}
        {/* pv-block-start:wn30nq */}
        <div data-pv-block="wn30nq" className="flex flex-col gap-0">
          {/* pv-editable-zone-start:zsp6pc */}
          {/* pv-block-start:zb9q0v */}
          <TextHeading data-pv-block="zb9q0v" typography="heading-md" >
          Heading
          </TextHeading>
          {/* pv-block-end:zb9q0v */}
          {/* pv-block-start:ky1q0j */}
          <TextParagraph data-pv-block="ky1q0j" typography="regular" >
          Paragraph text
          </TextParagraph>
          {/* pv-block-end:ky1q0j */}
          {/* pv-editable-zone-end:zsp6pc */}
        </div>
        {/* pv-block-end:wn30nq */}

        {/* pv-block-start:b4epir */}
      <Button data-pv-block="b4epir" label="Button" variant="solid" color="primary" size="md"  />
      {/* pv-block-end:b4epir */}
        {/* pv-editable-zone-end:vwbmom */}
      </Card>
      {/* pv-block-end:sq6hc8 */}
      {/* pv-editable-zone-end:d3dvka */}
    </div>
  );
}
