import { Rectangle } from '@/components/ui/sketchpad-rectangle'
import { Button } from '@/components/ui/button'
import { TextHeading } from '@/components/ui/text-heading'
import { TextParagraph } from '@/components/ui/text-paragraph'
import { Icon } from '@/components/ui/icon'
import { Image } from '@/components/ui/image'
import { RadioGroup } from '@/components/ui/radio-group'
import { RadioItem } from '@/components/ui/radio-item'
// Auto-generated by Protovibe Sketchpad

export default function Frame5() {
  return (
    <div data-layout-mode="absolute" style={{ width: '100%', height: '100%', position: 'relative' }}>
      {/* pv-editable-zone-start:ep46o3 */}
      
      {/* pv-block-start:6v0dsw */}
      <Rectangle data-pv-block="6v0dsw" data-pv-sketchpad-el="6v0dsw" className="w-[200px] h-[200px]" style={{ position: 'absolute', left: 25, top: 40, height: 450, width: 661 }}>
        {/* pv-editable-zone-start:wlrv4v */}
        {/* pv-block-start:d3mfp4 */}
      <Button data-pv-block="d3mfp4" label="Button" variant="solid" color="primary" size="md"  data-pv-sketchpad-el="d3mfp4" style={{ position: 'absolute', left: 41, top: 101 }}/>
      {/* pv-block-end:d3mfp4 */}

        {/* pv-block-start:4og5op */}
      <Button data-pv-block="4og5op" label="Button" variant="outline" color="primary" size="md"  data-pv-sketchpad-el="4og5op" style={{ position: 'absolute', left: 124, top: 104 }}/>
      {/* pv-block-end:4og5op */}

        {/* pv-block-start:ubo0nl */}
      <TextHeading data-pv-block="ubo0nl" data-pv-sketchpad-el="ubo0nl" typography="heading-md" style={{ position: 'absolute', left: 39, top: 32 }}>
        Heading
      </TextHeading>
      {/* pv-block-end:ubo0nl */}

        {/* pv-block-start:zgjmvm */}
      <TextParagraph data-pv-block="zgjmvm" data-pv-sketchpad-el="zgjmvm" typography="regular" style={{ position: 'absolute', left: 41, top: 61 }}>
        Paragraph text
      </TextParagraph>
      {/* pv-block-end:zgjmvm */}

        {/* pv-block-start:x5vi2r */}
      <Icon data-pv-block="x5vi2r" data-pv-sketchpad-el="x5vi2r" name="Edit" size="md" style={{ position: 'absolute', width: 20, left: 618, top: 22 }} />
      {/* pv-block-end:x5vi2r */}

        {/* pv-block-start:506gm4 */}
      <Image randomImage data-pv-block="506gm4" data-pv-sketchpad-el="506gm4" className="bg-[url('/src/images/from-protovibe/image-placeholder.svg')] bg-cover bg-center bg-no-repeat aspect-video w-full" style={{ position: 'absolute', left: 45, top: 168, width: 406 }} />
      {/* pv-block-end:506gm4 */}

        {/* pv-block-start:xqh9gx */}
      <RadioGroup data-pv-block="xqh9gx" data-pv-sketchpad-el="xqh9gx" orientation="vertical" value="opt1" style={{ position: 'absolute', left: 230, top: 30 }}>
        {/* pv-editable-zone-start:jfm4b2 */}
          {/* pv-block-start:uwk3vk */}
          <RadioItem data-pv-block="uwk3vk" value="opt1" primaryText="Option One" secondaryText="Description for option one" />
          {/* pv-block-end:uwk3vk */}
          {/* pv-block-start:fguimo */}
          <RadioItem data-pv-block="fguimo" value="opt2" primaryText="Option Two" secondaryText="Description for option two" />
          {/* pv-block-end:fguimo */}
          {/* pv-block-start:sgfjqk */}
          <RadioItem data-pv-block="sgfjqk" value="opt3" primaryText="Option Three" secondaryText="Third option" />
          {/* pv-block-end:sgfjqk */}
        {/* pv-editable-zone-end:jfm4b2 */}
      </RadioGroup>
      {/* pv-block-end:xqh9gx */}
        {/* pv-editable-zone-end:wlrv4v */}
      </Rectangle>
      {/* pv-block-end:6v0dsw */}
      {/* pv-editable-zone-end:ep46o3 */}
    </div>
  );
}
