import { Image } from '@/components/ui/image'
import { Card } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Rectangle } from '@/components/ui/sketchpad-rectangle'
import { TextHeading } from '@/components/ui/text-heading'
import { TextParagraph } from '@/components/ui/text-paragraph'
import { Icon } from '@/components/ui/icon'
// Auto-generated by Protovibe Sketchpad

export default function Frame2() {
  return (
    <div data-layout-mode="absolute" style={{ width: '100%', height: '100%', position: 'relative' }}>
      {/* pv-editable-zone-start:2ycyob */}
      {/* pv-block-start:iipqi8 */}
      <Card data-pv-block="iipqi8" data-pv-sketchpad-el="iipqi8"  style={{ position: 'absolute', left: 371, top: 405, width: 330 }}>
        {/* pv-editable-zone-start:d8kqr1 */}
        {/* pv-block-start:7fzcne */}
      <Button data-pv-block="7fzcne" label="Button" variant="solid" color="primary" size="md" />
      {/* pv-block-end:7fzcne */}

        {/* pv-block-start:58d3ng */}
      <Button data-pv-block="58d3ng" label="Button" variant="solid" color="primary" size="md" />
      {/* pv-block-end:58d3ng */}
        {/* pv-editable-zone-end:jxr5ey */}
      </Card>
      {/* pv-block-end:iipqi8 */}
      
      {/* pv-block-start:rddcic */}
      <div data-pv-block="rddcic" className="flex flex-col gap-2" data-pv-sketchpad-el="rddcic" style={{ position: 'absolute', left: 60, top: 108 }}>
        {/* pv-editable-zone-start:42uzxs */}
        {/* pv-block-start:pu8h7p */}
        <Image randomImage data-pv-block="pu8h7p" className="bg-[url('/src/images/from-protovibe/image-placeholder.svg')] bg-cover bg-center bg-no-repeat aspect-video w-full" style={{ width: 178 }} />
        {/* pv-block-end:pu8h7p */}
        {/* pv-editable-zone-end:1r8mze */}
      </div>
      {/* pv-block-end:rddcic */}

      
      {/* pv-block-start:2ojlsv */}
      <Image randomImage data-pv-block="2ojlsv" data-pv-sketchpad-el="2ojlsv" className="bg-[url('/src/images/from-protovibe/image-placeholder.svg')] bg-cover bg-center bg-no-repeat aspect-video w-full" style={{ position: 'absolute', left: 82, top: 278, width: 406 }} />
      {/* pv-block-end:2ojlsv */}
      {/* pv-editable-zone-end:jr37z0 */}
    </div>
  );
}
