import { Card } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { Rectangle } from '@/components/ui/sketchpad-rectangle'
import { Button } from '@/components/ui/button'
import { RadioGroup } from '@/components/ui/radio-group'
import { RadioItem } from '@/components/ui/radio-item'
// Auto-generated by Protovibe Sketchpad

export default function Frame2() {
  return (
    <div data-layout-mode="absolute" style={{ width: '100%', height: '100%', position: 'relative' }}>
      {/* pv-editable-zone-start:bibqg8 */}
        {/* pv-block-start:8c8sfy */}
        <Card data-pv-block="8c8sfy" data-pv-sketchpad-el="8c8sfy" style={{ position: 'absolute', width: 614, left: 640, top: 33 }}>
          {/* pv-editable-zone-start:dupkaw */}
            {/* pv-block-start:ou8li2 */}
            <Card data-pv-block="ou8li2" >
              {/* pv-editable-zone-start:d3pro3 */}
                {/* pv-block-start:uge8hh */}
                <Badge data-pv-block="uge8hh"  label="Badge" color="primary" />
                {/* pv-block-end:uge8hh */}
                {/* pv-block-start:vtg48d */}
                <Button data-pv-block="vtg48d"  label="Button" variant="solid" color="primary" size="md" />
                {/* pv-block-end:vtg48d */}
                
                {/* pv-block-start:uhw5im */}
                <Badge data-pv-block="uhw5im"  label="Badge" color="primary" />
                {/* pv-block-end:uhw5im */}
              {/* pv-editable-zone-end:d3pro3 */}
            </Card>
            {/* pv-block-end:ou8li2 */}
            {/* pv-block-start:jn33ge */}
            <Card data-pv-block="jn33ge" >
              {/* pv-editable-zone-start:d3pro3 */}
              {/* pv-editable-zone-end:d3pro3 */}
            </Card>
            {/* pv-block-end:jn33ge */}

            {/* pv-block-start:0onna7 */}
            <Button data-pv-block="0onna7"  label="Button" variant="solid" color="primary" size="md" />
            {/* pv-block-end:0onna7 */}
            
            {/* pv-block-start:md2k3c */}
            <Badge data-pv-block="md2k3c"  label="Badge" color="primary" />
            {/* pv-block-end:md2k3c */}
            {/* pv-block-start:lsl7qw */}
            <Badge data-pv-block="lsl7qw"  label="Badge" color="primary" />
            {/* pv-block-end:lsl7qw */}
            
            {/* pv-block-start:efe60s */}
            <Button data-pv-block="efe60s"  label="Button" variant="solid" color="primary" size="md" />
            {/* pv-block-end:efe60s */}
          {/* pv-editable-zone-end:dupkaw */}
        </Card>
        {/* pv-block-end:8c8sfy */}
        
        {/* pv-block-start:h7lval */}
        <RadioGroup data-pv-block="h7lval"  orientation="vertical" value="opt1" data-pv-sketchpad-el="h7lval" style={{ position: 'absolute', left: 899, top: 651 }}>
          {/* pv-editable-zone-start:jf0hi0 */}
            {/* pv-block-start:8guw9i */}
            <RadioItem data-pv-block="8guw9i" value="opt1" primaryText="Option One" secondaryText="Description for option one" />
            {/* pv-block-end:8guw9i */}
            {/* pv-block-start:6gt0bw */}
            <RadioItem data-pv-block="6gt0bw" value="opt2" primaryText="Option Two" secondaryText="Description for option two" />
            {/* pv-block-end:6gt0bw */}
            {/* pv-block-start:gtplgq */}
            <RadioItem data-pv-block="gtplgq" value="opt3" primaryText="Option Three" secondaryText="Third option" />
            {/* pv-block-end:gtplgq */}
          {/* pv-editable-zone-end:jf0hi0 */}
        </RadioGroup>
        {/* pv-block-end:h7lval */}
        {/* pv-block-start:2n40cz */}
        <Rectangle data-pv-block="2n40cz" data-pv-sketchpad-el="2n40cz" style={{ position: 'absolute', height: 690, width: 542, left: 44, top: 33 }} className="w-[200px] h-[200px]">
          {/* pv-editable-zone-start:o6rx04 */}
            {/* pv-block-start:tibi0q */}
            <Button data-pv-block="tibi0q"  label="Button" variant="solid" color="primary" size="md"  data-pv-sketchpad-el="tibi0q" style={{ position: 'absolute', left: 33, top: 31 }}/>
            {/* pv-block-end:tibi0q */}
            
            {/* pv-block-start:jfgfe8 */}
            <Button data-pv-block="jfgfe8"  label="Button" variant="solid" color="primary" size="md"  data-pv-sketchpad-el="jfgfe8" style={{ position: 'absolute', left: 33, top: 120 }}/>
            {/* pv-block-end:jfgfe8 */}
            {/* pv-block-start:gz0pkx */}
            <Button data-pv-block="gz0pkx"  label="Button" variant="solid" color="primary" size="md"  data-pv-sketchpad-el="gz0pkx" style={{ position: 'absolute', left: 33, top: 75 }}/>
            {/* pv-block-end:gz0pkx */}
            {/* pv-block-start:n1pq8y */}
            <Card data-pv-block="n1pq8y"  data-pv-sketchpad-el="n1pq8y" style={{ position: 'absolute', left: 141, top: 31 }}>
              {/* pv-editable-zone-start:d3pro3 */}
                {/* pv-block-start:e9q27f */}
                <RadioGroup data-pv-block="e9q27f"  orientation="vertical" value="opt1" >
                  {/* pv-editable-zone-start:jf0hi0 */}
                    {/* pv-block-start:m96zeb */}
                    <RadioItem data-pv-block="m96zeb" value="opt1" primaryText="Option One" secondaryText="Description for option one" />
                    {/* pv-block-end:m96zeb */}
                    {/* pv-block-start:hvax8k */}
                    <RadioItem data-pv-block="hvax8k" value="opt2" primaryText="Option Two" secondaryText="Description for option two" />
                    {/* pv-block-end:hvax8k */}
                    {/* pv-block-start:fe9spd */}
                    <RadioItem data-pv-block="fe9spd" value="opt3" primaryText="Option Three" secondaryText="Third option" />
                    {/* pv-block-end:fe9spd */}
                  {/* pv-editable-zone-end:jf0hi0 */}
                </RadioGroup>
                {/* pv-block-end:e9q27f */}
                
                {/* pv-block-start:hbmw9o */}
                <RadioGroup data-pv-block="hbmw9o"  orientation="vertical" value="opt1" >
                  {/* pv-editable-zone-start:jf0hi0 */}
                    {/* pv-block-start:9ahxt7 */}
                    <RadioItem data-pv-block="9ahxt7" value="opt1" primaryText="Option One" secondaryText="Description for option one" />
                    {/* pv-block-end:9ahxt7 */}
                    {/* pv-block-start:2vd0pz */}
                    <RadioItem data-pv-block="2vd0pz" value="opt2" primaryText="Option Two" secondaryText="Description for option two" />
                    {/* pv-block-end:2vd0pz */}
                    {/* pv-block-start:6e4sad */}
                    <RadioItem data-pv-block="6e4sad" value="opt3" primaryText="Option Three" secondaryText="Third option" />
                    {/* pv-block-end:6e4sad */}
                  {/* pv-editable-zone-end:jf0hi0 */}
                </RadioGroup>
                {/* pv-block-end:hbmw9o */}
              {/* pv-editable-zone-end:d3pro3 */}
            </Card>
            {/* pv-block-end:n1pq8y */}
          {/* pv-editable-zone-end:o6rx04 */}
        </Rectangle>
        {/* pv-block-end:2n40cz */}
      {/* pv-editable-zone-end:bibqg8 */}
    </div>
  );
}
