// Auto-generated by Protovibe Sketchpad

export default function Frame1() {
  return (
    <div data-layout-mode="absolute" style={{ width: '100%', height: '100%', position: 'relative' }}>
      {/* pv-editable-zone-start:gextwf */}
      {/* pv-editable-zone-end:gextwf */}
    </div>
  );
}
