import { Card } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { Rectangle } from '@/components/ui/sketchpad-rectangle'
import { Button } from '@/components/ui/button'
import { RadioGroup } from '@/components/ui/radio-group'
import { RadioItem } from '@/components/ui/radio-item'
// Auto-generated by Protovibe Sketchpad

export default function Frame2() {
  return (
    <div data-layout-mode="absolute" style={{ width: '100%', height: '100%', position: 'relative' }}>
      {/* pv-editable-zone-start:n35gru */}
        {/* pv-block-start:0cm2u4 */}
        <Card data-pv-block="0cm2u4" data-pv-sketchpad-el="0cm2u4" style={{ position: 'absolute', width: 614, left: 651, top: 54 }}>
          {/* pv-editable-zone-start:zq1ndf */}
            {/* pv-block-start:m47275 */}
            <Card data-pv-block="m47275" >
              {/* pv-editable-zone-start:j1ucae */}
                {/* pv-block-start:l3w9rp */}
                <Badge data-pv-block="l3w9rp"  label="Badge" color="primary" />
                {/* pv-block-end:l3w9rp */}
                {/* pv-block-start:86xljt */}
                <Button data-pv-block="86xljt"  label="Button" variant="solid" color="primary" size="md" />
                {/* pv-block-end:86xljt */}
                
                {/* pv-block-start:jj6rwe */}
                <Badge data-pv-block="jj6rwe"  label="Badge" color="primary" />
                {/* pv-block-end:jj6rwe */}
              {/* pv-editable-zone-end:j1ucae */}
            </Card>
            {/* pv-block-end:m47275 */}
            {/* pv-block-start:hg17z3 */}
            <Card data-pv-block="hg17z3" >
              {/* pv-editable-zone-start:j1ucae */}
              {/* pv-editable-zone-end:j1ucae */}
            </Card>
            {/* pv-block-end:hg17z3 */}

            {/* pv-block-start:38tuqy */}
            <Button data-pv-block="38tuqy"  label="Button" variant="solid" color="primary" size="md" />
            {/* pv-block-end:38tuqy */}
            
            {/* pv-block-start:2tz9ys */}
            <Badge data-pv-block="2tz9ys"  label="Badge" color="primary" />
            {/* pv-block-end:2tz9ys */}
            {/* pv-block-start:l9pa5x */}
            <Badge data-pv-block="l9pa5x"  label="Badge" color="primary" />
            {/* pv-block-end:l9pa5x */}
            
            {/* pv-block-start:hixjum */}
            <Button data-pv-block="hixjum"  label="Button" variant="solid" color="primary" size="md" />
            {/* pv-block-end:hixjum */}
          {/* pv-editable-zone-end:zq1ndf */}
        </Card>
        {/* pv-block-end:0cm2u4 */}
        
        {/* pv-block-start:xbxxe8 */}
        <RadioGroup data-pv-block="xbxxe8"  orientation="vertical" value="opt1" data-pv-sketchpad-el="xbxxe8" style={{ position: 'absolute', left: 899, top: 651 }}>
          {/* pv-editable-zone-start:ignijd */}
            {/* pv-block-start:89tcux */}
            <RadioItem data-pv-block="89tcux" value="opt1" primaryText="Option One" secondaryText="Description for option one" />
            {/* pv-block-end:89tcux */}
            {/* pv-block-start:msyhwr */}
            <RadioItem data-pv-block="msyhwr" value="opt2" primaryText="Option Two" secondaryText="Description for option two" />
            {/* pv-block-end:msyhwr */}
            {/* pv-block-start:ebyrzz */}
            <RadioItem data-pv-block="ebyrzz" value="opt3" primaryText="Option Three" secondaryText="Third option" />
            {/* pv-block-end:ebyrzz */}
          {/* pv-editable-zone-end:ignijd */}
        </RadioGroup>
        {/* pv-block-end:xbxxe8 */}
        {/* pv-block-start:jj9wgg */}
        <Rectangle data-pv-block="jj9wgg" data-pv-sketchpad-el="jj9wgg" style={{ position: 'absolute', width: 542, left: 23, top: 42 }} className="w-[200px] h-[200px]">
          {/* pv-editable-zone-start:ht918a */}
            {/* pv-block-start:oh6vig */}
            <Button data-pv-block="oh6vig"  label="Button" variant="solid" color="primary" size="md"  data-pv-sketchpad-el="oh6vig" style={{ position: 'absolute', left: 58, top: 21 }}/>
            {/* pv-block-end:oh6vig */}
            
            {/* pv-block-start:i2tkup */}
            <Button data-pv-block="i2tkup"  label="Button" variant="solid" color="primary" size="md"  data-pv-sketchpad-el="i2tkup" style={{ position: 'absolute', left: 59, top: 72 }}/>
            {/* pv-block-end:i2tkup */}
            {/* pv-block-start:dw1qsl */}
            <Button data-pv-block="dw1qsl"  label="Button" variant="solid" color="primary" size="md"  data-pv-sketchpad-el="dw1qsl" style={{ position: 'absolute', left: 250, top: 116 }}/>
            {/* pv-block-end:dw1qsl */}
          {/* pv-editable-zone-end:ht918a */}
        </Rectangle>
        {/* pv-block-end:jj9wgg */}
        
        {/* pv-block-start:yoq0ic */}
        <Card data-pv-block="yoq0ic"  data-pv-sketchpad-el="yoq0ic" style={{ position: 'absolute', left: 106, top: 360 }}>
          {/* pv-editable-zone-start:j1ucae */}
            {/* pv-block-start:coo7hq */}
            <RadioGroup data-pv-block="coo7hq"  orientation="vertical" value="opt1" >
              {/* pv-editable-zone-start:ignijd */}
                {/* pv-block-start:g7cj2k */}
                <RadioItem data-pv-block="g7cj2k" value="opt1" primaryText="Option One" secondaryText="Description for option one" />
                {/* pv-block-end:g7cj2k */}
                {/* pv-block-start:7lk036 */}
                <RadioItem data-pv-block="7lk036" value="opt2" primaryText="Option Two" secondaryText="Description for option two" />
                {/* pv-block-end:7lk036 */}
                {/* pv-block-start:565vzw */}
                <RadioItem data-pv-block="565vzw" value="opt3" primaryText="Option Three" secondaryText="Third option" />
                {/* pv-block-end:565vzw */}
              {/* pv-editable-zone-end:ignijd */}
            </RadioGroup>
            {/* pv-block-end:coo7hq */}
            
            {/* pv-block-start:abjrdi */}
            <RadioGroup data-pv-block="abjrdi"  orientation="vertical" value="opt1" >
              {/* pv-editable-zone-start:ignijd */}
                {/* pv-block-start:mwzlve */}
                <RadioItem data-pv-block="mwzlve" value="opt1" primaryText="Option One" secondaryText="Description for option one" />
                {/* pv-block-end:mwzlve */}
                {/* pv-block-start:s1z456 */}
                <RadioItem data-pv-block="s1z456" value="opt2" primaryText="Option Two" secondaryText="Description for option two" />
                {/* pv-block-end:s1z456 */}
                {/* pv-block-start:t3kk75 */}
                <RadioItem data-pv-block="t3kk75" value="opt3" primaryText="Option Three" secondaryText="Third option" />
                {/* pv-block-end:t3kk75 */}
              {/* pv-editable-zone-end:ignijd */}
            </RadioGroup>
            {/* pv-block-end:abjrdi */}
          {/* pv-editable-zone-end:j1ucae */}
        </Card>
        {/* pv-block-end:yoq0ic */}
      {/* pv-editable-zone-end:n35gru */}
    </div>
  );
}
