import { TextHeading } from '@/components/ui/text-heading'
import { TextParagraph } from '@/components/ui/text-paragraph'
import { Icon } from '@/components/ui/icon'
import { Rectangle } from '@/components/ui/sketchpad-rectangle'
import { Button } from '@/components/ui/button'
// Auto-generated by Protovibe Sketchpad

export default function Frame4() {
  return (
    <div data-layout-mode="absolute" style={{ width: '100%', height: '100%', position: 'relative' }}>
      {/* pv-editable-zone-start:kxdzso */}
        {/* pv-block-start:nstft8 */}
        <Rectangle data-pv-block="nstft8" data-pv-sketchpad-el="nstft8" style={{ position: 'absolute', height: 607, width: 702, left: 390, top: 154 }} className="w-[200px] h-[200px] bg-background-elevated">
          {/* pv-editable-zone-start:oiskll */}
            {/* pv-block-start:ggb6n6 */}
            <TextHeading data-pv-block="ggb6n6" data-pv-sketchpad-el="ggb6n6" style={{ position: 'absolute', left: 27, top: 24 }} typography="heading-md">
              Landing page
            </TextHeading>
            {/* pv-block-end:ggb6n6 */}
            {/* pv-block-start:ppinx3 */}
            <Icon className="text-foreground-success" data-pv-block="ppinx3" data-pv-sketchpad-el="ppinx3" style={{ position: 'absolute', left: 489, top: 25 }} iconSymbol="icon-park-outline:dot" size="md" />
            {/* pv-block-end:ppinx3 */}
            {/* pv-block-start:xl0dmm */}
            <TextParagraph className="text-foreground-success" data-pv-block="xl0dmm" data-pv-sketchpad-el="xl0dmm" style={{ position: 'absolute', left: 512, top: 25 }} typography="regular">
              Project is running
            </TextParagraph>
            {/* pv-block-end:xl0dmm */}
            {/* pv-block-start:wrk2v5 */}
            <Button leftIcon="ri:more-fill" iconOnly data-pv-block="wrk2v5" data-pv-sketchpad-el="wrk2v5" style={{ position: 'absolute', left: 642, top: 18 }} label="Button" variant="ghost" color="primary" size="md" />
            {/* pv-block-end:wrk2v5 */}
            {/* pv-block-start:smfeki */}
            <Rectangle data-pv-block="smfeki" data-pv-sketchpad-el="smfeki" style={{ position: 'absolute', left: 27, top: 102, height: 69, width: 635 }} className="w-[200px] h-[200px] bg-background-primary-subtle border-0">
              {/* pv-editable-zone-start:pvjfwm */}
                {/* pv-block-start:j10urn */}
                <TextParagraph className="text-foreground-secondary" data-pv-block="j10urn" data-pv-sketchpad-el="j10urn" style={{ position: 'absolute', left: 62, top: 23 }} typography="regular">
                  Open Protovibe Editor
                </TextParagraph>
                {/* pv-block-end:j10urn */}
                {/* pv-block-start:j9cvgh */}
                <Icon data-pv-block="j9cvgh" data-pv-sketchpad-el="j9cvgh" style={{ position: 'absolute', left: 22, top: 21 }} iconSymbol="majesticons:open" size="lg" />
                {/* pv-block-end:j9cvgh */}
              {/* pv-editable-zone-end:pvjfwm */}
            </Rectangle>
            {/* pv-block-end:smfeki */}
            {/* pv-block-start:y780h0 */}
            <TextParagraph className="text-foreground-secondary" data-pv-block="y780h0" data-pv-sketchpad-el="y780h0" style={{ position: 'absolute', left: 28, top: 51 }} typography="regular">
              Created 20 Dec 2028
            </TextParagraph>
            {/* pv-block-end:y780h0 */}
            {/* pv-block-start:zy5r5x */}
            <Button rightIcon="mdi:chevron-down" data-pv-block="zy5r5x" data-pv-sketchpad-el="zy5r5x" style={{ position: 'absolute', left: 33, top: 542 }} label="Show logs" variant="ghost" color="neutral" size="md" />
            {/* pv-block-end:zy5r5x */}
            {/* pv-block-start:5ciyhi */}
            <Rectangle data-pv-block="5ciyhi" data-pv-sketchpad-el="5ciyhi" style={{ position: 'absolute', left: 27, top: 186, height: 69, width: 641 }} className="w-[200px] h-[200px] border-0 bg-background-secondary">
              {/* pv-editable-zone-start:pvjfwm */}
                {/* pv-block-start:53o58g */}
                <TextParagraph className="text-foreground-secondary" data-pv-block="53o58g" data-pv-sketchpad-el="53o58g" style={{ position: 'absolute', left: 62, top: 23 }} typography="regular">
                  Open Protovibe Editor
                </TextParagraph>
                {/* pv-block-end:53o58g */}
                {/* pv-block-start:pzk0bq */}
                <Icon data-pv-block="pzk0bq" data-pv-sketchpad-el="pzk0bq" style={{ position: 'absolute', left: 22, top: 21 }} iconSymbol="majesticons:open" size="lg" />
                {/* pv-block-end:pzk0bq */}
              {/* pv-editable-zone-end:pvjfwm */}
            </Rectangle>
            {/* pv-block-end:5ciyhi */}
            {/* pv-block-start:gbbomq */}
            <Rectangle data-pv-block="gbbomq" data-pv-sketchpad-el="gbbomq" style={{ position: 'absolute', left: 29, top: 268, height: 69, width: 641 }} className="w-[200px] h-[200px] border-0 bg-background-secondary">
              {/* pv-editable-zone-start:pvjfwm */}
                {/* pv-block-start:v011ik */}
                <TextParagraph className="text-foreground-secondary" data-pv-block="v011ik" data-pv-sketchpad-el="v011ik" style={{ position: 'absolute', left: 62, top: 23 }} typography="regular">
                  Open Protovibe Editor
                </TextParagraph>
                {/* pv-block-end:v011ik */}
                {/* pv-block-start:vc7q1a */}
                <Icon data-pv-block="vc7q1a" data-pv-sketchpad-el="vc7q1a" style={{ position: 'absolute', left: 22, top: 21 }} iconSymbol="majesticons:open" size="lg" />
                {/* pv-block-end:vc7q1a */}
              {/* pv-editable-zone-end:pvjfwm */}
            </Rectangle>
            {/* pv-block-end:gbbomq */}
            {/* pv-block-start:htbic2 */}
            <Rectangle data-pv-block="htbic2" data-pv-sketchpad-el="htbic2" style={{ position: 'absolute', left: 29, top: 354, height: 69, width: 641 }} className="w-[200px] h-[200px] border-0 bg-background-secondary">
              {/* pv-editable-zone-start:pvjfwm */}
                {/* pv-block-start:4800f2 */}
                <TextParagraph className="text-foreground-secondary" data-pv-block="4800f2" data-pv-sketchpad-el="4800f2" style={{ position: 'absolute', left: 62, top: 23 }} typography="regular">
                  Open Protovibe Editor
                </TextParagraph>
                {/* pv-block-end:4800f2 */}
                {/* pv-block-start:gtuy7x */}
                <Icon data-pv-block="gtuy7x" data-pv-sketchpad-el="gtuy7x" style={{ position: 'absolute', left: 22, top: 21 }} iconSymbol="majesticons:open" size="lg" />
                {/* pv-block-end:gtuy7x */}
              {/* pv-editable-zone-end:pvjfwm */}
            </Rectangle>
            {/* pv-block-end:htbic2 */}
          {/* pv-editable-zone-end:oiskll */}
        </Rectangle>
        {/* pv-block-end:nstft8 */}
        {/* pv-block-start:epk6k8 */}
        <TextHeading data-pv-block="epk6k8" data-pv-sketchpad-el="epk6k8" style={{ position: 'absolute', left: 377, top: 13 }} typography="heading-md">
          Protovibe
        </TextHeading>
        {/* pv-block-end:epk6k8 */}
        {/* pv-block-start:eyifz9 */}
        <Button leftIcon="material-symbols:arrow-back"  data-pv-block="eyifz9" data-pv-sketchpad-el="eyifz9" style={{ position: 'absolute', left: 376, top: 86 }} label="Back to projects" variant="ghost" color="neutral" size="md" />
        {/* pv-block-end:eyifz9 */}
      {/* pv-editable-zone-end:kxdzso */}
    </div>
  );
}
