import { Rectangle } from '@/components/ui/sketchpad-rectangle'
// Auto-generated by Protovibe Sketchpad

export default function Frame2() {
  return (
    <div data-layout-mode="absolute" style={{ width: '100%', height: '100%', position: 'relative' }}>
      {/* pv-editable-zone-start:2e5rca */}
        {/* pv-block-start:mttucp */}
        <Rectangle data-pv-block="mttucp"  className="w-[200px] h-[200px]" data-pv-sketchpad-el="mttucp" style={{ position: 'absolute', width: 473, left: 129, top: 137 }}>
          {/* pv-editable-zone-start:d2ziz0 */}
            {/* pv-block-start:ksb9oo */}
            <p data-pv-block="ksb9oo" className="text-foreground-secondary" data-pv-sketchpad-el="ksb9oo" style={{ position: 'absolute', left: 38, top: 37 }}>This is the modal dialog content. Click the button below or press Escape to close.</p>
            {/* pv-block-end:ksb9oo */}
        
            {/* pv-block-start:8nwsc6 */}
            <p data-pv-block="8nwsc6" className="text-foreground-secondary" data-pv-sketchpad-el="8nwsc6" style={{ position: 'absolute', left: 66, top: 126 }}>This is the modal dialog content. Click the button below or press Escape to close.</p>
            {/* pv-block-end:8nwsc6 */}
          {/* pv-editable-zone-end:d2ziz0 */}
        </Rectangle>
        {/* pv-block-end:mttucp */}
        {/* pv-block-start:w036di */}
        <Rectangle data-pv-block="w036di"  className="w-[200px] h-[200px]" data-pv-sketchpad-el="w036di" style={{ position: 'absolute', width: 702, left: 147, top: 442 }}>
          {/* pv-editable-zone-start:d2ziz0 */}
            {/* pv-block-start:xyanr3 */}
            <p data-pv-block="xyanr3" className="text-foreground-secondary" data-pv-sketchpad-el="xyanr3" style={{ position: 'absolute', left: 38, top: 37 }}>This is the modal dialog content. Click the button below or press Escape to close.</p>
            {/* pv-block-end:xyanr3 */}
          {/* pv-editable-zone-end:d2ziz0 */}
        </Rectangle>
        {/* pv-block-end:w036di */}
      {/* pv-editable-zone-end:2e5rca */}
    </div>
  );
}
