import { Card } from '@/components/ui/card'
// Auto-generated by Protovibe Sketchpad

export default function Frame1() {
  return (
    <div data-layout-mode="absolute" style={{ width: '100%', height: '100%', position: 'relative' }}>
      {/* pv-editable-zone-start:wial0k */}
      {/* pv-editable-zone-end:wial0k */}
    </div>
  );
}
