import { TextHeading } from '@/components/ui/text-heading'
import { TextParagraph } from '@/components/ui/text-paragraph'
import { Icon } from '@/components/ui/icon'
import { Rectangle } from '@/components/ui/sketchpad-rectangle'
import { Button } from '@/components/ui/button'
// Auto-generated by Protovibe Sketchpad

export default function Frame4() {
  return (
    <div className="bg-background-sunken" data-layout-mode="absolute" style={{ width: '100%', height: '100%', position: 'relative' }}>
      {/* pv-editable-zone-start:8ngt6j */}
        {/* pv-block-start:x3twqb */}
        <Rectangle data-pv-block="x3twqb" data-pv-sketchpad-el="x3twqb" style={{ position: 'absolute', height: 607, width: 702, left: 377, top: 141 }} className="w-[200px] h-[200px] bg-background-default">
          {/* pv-editable-zone-start:kiqhby */}
            {/* pv-block-start:lcrvqe */}
            <TextHeading data-pv-block="lcrvqe" data-pv-sketchpad-el="lcrvqe" style={{ position: 'absolute', left: 27, top: 24 }} typography="heading-md">
              Landing page
            </TextHeading>
            {/* pv-block-end:lcrvqe */}
            {/* pv-block-start:fos0ml */}
            <div data-pv-block="fos0ml" className="flex flex-row bg-background-success-subtle rounded-full py-1 px-2 gap-1" data-pv-sketchpad-el="fos0ml" style={{ position: 'absolute', left: 465, top: 28 }}>
              {/* pv-editable-zone-start:nqlvho */}
              {/* pv-block-start:67c2io */}
              <Icon className="text-foreground-success" data-pv-block="67c2io"  iconSymbol="icon-park-outline:dot" size="md" />
              {/* pv-block-end:67c2io */}
              {/* pv-block-start:vyoj93 */}
              <TextParagraph className="text-foreground-success" data-pv-block="vyoj93"  typography="regular">
                Project is running
              </TextParagraph>
              {/* pv-block-end:vyoj93 */}
              {/* pv-editable-zone-end:nqlvho */}
            </div>
            {/* pv-block-end:fos0ml */}

            {/* pv-block-start:v0juws */}
            <Button leftIcon="ri:more-fill" iconOnly data-pv-block="v0juws" data-pv-sketchpad-el="v0juws" style={{ position: 'absolute', left: 638, top: 25 }} label="Button" variant="ghost" color="neutral" size="md" />
            {/* pv-block-end:v0juws */}
            {/* pv-block-start:ui7mgu */}
            <Rectangle data-pv-block="ui7mgu" data-pv-sketchpad-el="ui7mgu" style={{ position: 'absolute', left: 27, top: 102, height: 69, width: 638 }} className="w-[200px] h-[200px] bg-background-primary-subtle border-0">
              {/* pv-editable-zone-start:in18au */}
                {/* pv-block-start:mbngua */}
                <TextParagraph className="text-base text-foreground-default" data-pv-block="mbngua" data-pv-sketchpad-el="mbngua" style={{ position: 'absolute', left: 62, top: 25 }} typography="regular">
                  Open Protovibe Editor
                </TextParagraph>
                {/* pv-block-end:mbngua */}
                {/* pv-block-start:rtjaoc */}
                <Icon data-pv-block="rtjaoc" data-pv-sketchpad-el="rtjaoc" style={{ position: 'absolute', left: 22, top: 21 }} iconSymbol="majesticons:open" size="lg" />
                {/* pv-block-end:rtjaoc */}
              {/* pv-editable-zone-end:in18au */}
            </Rectangle>
            {/* pv-block-end:ui7mgu */}
            {/* pv-block-start:er9kt1 */}
            <TextParagraph className="text-foreground-secondary" data-pv-block="er9kt1" data-pv-sketchpad-el="er9kt1" style={{ position: 'absolute', left: 28, top: 51 }} typography="regular">
              Created 20 Dec 2028
            </TextParagraph>
            {/* pv-block-end:er9kt1 */}
            {/* pv-block-start:vu8dcb */}
            <Button rightIcon="mdi:chevron-down" data-pv-block="vu8dcb" data-pv-sketchpad-el="vu8dcb" style={{ position: 'absolute', left: 33, top: 542 }} label="Show logs" variant="ghost" color="neutral" size="md" />
            {/* pv-block-end:vu8dcb */}
            {/* pv-block-start:jk27dp */}
            <Rectangle data-pv-block="jk27dp" data-pv-sketchpad-el="jk27dp" style={{ position: 'absolute', left: 30, top: 261, height: 64, width: 635 }} className="w-[200px] h-[200px] border-0 bg-background-secondary">
              {/* pv-editable-zone-start:in18au */}
                {/* pv-block-start:qagr8g */}
                <TextParagraph className="text-foreground-secondary" data-pv-block="qagr8g" data-pv-sketchpad-el="qagr8g" style={{ position: 'absolute', left: 62, top: 23 }} typography="regular">
                  Restart server
                </TextParagraph>
                {/* pv-block-end:qagr8g */}
                {/* pv-block-start:zjw5ez */}
                <Icon data-pv-block="zjw5ez" data-pv-sketchpad-el="zjw5ez" style={{ position: 'absolute', left: 22, top: 21 }} iconSymbol="mdi:restart" size="lg" />
                {/* pv-block-end:zjw5ez */}
              {/* pv-editable-zone-end:in18au */}
            </Rectangle>
            {/* pv-block-end:jk27dp */}
            {/* pv-block-start:7ua2wl */}
            <Rectangle data-pv-block="7ua2wl" data-pv-sketchpad-el="7ua2wl" style={{ position: 'absolute', left: 31, top: 340, height: 69, width: 628 }} className="w-[200px] h-[200px] border-0 bg-background-secondary">
              {/* pv-editable-zone-start:in18au */}
                {/* pv-block-start:aaqnf8 */}
                <TextParagraph className="text-foreground-secondary" data-pv-block="aaqnf8" data-pv-sketchpad-el="aaqnf8" style={{ position: 'absolute', left: 62, top: 23 }} typography="regular">
                  Open in VS code
                </TextParagraph>
                {/* pv-block-end:aaqnf8 */}
                {/* pv-block-start:yi5de6 */}
                <Icon data-pv-block="yi5de6" data-pv-sketchpad-el="yi5de6" style={{ position: 'absolute', left: 22, top: 21 }} iconSymbol="material-symbols:code" size="lg" />
                {/* pv-block-end:yi5de6 */}
              {/* pv-editable-zone-end:in18au */}
            </Rectangle>
            {/* pv-block-end:7ua2wl */}
            {/* pv-block-start:5560s8 */}
            <Rectangle data-pv-block="5560s8" data-pv-sketchpad-el="5560s8" style={{ position: 'absolute', left: 33, top: 423, height: 69, width: 628 }} className="w-[200px] h-[200px] border-0 bg-background-secondary">
              {/* pv-editable-zone-start:in18au */}
                {/* pv-block-start:rdabtd */}
                <TextParagraph className="text-foreground-secondary" data-pv-block="rdabtd" data-pv-sketchpad-el="rdabtd" style={{ position: 'absolute', left: 62, top: 23 }} typography="regular">
                  Open Folder
                </TextParagraph>
                {/* pv-block-end:rdabtd */}
                {/* pv-block-start:jkmn27 */}
                <Icon data-pv-block="jkmn27" data-pv-sketchpad-el="jkmn27" style={{ position: 'absolute', left: 22, top: 21 }} iconSymbol="material-symbols:folder-outline" size="lg" />
                {/* pv-block-end:jkmn27 */}
              {/* pv-editable-zone-end:in18au */}
            </Rectangle>
            {/* pv-block-end:5560s8 */}
            {/* pv-block-start:2rrq8y */}
            <Rectangle data-pv-block="2rrq8y" data-pv-sketchpad-el="2rrq8y" style={{ position: 'absolute', left: 30, top: 185, height: 62, width: 632 }} className="w-[200px] h-[200px] border-0 bg-background-secondary">
              {/* pv-editable-zone-start:in18au */}
                {/* pv-block-start:u0zrlj */}
                <TextParagraph className="text-foreground-secondary" data-pv-block="u0zrlj" data-pv-sketchpad-el="u0zrlj" style={{ position: 'absolute', left: 57, top: 22 }} typography="regular">
                  Stop server
                </TextParagraph>
                {/* pv-block-end:u0zrlj */}
                {/* pv-block-start:6tfmjt */}
                <Icon data-pv-block="6tfmjt" data-pv-sketchpad-el="6tfmjt" style={{ position: 'absolute', left: 22, top: 21 }} iconSymbol="material-symbols:stop" size="lg" />
                {/* pv-block-end:6tfmjt */}
              {/* pv-editable-zone-end:in18au */}
            </Rectangle>
            {/* pv-block-end:2rrq8y */}
            {/* pv-block-start:61lc03 */}
            <TextParagraph className="text-foreground-tertiary" data-pv-block="61lc03" data-pv-sketchpad-el="61lc03" style={{ position: 'absolute', left: 491, top: 552 }} typography="small">
              Protovibe plugin v0.4 beta
            </TextParagraph>
            {/* pv-block-end:61lc03 */}
          {/* pv-editable-zone-end:kiqhby */}
        </Rectangle>
        {/* pv-block-end:x3twqb */}
        {/* pv-block-start:vj8asi */}
        <Rectangle data-pv-block="vj8asi" data-pv-sketchpad-el="vj8asi" style={{ position: 'absolute', height: 53, width: 1438, left: 0, top: 0 }} className="w-[200px] h-[200px] rounded-none border-t-0 border-r-0 border-b border-l-0">
          {/* pv-editable-zone-start:yuk6mh */}
            {/* pv-block-start:5wdq6n */}
            <TextHeading data-pv-block="5wdq6n" data-pv-sketchpad-el="5wdq6n" style={{ position: 'absolute', left: 29, top: 12 }} typography="heading-md">
              Protovibe
            </TextHeading>
            {/* pv-block-end:5wdq6n */}
            {/* pv-block-start:j8yk8w */}
            <TextParagraph className="text-foreground-tertiary" data-pv-block="j8yk8w" data-pv-sketchpad-el="j8yk8w" style={{ position: 'absolute', left: 1271, top: 19 }} typography="small">
              Version. 0.4 beta
            </TextParagraph>
            {/* pv-block-end:j8yk8w */}
            {/* pv-block-start:y390lp */}
            <Button leftIcon="material-symbols:help-outline" iconOnly data-pv-block="y390lp" data-pv-sketchpad-el="y390lp" style={{ position: 'absolute', left: 1386, top: 5 }} label="Button" variant="ghost" color="neutral" size="lg" />
            {/* pv-block-end:y390lp */}
          {/* pv-editable-zone-end:yuk6mh */}
        </Rectangle>
        {/* pv-block-end:vj8asi */}
        {/* pv-block-start:53ic1c */}
        <Button leftIcon="material-symbols:arrow-back"  data-pv-block="53ic1c" data-pv-sketchpad-el="53ic1c" style={{ position: 'absolute', left: 376, top: 86 }} label="Back to projects" variant="ghost" color="neutral" size="md" />
        {/* pv-block-end:53ic1c */}
      {/* pv-editable-zone-end:8ngt6j */}
    </div>
  );
}
