import { Input } from '@/components/ui/input'
import { SuperLabel } from '@/components/ui/super-label'
import { TextHeading } from '@/components/ui/text-heading'
import { Button } from '@/components/ui/button'
import { TextParagraph } from '@/components/ui/text-paragraph'
import { Icon } from '@/components/ui/icon'
import { Rectangle } from '@/components/ui/sketchpad-rectangle'
import { VerticalLine } from '@/components/ui/sketchpad-vertical-line'
import { HorizontalLine } from '@/components/ui/sketchpad-horizontal-line'
import { Card } from '@/components/ui/card'
import { Image } from '@/components/ui/image'
// Auto-generated by Protovibe Sketchpad

export default function Frame12() {
  return (
    <div className="overflow-hidden" data-layout-mode="absolute" style={{ width: '100%', height: '100%', position: 'relative' }}>
      {/* pv-editable-zone-start:3ubuxh */}
        {/* pv-block-start:8dynul */}
        <Input data-pv-block="8dynul" data-pv-sketchpad-el="8dynul" style={{ position: 'absolute', width: 332, left: 169, top: 236 }} placeholder="" />
        {/* pv-block-end:8dynul */}
        {/* pv-block-start:atjzo7 */}
        <SuperLabel data-pv-block="atjzo7" data-pv-sketchpad-el="atjzo7" style={{ position: 'absolute', left: 169, top: 208 }} primaryText="Email or username" />
        {/* pv-block-end:atjzo7 */}
        {/* pv-block-start:574z1k */}
        <TextHeading data-pv-block="574z1k" data-pv-sketchpad-el="574z1k" style={{ position: 'absolute', left: 169, top: 139 }} typography="heading-md">
          Login to EvilCorp
        </TextHeading>
        {/* pv-block-end:574z1k */}
        {/* pv-block-start:3fn7mn */}
        <SuperLabel data-pv-block="3fn7mn" data-pv-sketchpad-el="3fn7mn" style={{ position: 'absolute', left: 169, top: 295 }} primaryText="Password" />
        {/* pv-block-end:3fn7mn */}
        
        {/* pv-block-start:4vts8v */}
        <Input data-pv-block="4vts8v" data-pv-sketchpad-el="4vts8v" style={{ position: 'absolute', left: 169, top: 323, width: 332 }} placeholder="" />
        {/* pv-block-end:4vts8v */}
        {/* pv-block-start:4fg2im */}
        <SuperLabel data-pv-block="4fg2im" data-pv-sketchpad-el="4fg2im" style={{ position: 'absolute', left: 309, top: 428 }} primaryText="— OR —" />
        {/* pv-block-end:4fg2im */}
        {/* pv-block-start:r4xwg4 */}
        <Button data-pv-block="r4xwg4" data-pv-sketchpad-el="r4xwg4" style={{ position: 'absolute', width: 332, left: 169, top: 372 }} label="Sign in" variant="solid" color="primary" size="md" />
        {/* pv-block-end:r4xwg4 */}
        {/* pv-block-start:y8cpan */}
        <Button leftIcon="ion:logo-google" data-pv-block="y8cpan" data-pv-sketchpad-el="y8cpan" style={{ position: 'absolute', left: 170, top: 468, width: 332 }} label="Continue with Google" variant="solid" color="neutral" size="md" />
        {/* pv-block-end:y8cpan */}
        {/* pv-block-start:44rkki */}
        <Button leftIcon="radix-icons:github-logo" data-pv-block="44rkki" data-pv-sketchpad-el="44rkki" style={{ position: 'absolute', left: 170, top: 520, width: 332 }} label="Continue with GitHub" variant="solid" color="neutral" size="md" />
        {/* pv-block-end:44rkki */}
        {/* pv-block-start:dgd9df */}
        <TextHeading data-pv-block="dgd9df" data-pv-sketchpad-el="dgd9df" style={{ position: 'absolute', width: 82, left: 67, top: 30 }} typography="heading-md">
          EvilCorp
        </TextHeading>
        {/* pv-block-end:dgd9df */}
        {/* pv-block-start:n0mcq4 */}
        <TextParagraph data-pv-block="n0mcq4" data-pv-sketchpad-el="n0mcq4" style={{ position: 'absolute', left: 169, top: 30 }} typography="regular">
          To take over the world!
        </TextParagraph>
        {/* pv-block-end:n0mcq4 */}
        {/* pv-block-start:poz5eh */}
        <Icon data-pv-block="poz5eh" data-pv-sketchpad-el="poz5eh" style={{ position: 'absolute', width: 20, left: 33, top: 29 }} iconSymbol="fluent-emoji-high-contrast:see-no-evil-monkey" size="lg" />
        {/* pv-block-end:poz5eh */}
        {/* pv-block-start:mu0unz */}
        <div data-pv-block="mu0unz" data-pv-sketchpad-el="mu0unz" style={{ position: 'absolute', left: 365, top: -54 }} className="w-full bg-[url('/src/images/from-protovibe/image-3.png')] bg-contain bg-center bg-no-repeat aspect-[995/917]" />
        {/* pv-block-end:mu0unz */}
        {/* pv-block-start:ny6dao */}
        <Rectangle data-pv-block="ny6dao" data-pv-sketchpad-el="ny6dao" style={{ position: 'absolute', height: 893, width: 768, left: 670, top: 2 }} className="w-[200px] h-[200px] overflow-hidden border-0 rounded-none bg-transparent">
          {/* pv-editable-zone-start:69fbo3 */}
            {/* pv-block-start:km1api */}
            <div data-pv-block="km1api" data-pv-sketchpad-el="km1api" style={{ position: 'absolute', width: 1065, left: 117, top: 162 }} className="w-full bg-[url('/src/images/from-protovibe/image-2.png')] bg-contain bg-center bg-no-repeat aspect-[565/537]" />
            {/* pv-block-end:km1api */}

            {/* pv-block-start:2ohg6c */}
            <div data-pv-block="2ohg6c" data-pv-sketchpad-el="2ohg6c" style={{ position: 'absolute', width: 1065, left: 241, top: 304 }} className="w-full bg-[url('/src/images/from-protovibe/image-2.png')] bg-contain bg-center bg-no-repeat aspect-[565/537]" />
            {/* pv-block-end:2ohg6c */}
          {/* pv-editable-zone-end:69fbo3 */}
        </Rectangle>
        {/* pv-block-end:ny6dao */}
        {/* pv-block-start:e4gqhr */}
        <VerticalLine data-pv-block="e4gqhr" data-pv-sketchpad-el="e4gqhr" style={{ position: 'absolute', height: 20, left: 154, top: 32 }} className="w-[4px] h-[200px]">
          {/* pv-editable-zone-start:sqjwhd */}
          {/* pv-editable-zone-end:sqjwhd */}
        </VerticalLine>
        {/* pv-block-end:e4gqhr */}
        {/* pv-block-start:lic3hc */}
        <TextParagraph className="flex flex-row gap-1 items-center bg-transparent justify-center rounded-none" data-pv-block="lic3hc" data-pv-sketchpad-el="lic3hc" style={{ position: 'absolute', width: 328, left: 173, top: 582 }} typography="regular">
          Don't have account? <a href="https://" target="_blank" rel="noopener noreferrer" className="text-foreground-primary-link hover:opacity-80 transition-opacity">Sign up</a>
        </TextParagraph>
        {/* pv-block-end:lic3hc */}
        {/* pv-block-start:eq74v6 */}
        <TextParagraph className="text-tiny text-foreground-tertiary" data-pv-block="eq74v6" data-pv-sketchpad-el="eq74v6" style={{ position: 'absolute', width: 331, left: 173, top: 733 }} typography="small">
          By logging in you accept EvilCorop terms of services.
        </TextParagraph>
        {/* pv-block-end:eq74v6 */}
        {/* pv-block-start:gk2qgn */}
        <HorizontalLine data-pv-block="gk2qgn" data-pv-sketchpad-el="gk2qgn" style={{ position: 'absolute', width: 321, left: 173, top: 710 }} className="w-[200px] h-[4px]">
          {/* pv-editable-zone-start:wwkua1 */}
          {/* pv-editable-zone-end:wwkua1 */}
        </HorizontalLine>
        {/* pv-block-end:gk2qgn */}
      {/* pv-editable-zone-end:3ubuxh */}
    </div>
  );
}
