import { Input } from '@/components/ui/input'
import { SuperLabel } from '@/components/ui/super-label'
import { TextHeading } from '@/components/ui/text-heading'
import { Button } from '@/components/ui/button'
import { TextParagraph } from '@/components/ui/text-paragraph'
import { Icon } from '@/components/ui/icon'
import { Rectangle } from '@/components/ui/sketchpad-rectangle'
import { VerticalLine } from '@/components/ui/sketchpad-vertical-line'
import { HorizontalLine } from '@/components/ui/sketchpad-horizontal-line'
import { Card } from '@/components/ui/card'
// Auto-generated by Protovibe Sketchpad

export default function Frame12() {
  return (
    <div className="" data-layout-mode="absolute" style={{ width: '100%', height: '100%', position: 'relative' }}>
      {/* pv-editable-zone-start:zxmiww */}
        {/* pv-block-start:pxtdjn */}
        <Input data-pv-block="pxtdjn" data-pv-sketchpad-el="pxtdjn" style={{ position: 'absolute', width: 332, left: 552, top: 217 }} placeholder="" />
        {/* pv-block-end:pxtdjn */}
        {/* pv-block-start:f5g9ws */}
        <SuperLabel data-pv-block="f5g9ws" data-pv-sketchpad-el="f5g9ws" style={{ position: 'absolute', left: 552, top: 189 }} primaryText="Email or username" />
        {/* pv-block-end:f5g9ws */}
        {/* pv-block-start:26eh6a */}
        <TextHeading data-pv-block="26eh6a" data-pv-sketchpad-el="26eh6a" style={{ position: 'absolute', left: 552, top: 120 }} typography="heading-md">
          Login to EvilCorp
        </TextHeading>
        {/* pv-block-end:26eh6a */}
        {/* pv-block-start:08nex9 */}
        <SuperLabel data-pv-block="08nex9" data-pv-sketchpad-el="08nex9" style={{ position: 'absolute', left: 552, top: 276 }} primaryText="Password" />
        {/* pv-block-end:08nex9 */}
        
        {/* pv-block-start:fk43ly */}
        <Input data-pv-block="fk43ly" data-pv-sketchpad-el="fk43ly" style={{ position: 'absolute', left: 552, top: 304, width: 332 }} placeholder="" />
        {/* pv-block-end:fk43ly */}
        {/* pv-block-start:lywlh8 */}
        <SuperLabel data-pv-block="lywlh8" data-pv-sketchpad-el="lywlh8" style={{ position: 'absolute', left: 692, top: 409 }} primaryText="— OR —" />
        {/* pv-block-end:lywlh8 */}
        {/* pv-block-start:y2nug4 */}
        <Button data-pv-block="y2nug4" data-pv-sketchpad-el="y2nug4" style={{ position: 'absolute', width: 332, left: 552, top: 353 }} label="Sign in" variant="solid" color="primary" size="md" />
        {/* pv-block-end:y2nug4 */}
        {/* pv-block-start:ybaxed */}
        <Button leftIcon="ion:logo-google" data-pv-block="ybaxed" data-pv-sketchpad-el="ybaxed" style={{ position: 'absolute', left: 553, top: 449, width: 332 }} label="Continue with Google" variant="solid" color="neutral" size="md" />
        {/* pv-block-end:ybaxed */}
        {/* pv-block-start:gner9f */}
        <Button leftIcon="radix-icons:github-logo" data-pv-block="gner9f" data-pv-sketchpad-el="gner9f" style={{ position: 'absolute', left: 553, top: 501, width: 332 }} label="Continue with GitHub" variant="solid" color="neutral" size="md" />
        {/* pv-block-end:gner9f */}
        {/* pv-block-start:h1m7c5 */}
        <TextHeading data-pv-block="h1m7c5" data-pv-sketchpad-el="h1m7c5" style={{ position: 'absolute', width: 82, left: 67, top: 30 }} typography="heading-md">
          EvilCorp
        </TextHeading>
        {/* pv-block-end:h1m7c5 */}
        {/* pv-block-start:fbhl05 */}
        <TextParagraph data-pv-block="fbhl05" data-pv-sketchpad-el="fbhl05" style={{ position: 'absolute', left: 169, top: 30 }} typography="regular">
          To take over the world!
        </TextParagraph>
        {/* pv-block-end:fbhl05 */}
        {/* pv-block-start:hqg44d */}
        <Icon data-pv-block="hqg44d" data-pv-sketchpad-el="hqg44d" style={{ position: 'absolute', width: 20, left: 33, top: 29 }} iconSymbol="fluent-emoji-high-contrast:see-no-evil-monkey" size="lg" />
        {/* pv-block-end:hqg44d */}
        {/* pv-block-start:j2da79 */}
        <div data-pv-block="j2da79" data-pv-sketchpad-el="j2da79" style={{ position: 'absolute', width: 1123, left: 692, top: 276 }} className="w-full bg-[url('/src/images/from-protovibe/image-3.png')] bg-contain bg-center bg-no-repeat aspect-[995/917]" />
        {/* pv-block-end:j2da79 */}
        {/* pv-block-start:4cmqc0 */}
        <VerticalLine data-pv-block="4cmqc0" data-pv-sketchpad-el="4cmqc0" style={{ position: 'absolute', height: 20, left: 154, top: 32 }} className="w-[4px] h-[200px]">
          {/* pv-editable-zone-start:awo9xm */}
          {/* pv-editable-zone-end:awo9xm */}
        </VerticalLine>
        {/* pv-block-end:4cmqc0 */}
        {/* pv-block-start:lals6g */}
        <TextParagraph className="flex flex-row gap-1 items-center bg-transparent justify-center rounded-none" data-pv-block="lals6g" data-pv-sketchpad-el="lals6g" style={{ position: 'absolute', width: 328, left: 556, top: 563 }} typography="regular">
          Don't have account? <a href="https://" target="_blank" rel="noopener noreferrer" className="text-foreground-primary-link hover:opacity-80 transition-opacity">Sign up</a>
        </TextParagraph>
        {/* pv-block-end:lals6g */}
        {/* pv-block-start:o4hab4 */}
        <TextParagraph className="text-tiny text-foreground-tertiary" data-pv-block="o4hab4" data-pv-sketchpad-el="o4hab4" style={{ position: 'absolute', width: 331, left: 556, top: 714 }} typography="small">
          By logging in you accept EvilCorop terms of services.
        </TextParagraph>
        {/* pv-block-end:o4hab4 */}
        {/* pv-block-start:fsa54s */}
        <HorizontalLine data-pv-block="fsa54s" data-pv-sketchpad-el="fsa54s" style={{ position: 'absolute', width: 321, left: 556, top: 691 }} className="w-[200px] h-[4px]">
          {/* pv-editable-zone-start:o78zyc */}
          {/* pv-editable-zone-end:o78zyc */}
        </HorizontalLine>
        {/* pv-block-end:fsa54s */}
      {/* pv-editable-zone-end:zxmiww */}
    </div>
  );
}
