// Auto-generated by Protovibe Sketchpad
import { Rectangle } from '@/components/ui/sketchpad-rectangle';
import { TextHeading } from '@/components/ui/text-heading';
import { TextParagraph } from '@/components/ui/text-paragraph';

export default function Frame1() {
  return (
    <div data-layout-mode="absolute" style={{ width: '100%', height: '100%', position: 'relative' }}>
      {/* pv-editable-zone-start:0owew4 */}
      {/* pv-block-start:te1asy */}
      <Rectangle data-pv-block="te1asy" data-pv-sketchpad-el="te1asy" className="w-[200px] h-[200px]" style={{ position: 'absolute', left: 231, top: 95 }}>
        {/* pv-editable-zone-start:8zwpb0 */}
          {/* pv-block-start:mswr2t */}
          <TextHeading data-pv-block="mswr2t" data-pv-sketchpad-el="mswr2t" typography="heading-md" style={{ position: 'absolute', left: 27, top: 21 }}>
            Heading
          </TextHeading>
          {/* pv-block-end:mswr2t */}
          {/* pv-block-start:gyfjf8 */}
          <TextParagraph data-pv-block="gyfjf8" data-pv-sketchpad-el="gyfjf8" typography="regular" style={{ position: 'absolute', left: 28, top: 48 }}>
            Paragraph text
          </TextParagraph>
          {/* pv-block-end:gyfjf8 */}
        {/* pv-editable-zone-end:8zwpb0 */}
      </Rectangle>
      {/* pv-block-end:te1asy */}
      {/* pv-editable-zone-end:0owew4 */}
    </div>
  );
}
