import { Input } from '@/components/ui/input'
import { SuperLabel } from '@/components/ui/super-label'
import { TextHeading } from '@/components/ui/text-heading'
import { Button } from '@/components/ui/button'
import { TextParagraph } from '@/components/ui/text-paragraph'
import { Icon } from '@/components/ui/icon'
import { Rectangle } from '@/components/ui/sketchpad-rectangle'
import { VerticalLine } from '@/components/ui/sketchpad-vertical-line'
import { HorizontalLine } from '@/components/ui/sketchpad-horizontal-line'
import { Card } from '@/components/ui/card'
import { Image } from '@/components/ui/image'
// Auto-generated by Protovibe Sketchpad

export default function Frame12() {
  return (
    <div className="overflow-hidden" data-layout-mode="absolute" style={{ width: '100%', height: '100%', position: 'relative' }}>
      {/* pv-editable-zone-start:mjhqpl */}
        {/* pv-block-start:ba0hce */}
        <span className="text-4xl font-bold" data-pv-block="ba0hce" data-pv-sketchpad-el="ba0hce" style={{ position: 'absolute', left: 325, top: 145 }}>
          Welcome to Sketchpads!
        </span>
        {/* pv-block-end:ba0hce */}
        {/* pv-block-start:ey6z9r */}
        <span className="font-normal text-3xl text-foreground-secondary" data-pv-block="ey6z9r"  data-pv-sketchpad-el="ey6z9r" style={{ position: 'absolute', width: 728, left: 388, top: 220 }}>
          Here you can design like a human in a familiar infinite canvas interface. But you can use real React components here.
        </span>
        {/* pv-block-end:ey6z9r */}
        {/* pv-block-start:svcose */}
        <div data-pv-block="svcose" data-pv-sketchpad-el="svcose" style={{ position: 'absolute', left: -51, top: 399, width: 1541 }} className="w-full bg-[url('/src/images/from-protovibe/image-4.png')] bg-contain bg-center bg-no-repeat aspect-[1935/1612]">
          {/* pv-editable-zone-start:60suys */}
          {/* pv-editable-zone-end:60suys */}
        </div>
        {/* pv-block-end:svcose */}
        {/* pv-block-start:sw1cpp */}
        <span className="font-normal text-3xl text-foreground-secondary" data-pv-block="sw1cpp"  data-pv-sketchpad-el="sw1cpp" style={{ position: 'absolute', left: 388, top: 321, width: 728 }}>
          Double-click to select children. Hold Cmd and click to directly select the deepest child.
        </span>
        {/* pv-block-end:sw1cpp */}
        {/* pv-block-start:20c6x7 */}
        <Icon className="text-foreground-primary" data-pv-block="20c6x7" data-pv-sketchpad-el="20c6x7" style={{ position: 'absolute', left: 323, top: 321 }} iconSymbol="material-symbols:mouse" size="2xl" />
        {/* pv-block-end:20c6x7 */}
        {/* pv-block-start:0az2kb */}
        <Icon className="text-foreground-primary" data-pv-block="0az2kb" data-pv-sketchpad-el="0az2kb" style={{ position: 'absolute', width: 38, left: 325, top: 220 }} iconSymbol="tabler:bulb" size="2xl" />
        {/* pv-block-end:0az2kb */}
      {/* pv-editable-zone-end:mjhqpl */}
    </div>
  );
}
