import { Image } from '@/components/ui/image'
import { Card } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Rectangle } from '@/components/ui/sketchpad-rectangle'
import { TextHeading } from '@/components/ui/text-heading'
import { TextParagraph } from '@/components/ui/text-paragraph'
import { Icon } from '@/components/ui/icon'
import { Input } from '@/components/ui/input'
// Auto-generated by Protovibe Sketchpad

export default function Frame2() {
  return (
    <div data-layout-mode="absolute" style={{ width: '100%', height: '100%', position: 'relative' }}>
      {/* pv-editable-zone-start:jr37z0 */}
      {/* pv-block-start:j94omq */}
      <Card data-pv-block="j94omq" data-pv-sketchpad-el="j94omq"  style={{ position: 'absolute', left: 103, top: 78, width: 330 }}>
        {/* pv-editable-zone-start:jxr5ey */}
        {/* pv-block-start:3linjw */}
      <Button data-pv-block="3linjw" label="Button" variant="solid" color="primary" size="md" />
      {/* pv-block-end:3linjw */}

        {/* pv-block-start:uu2qp0 */}
      <div data-pv-block="uu2qp0" className="flex flex-col gap-2" >
        {/* pv-editable-zone-start:1r8mze */}
        {/* pv-block-start:xfk88y */}
        <Image randomImage data-pv-block="xfk88y" className="bg-[url('/src/images/from-protovibe/image-placeholder.svg')] bg-cover bg-center bg-no-repeat aspect-video w-full" style={{ width: 178 }} />
        {/* pv-block-end:xfk88y */}
        {/* pv-editable-zone-end:1r8mze */}
      </div>
      {/* pv-block-end:uu2qp0 */}

        {/* pv-block-start:1wvkzj */}
      <Button data-pv-block="1wvkzj" label="Button" variant="solid" color="primary" size="md" />
      {/* pv-block-end:1wvkzj */}
        {/* pv-editable-zone-end:jxr5ey */}
      </Card>
      {/* pv-block-end:j94omq */}

      {/* pv-block-start:g3lj6s */}
      <div data-pv-block="g3lj6s" className="flex flex-col gap-2" data-pv-sketchpad-el="g3lj6s" style={{ position: 'absolute', left: 690, top: 91 }}>
        {/* pv-editable-zone-start:1r8mze */}
        {/* pv-block-start:ip7d8c */}
        <Image randomImage data-pv-block="ip7d8c" className="bg-[url('/src/images/from-protovibe/image-placeholder.svg')] bg-cover bg-center bg-no-repeat aspect-video w-full" style={{ width: 178 }} />
        {/* pv-block-end:ip7d8c */}
        {/* pv-editable-zone-end:1r8mze */}
      </div>
      {/* pv-block-end:g3lj6s */}
      
      {/* pv-block-start:yw7158 */}
      <div data-pv-block="yw7158" className="flex flex-col gap-2" data-pv-sketchpad-el="yw7158" style={{ position: 'absolute', left: 355, top: 454 }}>
        {/* pv-editable-zone-start:1r8mze */}
        {/* pv-block-start:x5b3rz */}
        <Image randomImage data-pv-block="x5b3rz" className="bg-[url('/src/images/from-protovibe/image-placeholder.svg')] bg-cover bg-center bg-no-repeat aspect-video w-full" style={{ width: 178 }} />
        {/* pv-block-end:x5b3rz */}
        {/* pv-editable-zone-end:1r8mze */}
      </div>
      {/* pv-block-end:yw7158 */}

      {/* pv-block-start:44told */}
      <div data-pv-block="44told" className="flex flex-col gap-2" data-pv-sketchpad-el="44told" style={{ position: 'absolute', left: 515, top: 267 }}>
        {/* pv-editable-zone-start:1r8mze */}
        {/* pv-block-start:gao1dk */}
        <Image randomImage data-pv-block="gao1dk" className="bg-[url('/src/images/from-protovibe/image-placeholder.svg')] bg-cover bg-center bg-no-repeat aspect-video w-full" style={{ width: 178 }} />
        {/* pv-block-end:gao1dk */}
        {/* pv-editable-zone-end:1r8mze */}
      </div>
      {/* pv-block-end:44told */}
      
      {/* pv-block-start:b12ofv */}
      <div data-pv-block="b12ofv" className="flex flex-col gap-2" data-pv-sketchpad-el="b12ofv" style={{ position: 'absolute', left: 576, top: 647 }}>
        {/* pv-editable-zone-start:1r8mze */}
        {/* pv-block-start:n9aiev */}
        <Image randomImage data-pv-block="n9aiev" className="bg-[url('/src/images/from-protovibe/image-placeholder.svg')] bg-cover bg-center bg-no-repeat aspect-video w-full" style={{ width: 178 }} />
        {/* pv-block-end:n9aiev */}
        {/* pv-editable-zone-end:1r8mze */}
      </div>
      {/* pv-block-end:b12ofv */}
      
      {/* pv-block-start:7kg73j */}
      <div data-pv-block="7kg73j" className="flex flex-col gap-2" data-pv-sketchpad-el="7kg73j" style={{ position: 'absolute', left: 579, top: 441 }}>
        {/* pv-editable-zone-start:1r8mze */}
        {/* pv-block-start:ffvgdj */}
        <Image randomImage data-pv-block="ffvgdj" className="bg-[url('/src/images/from-protovibe/image-placeholder.svg')] bg-cover bg-center bg-no-repeat aspect-video w-full" style={{ width: 178 }} />
        {/* pv-block-end:ffvgdj */}
        {/* pv-editable-zone-end:1r8mze */}
      </div>
      {/* pv-block-end:7kg73j */}
      
      {/* pv-block-start:slc31y */}
      <Button data-pv-block="slc31y" label="Button" variant="solid" color="primary" size="md"  data-pv-sketchpad-el="slc31y" style={{ position: 'absolute', left: 568, top: 86 }}/>
      {/* pv-block-end:slc31y */}
      
      {/* pv-block-start:cii084 */}
      <Button data-pv-block="cii084" label="Button" variant="solid" color="primary" size="md"  data-pv-sketchpad-el="cii084" style={{ position: 'absolute', left: 468, top: 85 }}/>
      {/* pv-block-end:cii084 */}

      {/* pv-block-start:rk4eze */}
      <Rectangle data-pv-block="rk4eze" data-pv-sketchpad-el="rk4eze" className="w-[200px] h-[200px]" style={{ position: 'absolute', left: 926, top: 95, height: 405, width: 398 }}>
        {/* pv-editable-zone-start:lgg850 */}
        {/* pv-block-start:f50wjy */}
      <Rectangle data-pv-block="f50wjy" data-pv-sketchpad-el="f50wjy" className="w-[200px] h-[200px]" style={{ position: 'absolute', left: 19, top: 27, height: 224, width: 242 }}>
        {/* pv-editable-zone-start:0dyfc5 */}
        {/* pv-block-start:m6aplx */}
      <Button data-pv-block="m6aplx" label="Button" variant="solid" color="primary" size="md"  data-pv-sketchpad-el="m6aplx" style={{ position: 'absolute', width: 163, left: 31, top: 25 }}/>
      {/* pv-block-end:m6aplx */}

        {/* pv-block-start:wxhw3h */}
      <div data-pv-block="wxhw3h" className="flex flex-col gap-2" data-pv-sketchpad-el="wxhw3h" style={{ position: 'absolute', left: 37, top: 79, width: 245 }}>
        {/* pv-editable-zone-start:1r8mze */}
        {/* pv-block-start:qulzoh */}
        <Image randomImage data-pv-block="qulzoh" className="bg-[url('/src/images/from-protovibe/image-placeholder.svg')] bg-cover bg-center bg-no-repeat aspect-video w-full" style={{ width: 178 }} />
        {/* pv-block-end:qulzoh */}
        {/* pv-editable-zone-end:1r8mze */}
      </div>
      {/* pv-block-end:wxhw3h */}
        {/* pv-editable-zone-end:0dyfc5 */}
      </Rectangle>
      {/* pv-block-end:f50wjy */}
        {/* pv-editable-zone-end:lgg850 */}
      </Rectangle>
      {/* pv-block-end:rk4eze */}
      
      {/* pv-block-start:q2qzgb */}
      <Card data-pv-block="q2qzgb" data-pv-sketchpad-el="q2qzgb"  style={{ position: 'absolute', width: 321, left: 922, top: 556 }}>
        {/* pv-editable-zone-start:d3mff8 */}

        {/* pv-block-start:k7m9p2 */}
        <TextHeading data-pv-block="k7m9p2" typography="heading-md">Sign In</TextHeading>
        {/* pv-block-end:k7m9p2 */}

        {/* pv-block-start:r5x8f1 */}
        <div data-pv-block="r5x8f1" className="flex flex-col gap-3 w-full">
          {/* pv-editable-zone-start:n2h5j8 */}

          {/* pv-block-start:w2q9m3 */}
          <Input data-pv-block="w2q9m3" type="email" placeholder="Email address" />
          {/* pv-block-end:w2q9m3 */}

          {/* pv-block-start:h8j4n6 */}
          <Input data-pv-block="h8j4n6" type="password" placeholder="Password" />
          {/* pv-block-end:h8j4n6 */}

          {/* pv-editable-zone-end:n2h5j8 */}
        </div>
        {/* pv-block-end:r5x8f1 */}

        {/* pv-block-start:b1t3c7 */}
        <Button data-pv-block="b1t3c7" label="Sign In" variant="solid" color="primary" />
        {/* pv-block-end:b1t3c7 */}

        {/* pv-editable-zone-end:d3mff8 */}
      </Card>
      {/* pv-block-end:q2qzgb */}
      {/* pv-editable-zone-end:jr37z0 */}
    </div>
  );
}
