import { Image } from '@/components/ui/image'
import { Avatar } from '@/components/ui/avatar'
import { Button } from '@/components/ui/button'
import { Checkbox } from '@/components/ui/checkbox'
import { Rectangle } from '@/components/ui/sketchpad-rectangle'
import { Badge } from '@/components/ui/badge'
// Auto-generated by Protovibe Sketchpad

export default function Frame14() {
  return (
    <div data-layout-mode="absolute" style={{ width: '100%', height: '100%', position: 'relative' }}>
      {/* pv-editable-zone-start:evl0zh */}
        {/* pv-block-start:gus31d */}
        <Avatar data-pv-block="gus31d" data-pv-sketchpad-el="gus31d" style={{ position: 'absolute', left: 202, top: 181 }} initials="AB" size="md" bgColor="default" imageSrc="https://i.pravatar.cc/60" />
        {/* pv-block-end:gus31d */}
        {/* pv-block-start:24hqfc */}
        <div data-pv-block="24hqfc" data-pv-sketchpad-el="24hqfc" style={{ position: 'absolute', left: 123, top: 490, width: 536 }} className="w-full bg-contain bg-center bg-no-repeat bg-[url('/src/images/from-protovibe/screenshot-2026-05-01-at-070444.png')] aspect-[664/401]" />
        {/* pv-block-end:24hqfc */}
        {/* pv-block-start:ncyl8a */}
        <Rectangle data-pv-block="ncyl8a" data-pv-sketchpad-el="ncyl8a" style={{ position: 'absolute', width: 237, height: 249, left: 895, top: 112 }} className="w-[200px] h-[200px] bg-background-secondary">
          {/* pv-editable-zone-start:ex6zsf */}
            {/* pv-block-start:qvgssg */}
            <Avatar data-pv-block="qvgssg" data-pv-sketchpad-el="qvgssg" style={{ position: 'absolute', left: 21, top: 12 }} initials="AB" size="md" bgColor="default" imageSrc="https://i.pravatar.cc/60" />
            {/* pv-block-end:qvgssg */}
            {/* pv-block-start:48cdhn */}
            <span className="font-bold" data-pv-block="48cdhn" data-pv-sketchpad-el="48cdhn" style={{ position: 'absolute', left: 22, top: 61 }}>Lorem ipsum</span>
            {/* pv-block-end:48cdhn */}
            {/* pv-block-start:rzq9pg */}
            <Button data-pv-block="rzq9pg" data-pv-sketchpad-el="rzq9pg" style={{ position: 'absolute', left: 22, top: 190 }} label="Button" variant="solid" color="primary" size="md" />
            {/* pv-block-end:rzq9pg */}
            {/* pv-block-start:sbbosd */}
            <Checkbox data-pv-block="sbbosd" data-pv-sketchpad-el="sbbosd" style={{ position: 'absolute', left: 22, top: 149 }} primaryText="Check this out" />
            {/* pv-block-end:sbbosd */}
            {/* pv-block-start:jbbvot */}
            <Badge data-pv-block="jbbvot" data-pv-sketchpad-el="jbbvot" style={{ position: 'absolute', left: 130, top: 20 }} label="Badge" color="primary" />
            {/* pv-block-end:jbbvot */}
            {/* pv-block-start:3etwtb */}
            <span className="font-normal text-base" data-pv-block="3etwtb" data-pv-sketchpad-el="3etwtb" style={{ position: 'absolute', width: 166, left: 22, top: 91 }}>
              Secondary text that can take multiple lines
            </span>
            {/* pv-block-end:3etwtb */}
          {/* pv-editable-zone-end:ex6zsf */}
        </Rectangle>
        {/* pv-block-end:ncyl8a */}
        {/* pv-block-start:023d7s */}
        <Rectangle data-pv-block="023d7s" data-pv-sketchpad-el="023d7s" style={{ position: 'absolute', left: 581, top: 112, width: 237, height: 249 }} className="w-[200px] h-[200px] bg-background-secondary">
          {/* pv-editable-zone-start:ex6zsf */}
            {/* pv-block-start:9744bk */}
            <Avatar data-pv-block="9744bk" data-pv-sketchpad-el="9744bk" style={{ position: 'absolute', left: 21, top: 12 }} initials="AB" size="md" bgColor="default" imageSrc="https://i.pravatar.cc/60" />
            {/* pv-block-end:9744bk */}
            {/* pv-block-start:8c8qkh */}
            <span className="font-bold" data-pv-block="8c8qkh" data-pv-sketchpad-el="8c8qkh" style={{ position: 'absolute', left: 22, top: 61 }}>Lorem ipsum</span>
            {/* pv-block-end:8c8qkh */}
            {/* pv-block-start:6xjwu5 */}
            <Button data-pv-block="6xjwu5" data-pv-sketchpad-el="6xjwu5" style={{ position: 'absolute', left: 22, top: 190 }} label="Button" variant="solid" color="primary" size="md" />
            {/* pv-block-end:6xjwu5 */}
            {/* pv-block-start:fi6jse */}
            <Checkbox data-pv-block="fi6jse" data-pv-sketchpad-el="fi6jse" style={{ position: 'absolute', left: 22, top: 149 }} primaryText="Check this out" />
            {/* pv-block-end:fi6jse */}
            {/* pv-block-start:26xsul */}
            <Badge data-pv-block="26xsul" data-pv-sketchpad-el="26xsul" style={{ position: 'absolute', left: 130, top: 20 }} label="Badge" color="primary" />
            {/* pv-block-end:26xsul */}
            {/* pv-block-start:8mvs3j */}
            <span className="font-normal text-base" data-pv-block="8mvs3j" data-pv-sketchpad-el="8mvs3j" style={{ position: 'absolute', width: 166, left: 22, top: 91 }}>
              Secondary text that can take multiple lines
            </span>
            {/* pv-block-end:8mvs3j */}
          {/* pv-editable-zone-end:ex6zsf */}
        </Rectangle>
        {/* pv-block-end:023d7s */}
      {/* pv-editable-zone-end:evl0zh */}
    </div>
  );
}
