// Auto-generated by Protovibe Sketchpad
import { Checkbox } from '@/components/ui/checkbox';
import { Button } from '@/components/ui/button';
import { DialogWindow } from '@/components/ui/dialog-window';
import { Input } from '@/components/ui/input';
import { StepCircle } from '@/components/ui/step-circle'
import { TextParagraph } from '@/components/ui/text-paragraph'
import { Image } from '@/components/ui/image'

export default function Frame1() {
  return (
    <div data-layout-mode="absolute" style={{ width: '100%', height: '100%', position: 'relative' }}>
      {/* pv-editable-zone-start:rtzayt */}
      {/* pv-block-start:uwbdk8 */}
      <Checkbox error data-pv-block="uwbdk8" data-pv-sketchpad-el="uwbdk8"  style={{ position: 'absolute', left: 220, top: 416 }} />
      {/* pv-block-end:uwbdk8 */}
      
      {/* pv-block-start:1obgh8 */}
      <DialogWindow size="xl" data-pv-block="1obgh8" data-pv-sketchpad-el="1obgh8"  style={{ position: 'absolute', left: 316, top: 58 }}>
        {/* pv-editable-zone-start:jcx4p4 */}
          {/* pv-block-start:k4mn1h */}
          <div data-pv-block="k4mn1h" className="p-8 flex flex-col gap-2">
            {/* pv-editable-zone-start:xcg13x */}
              {/* pv-block-start:2gcnka */}
              <div data-pv-block="2gcnka" className="flex flex-row items-start gap-8">
                {/* pv-editable-zone-start:wo74jp */}
                {/* pv-block-start:6mrebx */}
                <div data-pv-block="6mrebx" className="flex flex-col gap-2">
                {/* pv-editable-zone-start:enyhfe */}
                {/* pv-block-start:ppsjsl */}
                <div data-pv-block="ppsjsl" className="flex flex-col gap-2">
                {/* pv-editable-zone-start:8be0rh */}
                {/* pv-block-start:rf94ku */}
                <h2 data-pv-block="rf94ku" className="text-xl font-semibold text-foreground-default">
                <span></span><span></span>Generate suggested skills in a spreadsheet
                </h2>
                {/* pv-block-end:rf94ku */}
                {/* pv-block-start:fbnso8 */}
                <TextParagraph className="pt-0.5" data-pv-block="fbnso8" typography="regular">
                  <span></span>Don’t have a document that defines skills in your company yet? No worries, we can help you kick-off this project!
                </TextParagraph>
                {/* pv-block-end:fbnso8 */}
                {/* pv-editable-zone-end:8be0rh */}
                </div>
                {/* pv-block-end:ppsjsl */}
                {/* pv-block-start:88rls2 */}
                <div data-pv-block="88rls2" className="flex flex-col gap-2">
                {/* pv-editable-zone-start:4v2vz4 */}
                {/* pv-block-start:gwhw15 */}
                <div className="flex flex-col min-h-4 items-start" data-pv-block="gwhw15">
                {/* pv-editable-zone-start:inside-gwhw15 */}
                {/* pv-block-start:j88xbh */}
                <div data-pv-block="j88xbh" className="flex gap-2 flex-row items-start justify-start">
                {/* pv-editable-zone-start:qyqjnc */}
                {/* pv-block-start:ucan3m */}
                <StepCircle data-pv-block="ucan3m" state="current" number={1} />
                {/* pv-block-end:ucan3m */}
                {/* pv-block-start:1zpetx */}
                <TextParagraph className="pt-0.5" data-pv-block="1zpetx" typography="regular">
                <span></span><span></span>Generate a file with all your positions and suggested skills
                </TextParagraph>
                {/* pv-block-end:1zpetx */}
                {/* pv-editable-zone-end:qyqjnc */}
                </div>
                {/* pv-block-end:j88xbh */}
                
                {/* pv-editable-zone-end:inside-gwhw15 */}
                </div>
                {/* pv-block-end:gwhw15 */}
                {/* pv-block-start:ts5s57 */}
                <div className="flex flex-col min-h-4 items-start" data-pv-block="ts5s57">
                {/* pv-editable-zone-start:inside-ts5s57 */}
                {/* pv-block-start:zpex1p */}
                <div data-pv-block="zpex1p" className="flex gap-2 flex-row items-start justify-start">
                {/* pv-editable-zone-start:qyqjnc */}
                {/* pv-block-start:x6ipm8 */}
                <StepCircle data-pv-block="x6ipm8" state="current" number="2" />
                {/* pv-block-end:x6ipm8 */}
                {/* pv-block-start:pg1a4e */}
                <TextParagraph className="pt-0.5" data-pv-block="pg1a4e" typography="regular">
                <span></span><span></span><span></span>Collaborate on the file in your favourite tools, like Google Sheets
                </TextParagraph>
                {/* pv-block-end:pg1a4e */}
                {/* pv-editable-zone-end:qyqjnc */}
                </div>
                {/* pv-block-end:zpex1p */}
                
                {/* pv-editable-zone-end:inside-ts5s57 */}
                </div>
                {/* pv-block-end:ts5s57 */}
                {/* pv-block-start:hiimbj */}
                <div className="flex flex-col min-h-4 items-start" data-pv-block="hiimbj">
                {/* pv-editable-zone-start:inside-hiimbj */}
                {/* pv-block-start:gj1pih */}
                <div data-pv-block="gj1pih" className="flex gap-2 flex-row items-start justify-start">
                {/* pv-editable-zone-start:qyqjnc */}
                {/* pv-block-start:s8an3k */}
                <StepCircle data-pv-block="s8an3k" state="current" number="3" />
                {/* pv-block-end:s8an3k */}
                {/* pv-block-start:pfv35g */}
                <TextParagraph className="pt-0.5" data-pv-block="pfv35g" typography="regular">
                <span></span><span></span><span></span>Once you’re done, import the file to Tellent HR
                </TextParagraph>
                {/* pv-block-end:pfv35g */}
                {/* pv-editable-zone-end:qyqjnc */}
                </div>
                {/* pv-block-end:gj1pih */}
                
                {/* pv-editable-zone-end:inside-hiimbj */}
                </div>
                {/* pv-block-end:hiimbj */}
                {/* pv-editable-zone-end:4v2vz4 */}
                </div>
                {/* pv-block-end:88rls2 */}
                {/* pv-editable-zone-end:enyhfe */}
                </div>
                {/* pv-block-end:6mrebx */}
                {/* pv-block-start:mk6tvu */}
                <Image data-pv-block="mk6tvu" className="bg-cover bg-center bg-no-repeat w-full bg-[url('/src/images/from-protovibe/ai-spreadsheet-illustration.svg')] aspect-[133/174] max-w-72" />
                {/* pv-block-end:mk6tvu */}
                {/* pv-editable-zone-end:wo74jp */}
              </div>
              {/* pv-block-end:2gcnka */}






            {/* pv-editable-zone-end:xcg13x */}
          </div>
          {/* pv-block-end:k4mn1h */}
        {/* pv-editable-zone-end:jcx4p4 */}
      </DialogWindow>
      {/* pv-block-end:1obgh8 */}
      
      {/* pv-block-start:m7ibt8 */}
      <Input data-pv-block="m7ibt8" data-pv-sketchpad-el="m7ibt8" placeholder="Enter text..." style={{ position: 'absolute', left: 52, top: 269 }} />
      {/* pv-block-end:m7ibt8 */}
      {/* pv-editable-zone-end:rtzayt */}
    </div>
  );
}
