// Auto-generated by Protovibe Sketchpad
import { Checkbox } from '@/components/ui/checkbox';
import { Button } from '@/components/ui/button';
import { DialogWindow } from '@/components/ui/dialog-window';
import { Input } from '@/components/ui/input';
import { StepCircle } from '@/components/ui/step-circle'
import { TextParagraph } from '@/components/ui/text-paragraph'
import { Image } from '@/components/ui/image'
import { Avatar } from '@/components/ui/avatar'
import { SuperLabel } from '@/components/ui/super-label'
import { SelectDropdown } from '@/components/ui/select-dropdown'
import { DropdownItem } from '@/components/ui/dropdown-item'
import { SelectDropdownSearch } from '@/components/ui/select-dropdown-search'
import { RadioGroup } from '@/components/ui/radio-group'
import { RadioItem } from '@/components/ui/radio-item'
import { Textarea } from '@/components/ui/textarea'
import { Icon } from '@/components/ui/icon'
import { MultiSelectDropdown } from '@/components/ui/multi-select-dropdown'
import { MultiSelectDropdownItem } from '@/components/ui/multi-select-dropdown-item'
import { DropdownSeparator } from '@/components/ui/dropdown-separator'
import { Stepper } from '@/components/ui/stepper'
import { StepperConnector } from '@/components/ui/stepper-connector'

export default function Frame1() {
  return (
    <div className="bg-background-overlay" data-layout-mode="absolute" style={{ width: '100%', height: '100%', position: 'relative' }}>
      {/* pv-editable-zone-start:xa24ou */}
      {/* pv-block-start:jipw8f */}
      <DialogWindow size="xl" data-pv-block="jipw8f" data-pv-sketchpad-el="jipw8f"  style={{ position: 'absolute', left: 300, top: 146 }}>
        {/* pv-editable-zone-start:ghpyxn */}
          {/* pv-block-start:my9lvs */}
          <div className="flex min-h-4 border-border-default flex-row items-center gap-4 justify-start border-b p-5" data-pv-block="my9lvs">
            {/* pv-editable-zone-start:t7nd3c */}
              {/* pv-block-start:d9f5jx */}
              <div data-pv-block="d9f5jx" className="flex flex-col gap-0">
              {/* pv-editable-zone-start:7l5x7c */}
              {/* pv-block-start:vw310f */}
              <h2 data-pv-block="vw310f" className="text-xl font-semibold text-foreground-default">
                <span></span><span></span><span></span>Import skills to positions from a file
              </h2>
              {/* pv-block-end:vw310f */}
              {/* pv-block-start:rwtf2d */}
              <TextParagraph className="pt-0.5 text-sm text-foreground-secondary" data-pv-block="rwtf2d" typography="regular">
                <span></span><span></span><span></span>Upload your document and AI will read it and import skills to Tellent HR. <a href="https://" target="_blank" rel="noopener noreferrer" className="text-foreground-primary hover:opacity-80 transition-opacity">Learn more</a>
              </TextParagraph>
              {/* pv-block-end:rwtf2d */}
              {/* pv-editable-zone-end:7l5x7c */}
              </div>
              {/* pv-block-end:d9f5jx */}
            {/* pv-editable-zone-end:t7nd3c */}
          </div>
          {/* pv-block-end:my9lvs */}
          {/* pv-block-start:cozohu */}
          <div data-pv-block="cozohu" className="flex flex-col p-5 gap-7">
            {/* pv-editable-zone-start:1907kq */}
              {/* pv-block-start:68199b */}
              <Stepper data-pv-block="68199b" fullWidth={false}>
                {/* pv-editable-zone-start:v4z32l */}
                  {/* pv-block-start:wybt4u */}
                  <StepCircle labelPosition="right" data-pv-block="wybt4u" state="current" number={1} label="Details" />
                  {/* pv-block-end:wybt4u */}
                  {/* pv-block-start:o9bj8n */}
                  <StepperConnector data-pv-block="o9bj8n" state="upcoming" />
                  {/* pv-block-end:o9bj8n */}
                  {/* pv-block-start:0kh66m */}
                  <StepCircle labelPosition="right" data-pv-block="0kh66m" state="upcoming" number={2} label="Review" />
                  {/* pv-block-end:0kh66m */}
                  {/* pv-block-start:1646vz */}
                  <StepperConnector data-pv-block="1646vz" state="upcoming" />
                  {/* pv-block-end:1646vz */}
                  {/* pv-block-start:col9vn */}
                  <StepCircle labelPosition="right" data-pv-block="col9vn" state="upcoming" number={3} label="Confirm" />
                  {/* pv-block-end:col9vn */}
                {/* pv-editable-zone-end:v4z32l */}
              </Stepper>
              {/* pv-block-end:68199b */}

              {/* pv-block-start:v2w9lh */}
              <div data-pv-block="v2w9lh" className="flex flex-col gap-2">
                {/* pv-editable-zone-start:hikm6d */}
                {/* pv-block-start:0fqt9h */}
                <SuperLabel secondaryText="Supported file formats: PDF, DOCX, CSV or XLSX • Max. file size: 5 MB" heading="Upload files with skills" data-pv-block="0fqt9h" primaryText="" />
                {/* pv-block-end:0fqt9h */}
                {/* pv-editable-zone-end:hikm6d */}
              </div>
              {/* pv-block-end:v2w9lh */}
            {/* pv-editable-zone-end:1907kq */}
          </div>
          {/* pv-block-end:cozohu */}

          {/* pv-block-start:686fs1 */}
          <div className="flex min-h-4 bg-background-subtle border-t border-border-default flex-row items-center gap-4 justify-end py-3 px-5" data-pv-block="686fs1">
            {/* pv-editable-zone-start:t7nd3c */}
              {/* pv-block-start:kgo6ug */}
              <div data-pv-block="kgo6ug" className="flex gap-2 flex-row">
                {/* pv-editable-zone-start:olib04 */}
                {/* pv-block-start:pxxeyc */}
                <Button data-pv-block="pxxeyc" label="Cancel" variant="ghost" color="neutral" size="md"  />
                {/* pv-block-end:pxxeyc */}
                {/* pv-block-start:id0ukj */}
                <Button rightIcon="mdi:arrow-right" data-pv-block="id0ukj" label="Generate file" variant="solid" color="primary" size="md"  />
                {/* pv-block-end:id0ukj */}
                {/* pv-editable-zone-end:olib04 */}
              </div>
              {/* pv-block-end:kgo6ug */}
            {/* pv-editable-zone-end:t7nd3c */}
          </div>
          {/* pv-block-end:686fs1 */}
        {/* pv-editable-zone-end:ghpyxn */}
      </DialogWindow>
      {/* pv-block-end:jipw8f */}
      {/* pv-editable-zone-end:xa24ou */}
    </div>
  );
}
