import { MultiSelectDropdown } from '@/components/ui/multi-select-dropdown'
import { MultiSelectDropdownItem } from '@/components/ui/multi-select-dropdown-item'
import { SelectDropdownSearch } from '@/components/ui/select-dropdown-search'
import { MultiSelectDropdownMenu } from '@/components/ui/multi-select-dropdown-menu'
import { SelectDropdownMenu } from '@/components/ui/select-dropdown-menu'
import { DropdownItem } from '@/components/ui/dropdown-item'
import { DropdownSeparator } from '@/components/ui/dropdown-separator'
import { SelectDropdown } from '@/components/ui/select-dropdown'
// Auto-generated by Protovibe Sketchpad

export default function Frame3() {
  return (
    <div data-layout-mode="absolute" style={{ width: '100%', height: '100%', position: 'relative' }}>
      {/* pv-editable-zone-start:tk01b8 */}
        {/* pv-block-start:943pgr */}
        <MultiSelectDropdown data-pv-block="943pgr" data-pv-sketchpad-el="943pgr" style={{ position: 'absolute', width: 458, left: 85, top: 137 }} placeholder="Select..." value="alice,bob">
          {/* pv-editable-zone-start:qxnsyn */}
            {/* pv-block-start:izx74i */}
            <SelectDropdownSearch data-pv-block="izx74i" placeholder="Search people..." />
            {/* pv-block-end:izx74i */}
            {/* pv-block-start:4gcfcl */}
            <MultiSelectDropdownItem data-pv-block="4gcfcl" value="alice" label="Alice Johnson" badgeLabel="Design" />
            {/* pv-block-end:4gcfcl */}
            {/* pv-block-start:2g64dz */}
            <MultiSelectDropdownItem data-pv-block="2g64dz" value="bob" label="Bob Smith" badgeLabel="Engineering" />
            {/* pv-block-end:2g64dz */}
            {/* pv-block-start:9y57ke */}
            <MultiSelectDropdownItem data-pv-block="9y57ke" value="carol" label="Carol Davis" badgeLabel="Marketing" />
            {/* pv-block-end:9y57ke */}
          {/* pv-editable-zone-end:qxnsyn */}
        </MultiSelectDropdown>
        {/* pv-block-end:943pgr */}
        {/* pv-block-start:k3wnqa */}
        <MultiSelectDropdownMenu data-pv-block="k3wnqa" data-pv-sketchpad-el="k3wnqa" style={{ position: 'absolute', left: 84, top: 212 }} width="md">
          {/* pv-editable-zone-start:nddxqu */}
            {/* pv-block-start:axx2tz */}
            <SelectDropdownSearch data-pv-block="axx2tz" placeholder="Search people..." />
            {/* pv-block-end:axx2tz */}
            {/* pv-block-start:k8wsbv */}
            <MultiSelectDropdownItem data-pv-block="k8wsbv" value="all" label="All" badgeLabel="Design" selected={true} />
            {/* pv-block-end:k8wsbv */}
            {/* pv-block-start:5obij0 */}
            <DropdownSeparator data-pv-block="5obij0" />
            {/* pv-block-end:5obij0 */}

            {/* pv-block-start:9jkcj1 */}
            <MultiSelectDropdownItem data-pv-block="9jkcj1" value="alice" label="Alice Johnson" badgeLabel="Design" selected={true} />
            {/* pv-block-end:9jkcj1 */}
            {/* pv-block-start:jtao3u */}
            <MultiSelectDropdownItem data-pv-block="jtao3u" value="bob" label="Bob Smith" badgeLabel="Engineering" selected={true} />
            {/* pv-block-end:jtao3u */}
            {/* pv-block-start:htgfqe */}
            <MultiSelectDropdownItem data-pv-block="htgfqe" value="carol" label="Carol Davis" badgeLabel="Marketing" selected={false} />
            {/* pv-block-end:htgfqe */}
          {/* pv-editable-zone-end:nddxqu */}
        </MultiSelectDropdownMenu>
        {/* pv-block-end:k3wnqa */}
        {/* pv-block-start:arylik */}
        <SelectDropdownMenu data-pv-block="arylik" data-pv-sketchpad-el="arylik" style={{ position: 'absolute', left: 437, top: 327 }} width="md">
          {/* pv-editable-zone-start:b68j9h */}
            {/* pv-block-start:aikkzl */}
            <SelectDropdownSearch data-pv-block="aikkzl" placeholder="Search..." />
            {/* pv-block-end:aikkzl */}
            {/* pv-block-start:xckoap */}
            <DropdownItem data-pv-block="xckoap" value="opt1" label="Option One" selected={true} />
            {/* pv-block-end:xckoap */}
            {/* pv-block-start:ayxeuz */}
            <DropdownItem data-pv-block="ayxeuz" value="opt2" label="Option Two" selected={false} />
            {/* pv-block-end:ayxeuz */}
            {/* pv-block-start:ij2bw5 */}
            <DropdownItem data-pv-block="ij2bw5" value="opt3" label="Option Three" selected={false} />
            {/* pv-block-end:ij2bw5 */}
          {/* pv-editable-zone-end:b68j9h */}
        </SelectDropdownMenu>
        {/* pv-block-end:arylik */}
      {/* pv-editable-zone-end:tk01b8 */}
    </div>
  );
}
