import { Input } from '@/components/ui/input'
import { SuperLabel } from '@/components/ui/super-label'
import { TextHeading } from '@/components/ui/text-heading'
import { Button } from '@/components/ui/button'
import { TextParagraph } from '@/components/ui/text-paragraph'
import { Icon } from '@/components/ui/icon'
import { Rectangle } from '@/components/ui/sketchpad-rectangle'
import { VerticalLine } from '@/components/ui/sketchpad-vertical-line'
import { HorizontalLine } from '@/components/ui/sketchpad-horizontal-line'
import { Card } from '@/components/ui/card'
import { Image } from '@/components/ui/image'
// Auto-generated by Protovibe Sketchpad

export default function Frame12() {
  return (
    <div className="overflow-hidden" data-layout-mode="absolute" style={{ width: '100%', height: '100%', position: 'relative' }}>
      {/* pv-editable-zone-start:tur897 */}
        {/* pv-block-start:enkyu2 */}
        <Input data-pv-block="enkyu2" data-pv-sketchpad-el="enkyu2" style={{ position: 'absolute', width: 332, left: 169, top: 236 }} placeholder="" />
        {/* pv-block-end:enkyu2 */}
        {/* pv-block-start:sp6voy */}
        <SuperLabel data-pv-block="sp6voy" data-pv-sketchpad-el="sp6voy" style={{ position: 'absolute', left: 169, top: 208 }} primaryText="Email or username" />
        {/* pv-block-end:sp6voy */}
        {/* pv-block-start:4cqrnu */}
        <TextHeading data-pv-block="4cqrnu" data-pv-sketchpad-el="4cqrnu" style={{ position: 'absolute', left: 169, top: 139 }} typography="heading-md">
          Login to EvilCorp
        </TextHeading>
        {/* pv-block-end:4cqrnu */}
        {/* pv-block-start:5lxryx */}
        <SuperLabel data-pv-block="5lxryx" data-pv-sketchpad-el="5lxryx" style={{ position: 'absolute', left: 169, top: 295 }} primaryText="Password" />
        {/* pv-block-end:5lxryx */}
        
        {/* pv-block-start:rnkc1k */}
        <Input data-pv-block="rnkc1k" data-pv-sketchpad-el="rnkc1k" style={{ position: 'absolute', left: 169, top: 323, width: 332 }} placeholder="" />
        {/* pv-block-end:rnkc1k */}
        {/* pv-block-start:o0o4kj */}
        <SuperLabel data-pv-block="o0o4kj" data-pv-sketchpad-el="o0o4kj" style={{ position: 'absolute', left: 309, top: 428 }} primaryText="— OR —" />
        {/* pv-block-end:o0o4kj */}
        {/* pv-block-start:6buap0 */}
        <Button data-pv-block="6buap0" data-pv-sketchpad-el="6buap0" style={{ position: 'absolute', width: 332, left: 169, top: 372 }} label="Sign in" variant="solid" color="primary" size="md" />
        {/* pv-block-end:6buap0 */}
        {/* pv-block-start:14jmz8 */}
        <Button leftIcon="ion:logo-google" data-pv-block="14jmz8" data-pv-sketchpad-el="14jmz8" style={{ position: 'absolute', left: 170, top: 468, width: 332 }} label="Continue with Google" variant="solid" color="neutral" size="md" />
        {/* pv-block-end:14jmz8 */}
        {/* pv-block-start:5va4n9 */}
        <Button leftIcon="radix-icons:github-logo" data-pv-block="5va4n9" data-pv-sketchpad-el="5va4n9" style={{ position: 'absolute', left: 170, top: 520, width: 332 }} label="Continue with GitHub" variant="solid" color="neutral" size="md" />
        {/* pv-block-end:5va4n9 */}
        {/* pv-block-start:omkon4 */}
        <TextHeading data-pv-block="omkon4" data-pv-sketchpad-el="omkon4" style={{ position: 'absolute', width: 82, left: 67, top: 30 }} typography="heading-md">
          EvilCorp
        </TextHeading>
        {/* pv-block-end:omkon4 */}
        {/* pv-block-start:3dgv9m */}
        <TextParagraph data-pv-block="3dgv9m" data-pv-sketchpad-el="3dgv9m" style={{ position: 'absolute', left: 169, top: 30 }} typography="regular">
          To take over the world!
        </TextParagraph>
        {/* pv-block-end:3dgv9m */}
        {/* pv-block-start:edxig4 */}
        <Icon data-pv-block="edxig4" data-pv-sketchpad-el="edxig4" style={{ position: 'absolute', width: 20, left: 33, top: 29 }} iconSymbol="fluent-emoji-high-contrast:see-no-evil-monkey" size="lg" />
        {/* pv-block-end:edxig4 */}
        {/* pv-block-start:2i8ndr */}
        <div data-pv-block="2i8ndr" data-pv-sketchpad-el="2i8ndr" style={{ position: 'absolute', left: 365, top: -54 }} className="w-full bg-[url('/src/images/from-protovibe/image-3.png')] bg-contain bg-center bg-no-repeat aspect-[995/917]" />
        {/* pv-block-end:2i8ndr */}
        {/* pv-block-start:burgn0 */}
        <Rectangle data-pv-block="burgn0" data-pv-sketchpad-el="burgn0" style={{ position: 'absolute', height: 893, width: 768, left: 671, top: -18 }} className="w-[200px] h-[200px] overflow-hidden border-0 rounded-none bg-transparent">
          {/* pv-editable-zone-start:33rzk4 */}
            {/* pv-block-start:wrdvod */}
            <div data-pv-block="wrdvod" data-pv-sketchpad-el="wrdvod" style={{ position: 'absolute', width: 1065, left: 117, top: 162 }} className="w-full bg-[url('/src/images/from-protovibe/image-2.png')] bg-contain bg-center bg-no-repeat aspect-[565/537]" />
            {/* pv-block-end:wrdvod */}
          {/* pv-editable-zone-end:33rzk4 */}
        </Rectangle>
        {/* pv-block-end:burgn0 */}
        {/* pv-block-start:hcmr75 */}
        <VerticalLine data-pv-block="hcmr75" data-pv-sketchpad-el="hcmr75" style={{ position: 'absolute', height: 20, left: 154, top: 32 }} className="w-[4px] h-[200px]">
          {/* pv-editable-zone-start:p10z5a */}
          {/* pv-editable-zone-end:p10z5a */}
        </VerticalLine>
        {/* pv-block-end:hcmr75 */}
        {/* pv-block-start:kw2kxh */}
        <TextParagraph className="flex flex-row gap-1 items-center bg-transparent justify-center rounded-none" data-pv-block="kw2kxh" data-pv-sketchpad-el="kw2kxh" style={{ position: 'absolute', width: 328, left: 173, top: 582 }} typography="regular">
          Don't have account? <a href="https://" target="_blank" rel="noopener noreferrer" className="text-foreground-primary-link hover:opacity-80 transition-opacity">Sign up</a>
        </TextParagraph>
        {/* pv-block-end:kw2kxh */}
        {/* pv-block-start:efpysr */}
        <TextParagraph className="text-tiny text-foreground-tertiary" data-pv-block="efpysr" data-pv-sketchpad-el="efpysr" style={{ position: 'absolute', width: 331, left: 173, top: 733 }} typography="small">
          By logging in you accept EvilCorop terms of services.
        </TextParagraph>
        {/* pv-block-end:efpysr */}
        {/* pv-block-start:g5lgmw */}
        <HorizontalLine data-pv-block="g5lgmw" data-pv-sketchpad-el="g5lgmw" style={{ position: 'absolute', width: 321, left: 173, top: 710 }} className="w-[200px] h-[4px]">
          {/* pv-editable-zone-start:lo07ls */}
          {/* pv-editable-zone-end:lo07ls */}
        </HorizontalLine>
        {/* pv-block-end:g5lgmw */}
      {/* pv-editable-zone-end:tur897 */}
    </div>
  );
}
