// Auto-generated by Protovibe Sketchpad
import { Checkbox } from '@/components/ui/checkbox';
import { Button } from '@/components/ui/button';
import { DialogWindow } from '@/components/ui/dialog-window';
import { Input } from '@/components/ui/input';
import { StepCircle } from '@/components/ui/step-circle'
import { TextParagraph } from '@/components/ui/text-paragraph'
import { Image } from '@/components/ui/image'
import { Avatar } from '@/components/ui/avatar'
import { SuperLabel } from '@/components/ui/super-label'
import { SelectDropdown } from '@/components/ui/select-dropdown'
import { DropdownItem } from '@/components/ui/dropdown-item'
import { SelectDropdownSearch } from '@/components/ui/select-dropdown-search'
import { RadioGroup } from '@/components/ui/radio-group'
import { RadioItem } from '@/components/ui/radio-item'
import { Textarea } from '@/components/ui/textarea'
import { Icon } from '@/components/ui/icon'
import { MultiSelectDropdown } from '@/components/ui/multi-select-dropdown'
import { MultiSelectDropdownItem } from '@/components/ui/multi-select-dropdown-item'
import { DropdownSeparator } from '@/components/ui/dropdown-separator'
import { Card } from '@/components/ui/card'
import { Stepper } from '@/components/ui/stepper'
import { StepperConnector } from '@/components/ui/stepper-connector'

export default function Frame1() {
  return (
    <div className="bg-background-overlay" data-layout-mode="absolute" style={{ width: '100%', height: '100%', position: 'relative' }}>
      {/* pv-editable-zone-start:nc1nqa */}
      {/* pv-block-start:exm6jg */}
      <DialogWindow size="xl" data-pv-block="exm6jg" data-pv-sketchpad-el="exm6jg"  style={{ position: 'absolute', left: 300, top: 146 }}>
        {/* pv-editable-zone-start:gu24cs */}
          {/* pv-block-start:jlpm2v */}
          <div className="flex min-h-4 border-border-default flex-row items-center gap-4 justify-start border-b p-5" data-pv-block="jlpm2v">
            {/* pv-editable-zone-start:t7nd3c */}
              {/* pv-block-start:c39vrv */}
              <div data-pv-block="c39vrv" className="flex flex-col gap-0">
              {/* pv-editable-zone-start:7l5x7c */}
              {/* pv-block-start:xedfkz */}
              <h2 data-pv-block="xedfkz" className="text-xl font-semibold text-foreground-default">
                <span></span><span></span><span></span>Import skills to positions from a file
              </h2>
              {/* pv-block-end:xedfkz */}
              {/* pv-block-start:ahfwpg */}
              <TextParagraph className="pt-0.5 text-sm text-foreground-secondary" data-pv-block="ahfwpg" typography="regular">
                <span></span><span></span><span></span>Upload your document and AI will read it and import skills to Tellent HR. <a href="https://" target="_blank" rel="noopener noreferrer" className="text-foreground-primary hover:opacity-80 transition-opacity">Learn more</a>
              </TextParagraph>
              {/* pv-block-end:ahfwpg */}
              {/* pv-editable-zone-end:7l5x7c */}
              </div>
              {/* pv-block-end:c39vrv */}
            {/* pv-editable-zone-end:t7nd3c */}
          </div>
          {/* pv-block-end:jlpm2v */}
          {/* pv-block-start:e5voje */}
          <div data-pv-block="e5voje" className="flex flex-col p-5 gap-7">
            {/* pv-editable-zone-start:hb3knb */}
              {/* pv-block-start:4qgtzj */}
              <Stepper data-pv-block="4qgtzj" fullWidth={false}>
                {/* pv-editable-zone-start:v4z32l */}
                  {/* pv-block-start:ijci27 */}
                  <StepCircle labelPosition="right" data-pv-block="ijci27" state="current" number={1} label="Details" />
                  {/* pv-block-end:ijci27 */}
                  {/* pv-block-start:ywwjbl */}
                  <StepperConnector data-pv-block="ywwjbl" state="upcoming" />
                  {/* pv-block-end:ywwjbl */}
                  {/* pv-block-start:fm9a31 */}
                  <StepCircle labelPosition="right" data-pv-block="fm9a31" state="upcoming" number={2} label="Review" />
                  {/* pv-block-end:fm9a31 */}
                  {/* pv-block-start:xy90vm */}
                  <StepperConnector data-pv-block="xy90vm" state="upcoming" />
                  {/* pv-block-end:xy90vm */}
                  {/* pv-block-start:f46t1q */}
                  <StepCircle labelPosition="right" data-pv-block="f46t1q" state="upcoming" number={3} label="Confirm" />
                  {/* pv-block-end:f46t1q */}
                {/* pv-editable-zone-end:v4z32l */}
              </Stepper>
              {/* pv-block-end:4qgtzj */}
              {/* pv-block-start:m7kral */}
              <div data-tooltip-text="This section only appears if Custom number of proficiency levels is selected" data-pv-block="m7kral" className="flex flex-col gap-2">
                {/* pv-editable-zone-start:dy3ds8 */}
                {/* pv-block-start:lvjh8x */}
                <SuperLabel secondaryText="To ensure best quality, instruct AI what to expect in your file" heading="What's in your file?" data-pv-block="lvjh8x" primaryText="" />
                {/* pv-block-end:lvjh8x */}
                {/* pv-block-start:h0syuq */}
                <Card className="gap-1 p-3" data-pv-block="h0syuq">
                  {/* pv-editable-zone-start:1m6n9j */}
                    {/* pv-block-start:99s9fi */}
                    <Checkbox data-pv-block="99s9fi" primaryText="Skills have a unique name and description" />
                    {/* pv-block-end:99s9fi */}

                    {/* pv-block-start:4qb8rq */}
                    <Checkbox data-pv-block="4qb8rq" primaryText="Skills have proficiency levels (e.g. ‘Beginner’, ‘Intermediate’, ‘Expert’ or ‘P1’, ‘P2’, ‘P3’)" />
                    {/* pv-block-end:4qb8rq */}

                    {/* pv-block-start:ee1b16 */}
                    <Checkbox data-pv-block="ee1b16" primaryText="Each proficiency level have a description what is expected" />
                    {/* pv-block-end:ee1b16 */}

                    {/* pv-block-start:7bjwj7 */}
                    <Checkbox data-pv-block="7bjwj7" primaryText="Positions are associated with a skill and its proficiency level" />
                    {/* pv-block-end:7bjwj7 */}

                    {/* pv-block-start:vmz009 */}
                    <Checkbox data-pv-block="vmz009" primaryText="Skills are grouped into categories (such as ‘Soft skills” or ‘Technical skills’)" />
                    {/* pv-block-end:vmz009 */}
                  {/* pv-editable-zone-end:1m6n9j */}
                </Card>
                {/* pv-block-end:h0syuq */}
                {/* pv-editable-zone-end:dy3ds8 */}
              </div>
              {/* pv-block-end:m7kral */}

              {/* pv-block-start:41v8rx */}
              <div data-pv-block="41v8rx" className="flex flex-col gap-2">
                {/* pv-editable-zone-start:dy3ds8 */}
                {/* pv-block-start:qj0y8m */}
                <SuperLabel secondaryText="For example, what methodologies you plan to use, what industry you’re in." heading="Additonal instructions for AI" data-pv-block="qj0y8m" primaryText="" />
                {/* pv-block-end:qj0y8m */}
                {/* pv-block-start:9e2lqw */}
                <Textarea data-pv-block="9e2lqw" placeholder="Optional" />
                {/* pv-block-end:9e2lqw */}
                {/* pv-editable-zone-end:dy3ds8 */}
              </div>
              {/* pv-block-end:41v8rx */}
            {/* pv-editable-zone-end:hb3knb */}
          </div>
          {/* pv-block-end:e5voje */}

          {/* pv-block-start:mbv43u */}
          <div className="flex min-h-4 bg-background-subtle border-t border-border-default flex-row items-center gap-4 justify-end py-3 px-5" data-pv-block="mbv43u">
            {/* pv-editable-zone-start:2mi6w3 */}
              {/* pv-block-start:gh1jlr */}
              <div data-pv-block="gh1jlr" className="flex gap-2 flex-row">
                {/* pv-editable-zone-start:2x30wg */}
                {/* pv-block-start:d6sgc6 */}
                <Button data-pv-block="d6sgc6" label="Cancel" variant="ghost" color="neutral" size="md"  />
                {/* pv-block-end:d6sgc6 */}
                {/* pv-block-start:t8stw0 */}
                <Button rightIcon="mdi:arrow-right" data-pv-block="t8stw0" label="Generate file" variant="solid" color="primary" size="md"  />
                {/* pv-block-end:t8stw0 */}
                {/* pv-editable-zone-end:2x30wg */}
              </div>
              {/* pv-block-end:gh1jlr */}
            {/* pv-editable-zone-end:2mi6w3 */}
          </div>
          {/* pv-block-end:mbv43u */}
        {/* pv-editable-zone-end:gu24cs */}
      </DialogWindow>
      {/* pv-block-end:exm6jg */}
      {/* pv-editable-zone-end:nc1nqa */}
    </div>
  );
}
