import { Image } from '@/components/ui/image'
import { Avatar } from '@/components/ui/avatar'
// Auto-generated by Protovibe Sketchpad

export default function Frame14() {
  return (
    <div data-layout-mode="absolute" style={{ width: '100%', height: '100%', position: 'relative' }}>
      {/* pv-editable-zone-start:0au3jg */}
        {/* pv-block-start:lxe9m9 */}
        <Image data-pv-block="lxe9m9" data-pv-sketchpad-el="lxe9m9" style={{ position: 'absolute', width: 558, left: 114, top: 92 }} className="bg-[url('/src/images/from-protovibe/image-placeholder.svg')] bg-cover bg-center bg-no-repeat aspect-video w-full" />
        {/* pv-block-end:lxe9m9 */}
        {/* pv-block-start:ekbi6l */}
        <Avatar data-pv-block="ekbi6l" data-pv-sketchpad-el="ekbi6l" style={{ position: 'absolute', left: 202, top: 181 }} initials="AB" size="md" bgColor="default" imageSrc="https://i.pravatar.cc/60" />
        {/* pv-block-end:ekbi6l */}
      {/* pv-editable-zone-end:0au3jg */}
    </div>
  );
}
