// Auto-generated by Protovibe Sketchpad
import { Checkbox } from '@/components/ui/checkbox';
import { Button } from '@/components/ui/button';
import { DialogWindow } from '@/components/ui/dialog-window';
import { Input } from '@/components/ui/input';
import { StepCircle } from '@/components/ui/step-circle'
import { TextParagraph } from '@/components/ui/text-paragraph'
import { Image } from '@/components/ui/image'
import { Avatar } from '@/components/ui/avatar'

export default function Frame1() {
  return (
    <div className="bg-background-overlay" data-layout-mode="absolute" style={{ width: '100%', height: '100%', position: 'relative' }}>
      {/* pv-editable-zone-start:2n7pqy */}
      {/* pv-block-start:sdaeec */}
      <DialogWindow size="xl" data-pv-block="sdaeec" data-pv-sketchpad-el="sdaeec"  style={{ position: 'absolute', left: 300, top: 146 }}>
        {/* pv-editable-zone-start:tw6q5w */}
          {/* pv-block-start:pmsui8 */}
          <div data-pv-block="pmsui8" className="flex flex-col gap-2 p-12">
            {/* pv-editable-zone-start:9fo3ep */}
              {/* pv-block-start:cjnh0t */}
              <div data-pv-block="cjnh0t" className="flex flex-row items-start gap-16">
                {/* pv-editable-zone-start:w3mswu */}
                {/* pv-block-start:fh2cz9 */}
                <div data-pv-block="fh2cz9" className="flex flex-col gap-8">
                {/* pv-editable-zone-start:9nk40i */}
                {/* pv-block-start:euoh13 */}
                <div data-pv-block="euoh13" className="flex flex-col gap-4">
                {/* pv-editable-zone-start:dt5pv2 */}
                {/* pv-block-start:ozzkoi */}
                <h2 data-pv-block="ozzkoi" className="text-xl font-semibold text-foreground-default">
                <span></span><span></span>Generate suggested skills in a spreadsheet
                </h2>
                {/* pv-block-end:ozzkoi */}
                {/* pv-block-start:q9lpow */}
                <TextParagraph className="pt-0.5" data-pv-block="q9lpow" typography="regular">
                  <span></span>Don’t have a document that defines skills in your company yet? No worries, we can help you kick-off this project!
                </TextParagraph>
                {/* pv-block-end:q9lpow */}
                {/* pv-editable-zone-end:dt5pv2 */}
                </div>
                {/* pv-block-end:euoh13 */}
                {/* pv-block-start:ou8phh */}
                <div data-pv-block="ou8phh" className="flex flex-col gap-2">
                {/* pv-editable-zone-start:016r5z */}
                {/* pv-block-start:zwi4vp */}
                <div className="flex flex-col items-start relative pb-6 min-h-16" data-pv-block="zwi4vp">
                {/* pv-editable-zone-start:pioaf5 */}
                {/* pv-block-start:ccoyu8 */}
                <div data-pv-block="ccoyu8" className="flex gap-2 flex-row items-start justify-start">
                {/* pv-editable-zone-start:adgjak */}
                {/* pv-block-start:imooe8 */}
                <StepCircle data-pv-block="imooe8" state="current" number={1} />
                {/* pv-block-end:imooe8 */}
                {/* pv-block-start:2v63k8 */}
                <TextParagraph className="pt-0.5" data-pv-block="2v63k8" typography="regular">
                  <span></span><span></span>Generate a file with all your positions and suggested skills
                </TextParagraph>
                {/* pv-block-end:2v63k8 */}
                {/* pv-editable-zone-end:adgjak */}
                </div>
                {/* pv-block-end:ccoyu8 */}
                
                  {/* pv-block-start:o7xc5z */}
                  <div className="flex flex-col w-6 items-center absolute top-8 bottom-0 min-h-2" data-pv-block="o7xc5z">
                    {/* pv-editable-zone-start:a0c5v2 */}
                      {/* pv-block-start:56o06f */}
                      <div className="flex flex-col min-h-4 w-px bg-background-primary flex-1" data-pv-block="56o06f">
                        {/* pv-editable-zone-start:0rqr5t */}
                        {/* pv-editable-zone-end:0rqr5t */}
                      </div>
                      {/* pv-block-end:56o06f */}
                    {/* pv-editable-zone-end:a0c5v2 */}
                  </div>
                  {/* pv-block-end:o7xc5z */}
                {/* pv-editable-zone-end:pioaf5 */}
                </div>
                {/* pv-block-end:zwi4vp */}

                {/* pv-block-start:gymrke */}
                <div className="flex flex-col items-start relative pb-6 min-h-16" data-pv-block="gymrke">
                {/* pv-editable-zone-start:thgz3j */}
                {/* pv-block-start:knjumq */}
                <div data-pv-block="knjumq" className="flex gap-2 flex-row items-start justify-start">
                {/* pv-editable-zone-start:adgjak */}
                {/* pv-block-start:xa7c1x */}
                <StepCircle data-pv-block="xa7c1x" state="current" number={1} />
                {/* pv-block-end:xa7c1x */}
                {/* pv-block-start:8p3sxf */}
                <TextParagraph className="pt-0.5" data-pv-block="8p3sxf" typography="regular">
                  <span></span>Collaborate on the file in your favourite tools, like Google Sheets
                </TextParagraph>
                {/* pv-block-end:8p3sxf */}
                {/* pv-editable-zone-end:adgjak */}
                </div>
                {/* pv-block-end:knjumq */}
                
                  {/* pv-block-start:7cwhe6 */}
                  <div className="flex flex-col w-6 items-center absolute top-8 bottom-0 min-h-2" data-pv-block="7cwhe6">
                    {/* pv-editable-zone-start:vkndww */}
                      {/* pv-block-start:b52day */}
                      <div className="flex flex-col min-h-4 w-px bg-background-primary flex-1" data-pv-block="b52day">
                        {/* pv-editable-zone-start:9pufgw */}
                        {/* pv-editable-zone-end:9pufgw */}
                      </div>
                      {/* pv-block-end:b52day */}
                    {/* pv-editable-zone-end:vkndww */}
                  </div>
                  {/* pv-block-end:7cwhe6 */}
                {/* pv-editable-zone-end:thgz3j */}
                </div>
                {/* pv-block-end:gymrke */}

                {/* pv-block-start:nzbrww */}
                <div className="flex flex-col items-start relative pb-6 min-h-0" data-pv-block="nzbrww">
                {/* pv-editable-zone-start:a1tw2p */}
                {/* pv-block-start:j9uki5 */}
                <div data-pv-block="j9uki5" className="flex gap-2 flex-row items-start justify-start">
                {/* pv-editable-zone-start:adgjak */}
                {/* pv-block-start:tt805b */}
                <StepCircle data-pv-block="tt805b" state="current" number={1} />
                {/* pv-block-end:tt805b */}
                {/* pv-block-start:e0fmzo */}
                <TextParagraph className="pt-0.5" data-pv-block="e0fmzo" typography="regular">
                  <span></span>Once you’re done, import the file to Tellent HR
                </TextParagraph>
                {/* pv-block-end:e0fmzo */}
                {/* pv-editable-zone-end:adgjak */}
                </div>
                {/* pv-block-end:j9uki5 */}
                
                  {/* pv-block-start:51vsdn */}
                  <div className="flex-col w-6 items-center absolute top-8 bottom-0 min-h-2 hidden" data-pv-block="51vsdn">
                    {/* pv-editable-zone-start:4anw3k */}
                      {/* pv-block-start:m1zgyo */}
                      <div className="flex flex-col min-h-4 w-px bg-background-primary flex-1" data-pv-block="m1zgyo">
                        {/* pv-editable-zone-start:ee04tw */}
                        {/* pv-editable-zone-end:ee04tw */}
                      </div>
                      {/* pv-block-end:m1zgyo */}
                    {/* pv-editable-zone-end:4anw3k */}
                  </div>
                  {/* pv-block-end:51vsdn */}
                {/* pv-editable-zone-end:a1tw2p */}
                </div>
                {/* pv-block-end:nzbrww */}
                {/* pv-editable-zone-end:016r5z */}
                </div>
                {/* pv-block-end:ou8phh */}
                {/* pv-editable-zone-end:9nk40i */}
                </div>
                {/* pv-block-end:fh2cz9 */}
                {/* pv-block-start:5wmibe */}
                <Image data-pv-block="5wmibe" className="bg-cover bg-center bg-no-repeat w-full bg-[url('/src/images/from-protovibe/ai-spreadsheet-illustration.svg')] aspect-[133/174] max-w-[258px]" />
                {/* pv-block-end:5wmibe */}
                {/* pv-editable-zone-end:w3mswu */}
              </div>
              {/* pv-block-end:cjnh0t */}
            {/* pv-editable-zone-end:9fo3ep */}
          </div>
          {/* pv-block-end:pmsui8 */}
          {/* pv-block-start:9la13c */}
          <div className="flex min-h-4 bg-background-subtle border-t border-border-default flex-row items-center p-5 gap-4 justify-between" data-pv-block="9la13c">
            {/* pv-editable-zone-start:2xmyp4 */}
              {/* pv-block-start:5ypdw6 */}
              <Checkbox data-pv-block="5ypdw6" primaryText="Don't show this intro again" />
              {/* pv-block-end:5ypdw6 */}
              {/* pv-block-start:rfu32z */}
              <div data-pv-block="rfu32z" className="flex gap-2 flex-row">
                {/* pv-editable-zone-start:e2sff4 */}
                {/* pv-block-start:uiktns */}
                <Button data-pv-block="uiktns" label="Cancel" variant="ghost" color="neutral" size="md"  />
                {/* pv-block-end:uiktns */}
                {/* pv-block-start:fgs6cw */}
                <Button rightIcon="mdi:arrow-right" data-pv-block="fgs6cw" label="Let's start" variant="solid" color="primary" size="md"  />
                {/* pv-block-end:fgs6cw */}
                {/* pv-editable-zone-end:e2sff4 */}
              </div>
              {/* pv-block-end:rfu32z */}
            {/* pv-editable-zone-end:2xmyp4 */}
          </div>
          {/* pv-block-end:9la13c */}
        {/* pv-editable-zone-end:tw6q5w */}
      </DialogWindow>
      {/* pv-block-end:sdaeec */}
      {/* pv-editable-zone-end:2n7pqy */}
    </div>
  );
}
